### ISSUE TITLE
Can't find framework header

### ISSUE THREAD

**Issue by felixdkatt** [urbanairship/ios-library#103]
followed the instructions on the website and i got

/Users/felix/HomeMe/homeme-ios/Airship/AirshipKit/copy_header_imports.sh: line 8: cd: /Users/me/Library/Developer/Xcode/DerivedData/MyApp-ghucfhbqygxxydgebuhorsaxjloy/Build/Products/Debug-iphonesimulator/AirshipKit.framework/Headers: No such file or directory

Instructions for install as i read them were to drag over project file into top level of my project
then embed the framework and verify that it was in the link libraries

i did so and it says it cant find files. I don't see anywhere in your documentation about adding header file paths when doing it with the Airship kit. Any suggestions?

![airshiperr](https://cloud.githubusercontent.com/assets/364910/12523803/efedc34e-c10d-11e5-9570-c592bb00b67d.jpg)

**Comment by rlepinski** [comment]
We have changed the way we package airshipkit. If its still an issue in 8.1.0 can you please reopen. Thanks!
