### ISSUE TITLE
AppVersion for userAgent is using build number instead of app release number

### ISSUE THREAD

**Issue by mzentric** [urbanairship/ios-library#109]
NSString *appVersion = [info objectForKey:(NSString*)kCFBundleVersionKey];

This line of code produces the build number rather than the release app version numbers. This number is reflected in the website that is used by marketing/non development users and is not easily readable number they can correlate to app release versions on the app store.  The UA web site displays this at Segment/Device Property Tags/iOS App Version which is misleading and should say "build version" 

According to Apple documentation

CFBundleShortVersionString

CFBundleShortVersionString (String) specifies the release version number of the bundle, which identifies a released iteration of the application. The release version number is a string comprised of three period-separated integers. The first integer represents major revisions to the application, such as revisions that implement new features or major changes. The second integer denotes revisions that implement less prominent features. The third integer represents maintenance releases.

The value for this key differs from the value for “CFBundleVersion,” which identifies an iteration (released or unreleased) of the application.

CFBundleVersion

CFBundleVersion (String) specifies the build version number of the bundle, which identifies an iteration (released or unreleased) of the bundle. This is a monotonically increased string, comprised of one or more period-separated integers. This key is not localizable.

**Comment by marc-scig** [comment]
Hi @mzentric,

Thanks for the info. We've identified this as a problem area based on other customer feedback and will be modifying this behavior in an upcoming release.

**Comment by junkinthetrunk** [comment]
I have a pull request ready, waiting on the authorization under "junkinthetrunk" to send it in

**Comment by rlepinski** [comment]
Fixed in 7.2.0
