### ISSUE TITLE
Black screen issue

### ISSUE THREAD

**Issue by tariq235** [urbanairship/ios-library#110]
We are running into a strange black screen problem.

Earlier we were using urbanairship library 5.x and several users reported black screen. 

Steps -
1. Tap few push notifications
2. After some use app started showing black screen.
3. And crash for few users on receiving push on black screen (crash log attached).

Now when we have updated to the latest UA sdk, problem got resolved automatically. We have tested rigorously and not able to reproduce black screen issue on ios9.x. But now some of iOS10 users are reporting black screen.

App is not crashing it just show a black screen. Even i restart device or kill the app from background. Always a black screen.

Can someone please help on this. Attached both video and rare crash logs.
[Movie Recording.mov.zip](https://github.com/urbanairship/ios-library/files/424172/Movie.Recording.mov.zip)
![pasted image at 2016_08_17 07_34 pm](https://cloud.githubusercontent.com/assets/349211/17762652/3e96e036-6530-11e6-8c69-9e77303deb5c.png)

**Comment by rlepinski** [comment]
Not sure whats going on here, we may need more info from you. Can you provide verbose logs that capture the issue? We will also need to look at your app delegate to see if we can see anything odd going on. If you have a support contact, please email them with your app info.

The first thing you may want to try is disabling automatic integration and adding the app delegate hooks directly - http://docs.urbanairship.com/platform/ios.html#automatic-integration. That will rule out the `UAAppDelegateProxy.m`.

**Comment by tariq235** [comment]
@rlepinski There are no exact steps to reproduce black screen issue but we have noticed whenever there is a black screen then we have following logs -

2016-08-19 11:07:49.258 Involvio[252:59345] LayerKit client v0.21.0 loaded
2016-08-19 11:07:49.688 Involvio[252:59345] [E] __52+[UAirship handleAppDidFinishLaunchingNotification:]_block_invoke [Line 319] [UAirship takeOff] was not called in application:didFinishLaunchingWithOptions:
2016-08-19 11:07:49.689 Involvio[252:59345] [E] __52+[UAirship handleAppDidFinishLaunchingNotification:]_block_invoke [Line 320] Please ensure that [UAirship takeOff] is called synchronously before application:didFinishLaunchingWithOptions: returns

**Comment by rlepinski** [comment]
@tariq235 Could you post your app delegate method where you call takeOff? Please make sure to omit any app keys/secrets

**Comment by rlepinski** [comment]
Closing until we get more info.
