### ISSUE TITLE
Can't use UANotificationAction in iOS9 due to UNNotificationActionOptions being available only in iOS10

### ISSUE THREAD

**Issue by Ataman11** [urbanairship/ios-library#115]
Hello,

Maybe I am missing something but `UANotificationAction` has options param which is of type `UNNotificationActionOptions`. When I try to use `UANotificationAction` in swift, i.e 
`let action = UANotificationAction(identifier: "id", title: "Action", options: [.authenticationRequired, .foreground])`,
it doesn't complain about only iOS10 availability for `UNNotificationActionOptions`. But if I set options explicitly i.e. `let options: UNNotificationActionOptions =  [.authenticationRequired, .foreground]` and then `let action = UANotificationAction(identifier: "id", title: "Action", options: options)` it does complain. I would prefer to do it the latter way in my code as I have a lot of actions for different categories and it is nice to have a separate method which just returns a set of options for a given action type.

Thanks.

**Comment by rlepinski** [comment]
@Ataman11 usually enums are ok to use in older iOS versions as they are just NSUInteger constants. Ill look into today.

**Comment by rlepinski** [comment]
@Ataman11 Yep, I am able to reproduce your issue. Looking into provided `UANotificationActionOptions` for compatibility.

**Comment by Ataman11** [comment]
Thanks @rlepinski.

**Comment by rlepinski** [comment]
@Ataman11 Just released 8.1.0.

If you are using cocaopods, we tried pushing an update and its returning a 500. We will try again late.

**Comment by Ataman11** [comment]
Thanks again @rlepinski.
