### ISSUE TITLE
Add support for UNTextInputNotificationAction

### ISSUE THREAD

**Issue by Ataman11** [urbanairship/ios-library#116]
Hello again,

While working on adding actions for iOS10 push notifications I noticed that it is not possible to create a `UNTextInputNotificationAction` using the UA iOS SDK. Would it be possible to add support for this type of action with fallback support to old style text input action for iOS9?

Thanks,
Artem

**Comment by rlepinski** [comment]
@Ataman11 We will look into it. 

Short term, if we exposed the two conversion methods on UANotificaitonAction then you could extend it and provide your own - https://github.com/urbanairship/ios-library/blob/master/AirshipKit/AirshipKit/UANotificationAction+Internal.h#L37.

**Comment by Ataman11** [comment]
Hi @rlepinski, not sure if I am following 100%. Let's say I create `UANotificaitonAction` using current init method. How would I make it a `UNTextInputNotificationAction`?

**Comment by rlepinski** [comment]
@Ataman11 We will open up our UANotificationAction to be extendible so you can do something like:
```
open class CustomTextAction: UANotificationAction {
    open private(set) var textInputButtonTitle: String = "";
    open private(set) var textInputPlaceholder: String = "";

    public convenience init(identifier: String, title: String, options: UANotificationActionOptions = [], textInputButtonTitle: String, textInputPlaceholder: String) {
        self.init(identifier: identifier, title: title, options: options);

        self.textInputButtonTitle = textInputButtonTitle;
        self.textInputPlaceholder = textInputPlaceholder;
    }

    @available(iOS 10.0, *)
    override open func asUNNotificationAction() -> UNNotificationAction {
        return UNTextInputNotificationAction(identifier: self.identifier,
                                             title: self.title,
                                             options: UNNotificationActionOptions.init(rawValue: self.options.rawValue),
                                             textInputButtonTitle: self.textInputButtonTitle,
                                             textInputPlaceholder: self.textInputPlaceholder)
    }

    open override func asUIUserNotificationAction() -> UIUserNotificationAction {
        let action: UIMutableUserNotificationAction = super.asUIUserNotificationAction().mutableCopy() as! UIMutableUserNotificationAction;
        action.behavior = .textInput;

        return action;
    }
}
```
Then in 8.2.0 we will add a proper UATextINputNotificationAction.

**Comment by Ataman11** [comment]
Right, that makes sense! Thanks @rlepinski.

**Comment by rlepinski** [comment]
@Ataman11 Released 8.1.1 that should allow the action above to work.

**Comment by Ataman11** [comment]
Thanks @rlepinski!

**Comment by rlepinski** [comment]
@Ataman11 We added a UATextInputNotificationAction in 8.2.0
