### ISSUE TITLE
Latest release not compiling with Carthage

### ISSUE THREAD

**Issue by weissazool** [urbanairship/ios-library#117]
Getting the following error when trying to update to 8.1 via Carthage:

A shell task (/usr/bin/xcrun xcodebuild -project .../Carthage/Checkouts/ios-library/AirshipKit/AirshipKitSource.xcodeproj CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES -list) failed with exit code 74:
xcodebuild: error: Unable to read project 'AirshipKitSource.xcodeproj' from folder '.../Carthage/Checkouts/ios-library/AirshipKit'.
	Reason: Project .../Carthage/Checkouts/ios-library/AirshipKit/AirshipKitSource.xcodeproj cannot be opened because it is missing its project.pbxproj file.

**Comment by rlepinski** [comment]
@weissazool Looks like we have a left over project file. We will do a patch release tomorrow. Thanks for letting us know.

**Comment by rlepinski** [comment]
@weissazool Actually i just removed it and retagged. Could you give it a shot now?

**Comment by rlepinski** [comment]
I verified it builds. Closing for now. Please reopen if you are still having issues.

**Comment by weissazool** [comment]
Yep, works. Thanks!
