### ISSUE TITLE
Notifications with empty alert are treated as non silent by UA, but as silent by iOS.

### ISSUE THREAD

**Issue by capitangolo** [urbanairship/ios-library#118]
Hi,

I'm experiencing a problem where receiving a foreground notification fails, but same one works on the background. iOS 10.

We think it's caused by having an empty 'alert' on the notification payload.

On [0], if the notification is not silent, UA delegates on the new UNNotification API.

As of [1] UAUtils isSilentPush:, if the notification payload contains a value for 'alert' it returns NO as the notification is not silent.

However if the alert value is empty, isSilentPush: returns NO but iOS threats it as silent. As a result, neither the UA delegate nor the UNNotification API are called.

[0] https://github.com/urbanairship/ios-library/blob/8.0.3/Airship/Common/UAAppIntegration.m#L74

[1] https://github.com/urbanairship/ios-library/blob/9907c7aff2635f3d7a27940619145758de48f58e/AirshipKit/AirshipKit/UAUtils.m#L286

**Comment by rlepinski** [comment]
@capitangolo Thanks for the report. I will take a look shortly.

**Comment by rlepinski** [comment]
@capitangolo Fixed in 8.1.3. Thanks!
