### ISSUE TITLE
Problem with pod 'UrbanAirship-iOS-SDK', '~> 8.1.0'

### ISSUE THREAD

**Issue by mperovic** [urbanairship/ios-library#119]
# Report

## What did I do?
After updating UrbanAirship to 8.1.2 (`pod update`) my Pod.xcodeproj file is damaged. When I try to open it directly message: **"/Users/myName/myProjectFolder/Pods/Pods.xcodeproj cannot be opened because the project file cannot be parsed."** is shown.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : bcylin - https://github.com/bcylin/Specs.git @ 95581b9904d0dff63295c29923f823c4cdd6629a
               master - https://github.com/CocoaPods/Specs.git @ 70734e1a3e43fc2cf138c9e6b1bd57b54ef3280a
               popcorntimetv - https://github.com/PopcornTimeTV/Specs.git @ 8a4b1649abaf174132f97b78961ae711496bbb85
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

project 'MyProject.xcodeproj'

target 'MyProject' do
	platform :ios, '9.0'
	use_frameworks!
	
	pod 'UrbanAirship-iOS-SDK'
end
```

## Unsuccessful solutions
I tried a lot of things: Restart computer, completely uninstal and install CocoaPods, delete Pod folder and execute `pod install` but without result.

## Solution
Revert UrbanAirship to 8.0.4 (`pod 'UrbanAirship-iOS-SDK', '~> 8.0.0'`).

**Comment by hcrowell** [comment]
Hi @mperovic I was unable to reproduce this issue (details below). Can you update your cocoapods and try again please?

Podfile

```
source 'https://github.com/CocoaPods/Specs.git'

project 'test/test.xcodeproj'

target 'test' do
   platform :ios, '9.0'
   use_frameworks!

   pod 'UrbanAirship-iOS-SDK'
end
```

```
$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.2.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.2.0.beta.1

Analyzing dependencies
Downloading dependencies
Using UrbanAirship-iOS-SDK (8.1.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

I was able to open test.xcodeproj as we as the test.xcworkspace with no issues.

**Comment by mperovic** [comment]
@hcrowell I tried on second iOS project and result is the same :(

Also I tried with CocoaPods 1.2.0 beta 1 but without any luck. I know that's weird. Tomorrow I'll try on another computer.

**Comment by rlepinski** [comment]
@mperovic could you try `pod install --verbose` and post the logs? Thanks

**Comment by rlepinski** [comment]
@mperovic Also can you zip the second project and post it here?

**Comment by ckalolass** [comment]
@mperovic It seems that I have the same issue. Could you look inside generated file `Pods.xcodeproj/project.pbxproj`. Do you have a strings inside like `"-D_UA_VERSION=\\"{UA version here}\\""`? In my case when i replace `\\` to `\\\` project start working fine. The problem is that my colleague has the same versions of base components (macOs, Xcode, cocoapods) and he don't observing this issue.

**Comment by mperovic** [comment]
@ckalolass you saved my day. It works perfectly 👍

**Comment by mperovic** [comment]
@rlepinski sorry for not responding to your messages, I was on vacation for last 7 days.

**Comment by ckalolass** [comment]
@rlepinski My answer contain a workaround, maybe this helps you to find real issue.

**Comment by rlepinski** [comment]
@ckalolass Yep that helps. Ill look into removing that in a patch. 

My guess is one of cocoapods dependencies is different between installs. Could someone run `gem list cocoapods` on a machine that experiences this issue?

**Comment by mperovic** [comment]
*** LOCAL GEMS ***

cocoapods (1.1.1)
cocoapods-core (1.1.1)
cocoapods-deintegrate (1.0.1)
cocoapods-downloader (1.1.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.0.0)
cocoapods-trunk (1.1.1)
cocoapods-try (1.1.0)

**Comment by rlepinski** [comment]
@mperovic Yeah, each of those have there own set of dependencies. I do not know the gem command off the top of my head on how to get a full dependency tree.

**Comment by ckalolass** [comment]
@rlepinski @mperovic Looks like i found a bottleneck. The gem `xcodeproj` should be updated to the latest 1.4.1 version. Issue on my machine is gone now.

**Comment by rlepinski** [comment]
@ckalolass Awesome!

We have a patch in the works that removes the use of the compiler_flags and fixes a few other issues. Ill post here when its released.

**Comment by rlepinski** [comment]
8.1.4 is out with a fix for older versions of `xcodeproj`
