### ISSUE TITLE
Pod broken?

### ISSUE THREAD

**Issue by garethcurtis** [urbanairship/ios-library#120]
Hi,

Just trying to integrate UA via the CocoaPods method and it seems to break the Pods project. I've even tried on a brand new Swift 3.0 Xcode project straight out of the box with a only the UA Pod being installed and when I open the workspace I immediately get 'can't open the Pods.project'. This is using Xcode 8.1 with the 8.4 version of the Pod.

Any ideas please?

Thanks.

<img width="1512" alt="screen shot 2016-12-13 at 10 02 52" src="https://cloud.githubusercontent.com/assets/9380217/21135932/6158bdb4-c11b-11e6-87dd-2ede0e263207.png">

**Comment by rlepinski** [comment]
@garethcurtis Take a look at this issue: https://github.com/urbanairship/ios-library/issues/119

I am pretty sure you can update your pod repo and use the latest version of the pod (8.1.4) or update your xcodeproj gem dependency.

**Comment by garethcurtis** [comment]
Weird. I was using 8.1.4, that was a typo above when I said 8.4. I did pod repo update and then pod update again and this time it's fine. Thanks and sorry!

**Comment by rlepinski** [comment]
Glad its working!
