### ISSUE TITLE
Main thread blocked on app open w/ iOS 10 & Universal clipboard

### ISSUE THREAD

**Issue by darrenclark** [urbanairship/ios-library#121]
Hey,

We noticed that the UrbanAirship SDK (v8.1.4) can cause the main thread to be blocked (for up to 15 seconds I believe) on app open if the user has Universal Pasteboard enabled between an iOS 10 device & a Sierra Mac.  Specifically, it appears this line of code is causing the issue:

https://github.com/urbanairship/ios-library/blob/master/AirshipKit/AirshipKit/UAChannelCapture.m#L87

Also see: https://openradar.appspot.com/28787338.  As far as we can tell, it blocks the thread while synchronizing with the Mac when reading the contests of the pasteboard.

Any ideas on a fix?  Unfortunately it appears the docs don't mention anything about `UIPasteboard` being thread safe, so I don't believe it can be moved off the main thread.

Thanks,
Darren

(cc @delannoyk)

**Comment by crow** [comment]
Thank you very much for bringing this to our attention.

**Comment by hcrowell** [comment]
@darrenclark A workaround is to disable channel capture via http://docs.urbanairship.com/reference/libraries/ios/latest/Classes/UAConfig.html#/c:objc(cs)UAConfig(py)channelCaptureEnabled

**Comment by hcrowell** [comment]
Hey @darrenclark , Please let us know if the workaround above ^ (disable channel capture) is sufficient for you, so that we clean close this issue as well as close the ticket you submitted to our support team. We will look into this issue further after the holidays. Thank you!

**Comment by darrenclark** [comment]
Hi @hcrowell, thanks for the response!  I think this should work for us!  I just wanted to verify, channel capture is really only a debugging tool, eh? Disabling it won't prevent the SDK from functioning regularly?

**Comment by hcrowell** [comment]
Hi @darrenclark , you're correct that disabling channel capture won't prevent the SDK from functioning regularly. Glad to hear disabling channel capture will work for you! I will close this issue and let our support team know to also close the support ticket. Thank you!

**Comment by darrenclark** [comment]
Great, thanks!

**Comment by kurzee** [comment]
For the record, this is still an issue and causing major lock ups for users. Definitely needs to be disabled by default or more widely documented.

cc @hcrowell

**Comment by rlepinski** [comment]
@kurzee what SDK version are you on? We try to disable it as much as possible now. Its only enabled if not explicitly disabled in the config and background push is disabled.

**Comment by kurzee** [comment]
On `8.6.3`, but I see version `9.0.0`+ just hit the last week or so.

>Its only enabled if not explicitly disabled in the config and background push is disabled.

Sounds like that basically means enabled by default? 😜

In my particular scenario, an inherited project, the configuration file had no explicit setting for `isChannelCaptureEnabled`. Wouldn't it be safer for a user of the SDK to not have to worry about such a case and the value of `isChannelCaptureEnabled` default to `false`? Or at least have that noticeably documented for the SDK's configuration steps?

Side note, it was also spooky to spot that an SDK was consuming a user's pasteboard on foregrounding with no obvious purpose.

**Comment by rlepinski** [comment]
Yeah, its conditional if its enabled, but we tried to disable as much as possible while still solving the issue of debugging a users application without any dev resources.

For you, it sounds like you should disable it through app config.
