### ISSUE TITLE
Development push notification certificate

### ISSUE THREAD

**Issue by krzysztofp** [urbanairship/ios-library#122]
I Can't upload the development push notification certificate, I keep on getting the same error:
![image](https://cloud.githubusercontent.com/assets/1634660/21817632/0ed70e82-d765-11e6-9230-fbc2db14f70b.png)

I'm more than sure my certificate is a development one. I'm using the following  command to convert it from cer to pem format:

    openssl x509 -in aps.cer -inform der -outform pem -out certificate-development.pem

**Comment by rlepinski** [comment]
@krzysztofp This is a question for our support team. Please email support@urbanairship.com. We like to keep github issues focused on code issues, not general support. Plus our support team is generally better at anything certificate related.

**Comment by krzysztofp** [comment]
hey @rlepinski thank you for the suggestion. Unfortunately their support is only for paying customers which in my case is a typical egg-n-chicken problem, as I'm not able to configure the app, I'm able to push it live - or maybe I need to switch to another Push Notifications provider who can help me get rolling before I can convert to a paying customer.

My question is not covered in the Community Forum and other Knowledgebase materials. There are very few in fact.

**Comment by rlepinski** [comment]
Create a new post in the forum and someone will help you shortly.

**Comment by krzysztofp** [comment]
Ok, I [did](https://support.urbanairship.com/hc/en-us/community/posts/115000156563-Can-t-upload-Apple-Push-notification-certificate). Many thanks.
