### ISSUE TITLE
UATagUtils.createTags is deprecated

### ISSUE THREAD

**Issue by matzino** [urbanairship/ios-library#123]
UATagUtils.createTags(tags: UATagType) is deprecated ! I should use device property tags instead but can't find anything that helps in the docs. 

````
let push = UAirship.push() 
push?.userPushNotificationsEnabled = true 
push?.tags = UATagUtils.createTags([.deviceType, .country, .language, .timeZoneAbbreviation]) as! [String]
````

How can I set the device property tags like before the push.tags?

**Comment by rlepinski** [comment]
@matzino Here are the [docs on property tags]( http://docs.urbanairship.com/reference/device-property-tags.html). The tags are auto generated for everyone, so all you have to do is use the tags.

If for whatever reason the tags are not working for you, you can always copy take the code and copy it into your project:
https://github.com/urbanairship/ios-library-dev/blob/6.4.0/Airship/Common/UATagUtils.h
https://github.com/urbanairship/ios-library-dev/blob/6.4.0/Airship/Common/UATagUtils.m

**Comment by matzino** [comment]
If I understand it right, I have nothing to do from the developer perspective? The tags would now automatically created from the SDK and can be used from the UA-Backend. Then I can completely remove the line:

`push?.tags = UATagUtils.createTags([.deviceType, .country, .language, .timeZoneAbbreviation]) as! [String]`

If it is so, you can close this issue.

**Comment by rlepinski** [comment]
@matzino They are actually generated on our backend, not the SDK. But yeah thats the idea. They should be available with no action on your part.
