### ISSUE TITLE
didRegisterUserNotificationSettings doesn't work for ios10

### ISSUE THREAD

**Issue by ShahriatHossain** [urbanairship/ios-library#124]
Hi, 
it seems that didRegisterUserNotificationSettings  this method is deprecated for ios10 then what should be the alternate method for this one for ios10?

**Comment by rlepinski** [comment]
@ShahriatHossain iOS 10 we use the new UNNotificationCenter APIS. You can either move to using that API directly and continue to use didRegisterUserNotificationSettings for older devices, OR we provide a backwards compatible callback in our [UARegistrationDelegate -](http://docs.urbanairship.com/reference/libraries/ios/latest/Protocols/UARegistrationDelegate.html). 

The method `notificationRegistrationFinishedWithOptions:categories:` is the closet equivalent to the method  `didRegisterUserNotificationSettings`. You can set the registrationDelegate on the UAPush instance.

**Comment by ShahriatHossain** [comment]
actually I am using this method didRegisterUserNotificationSettings to
subscribe firebase cloud messaging topic after getting list of notices from
api in my xamarin.ios project on appdelegate.cs file, as this method only
working for ios9 or earlier and I am just getting push notification on
those earlier devices but not for ios10 so I need to find another method
where I can place my code of subscription on appdelegate class, can you say
which method I can use so that once app is running first time and the
method hit run those subscribe snippet of codes.

If I place those codes on this method FinishedLaunching but I am not
getting any topic from api and list is showing 0 as the api is requesting
asynchronously, do you have any suggestion?

Regards
--
*Shahriat Hossain*
Sr. Software engineer
ImplevistaBD Pvt. Ltd.
Consultant for Microsoft .net, php and ios/android native app development
Associate member of BCS (Bangladesh Computer Society)

Mobile: +880-1923508304

**Comment by rlepinski** [comment]
@ShahriatHossain Are you using Urban Airship? If not, please do not file issues on our github repo. Stackoverflow is a better place for that sort of question.
