### ISSUE TITLE
AirshipKit 8.1.3 is not iOS 8,9 compatible as described in the version history

### ISSUE THREAD

**Issue by jaishankar** [urbanairship/ios-library#126]
Team,

The changelog and podspec of AirshipKit 8.1.3  says deployment target for Airship Kit is iOS 8. https://docs.urbanairship.com/reference/libraries/ios/latest/ios_changelog.txt

But the AirshipKit.podspec uses "USerNotifications" in the s.ios_frameworks which is iOS 10 and above framework. 
https://github.com/urbanairship/ios-library/blob/8.1.3/UrbanAirship-iOS-SDK.podspec

Can you Please fix this podspec by removing "UserNotifiactions" in the s.ios.frameworks, so that it is iOS 8 and 9 compatible?

**Comment by BrianBatchelder** [comment]
The Deployment Target for an iOS build can be "below" the Base SDK the app is built against. See this [StackOverflow question](http://stackoverflow.com/questions/18568572/whats-the-meaning-of-base-sdk-ios-deployment-target-target-and-project-in-xc/22536773#22536773). The Urban Airship SDK can be deployed to iOS 8 or 9, but requires the Base SDK to be >= iOS 10, which is the default for Xcode 8. When run on a device with iOS 8 or 9, our SDK will not use any iOS 10 frameworks, e.g. UserNotifications.
