### ISSUE TITLE
Xcode8+ Carthage exit code 65

### ISSUE THREAD

**Issue by DenDeze** [urbanairship/ios-library#127]
*** Building scheme "AirshipKit" in Airship.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace "/Users/thisone/Documents/Materiaal Beheer/Carthage/Checkouts/ios-library/Airship.xcworkspace" -scheme AirshipKit -configuration Release -derivedDataPath /Users/thisone/Library/Caches/org.carthage.CarthageKit/DerivedData/ios-library/8.2.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

**Comment by crow** [comment]
I'm unable to replicate this error while installing AirshipKit via carthage 0.20.1

Could you please provide the following details?:

- Carthage version (carthage version)
- xcodebuild version (xcodebuild -version)
- xcodebuild output*

*During install carthage will output a link to the xcode build output .log file
for example:
"xcodebuild output can be found in /var/folders/yj/st6x4b4n2j146njwc09f3xr5t778vm/T/carthage-xcodebuild.MDXic8.log"

**Comment by rlepinski** [comment]
Closing for now. Please reopen with the requested information if you are still having issues.
