### ISSUE TITLE
Hundreds of warnings related to dsym generation in Xamarin ios project on build

### ISSUE THREAD

**Issue by alanag13** [urbanairship/ios-library#128]
I'm not sure if this should be posted here or in the Xamarin-component project, but...

When building a Xamarin project that references the iOS dll, a `_GenerateFrameworkDebugSymbols` task is being called for  AirshipKit and I receive over 200 warnings in the build output similar to (looks like essentially one for every .o file / architecture in the UA SDK):

`EXEC : warning : (arm64) /Users/swizzler/Library/Developer/Xcode/DerivedData/Airship-bkdnzgzpkugunmgdhbfdgxcsuadk/Build/Intermediates/AirshipKit.build/Release-iphoneos/AirshipKit.build/Objects-normal/arm64/UAShareAction.o unable to open object file: No such file or directory`

 They do not appear in the IDE, but can be seen in the text output, and `swizzler` is not a user that exists (or has ever existed) on the machine that I am performing the build on. 

My guess is that this is a directory that exists on the machine that performs the build for the framework before it is eventually distributed. I'm not an iOS expert, but from what I can tell I believe this is is being caused by some combination of settings for debug symbol stripping that are incorrect for Release mode in the ios library:

http://jonathanblog2000.blogspot.com/2013/07/xcode-build-settings-for-debug-symbol.html

In particular, I noticed that in the iOS project, "Strip Linked Product" is set to Yes (which would suggest you are trying to remove debug symbols from the release project, which I assume would in turn cause Xamarin to not attempt to generate a dsym file for it) while Deployment postprocessing is set to No -- the link above would suggest that based off of these settings, "Strip Linked Product" would not occur unless Deployment Postprocessing is also set to yes.

I suspect that if these build settings are corrected that the warnings would disappear.

**Comment by rlepinski** [comment]
@alanag13 Thanks for reporting this. You are right about `swizzler` being a build machine and I assume about the build settings. Will look into today and try to have a release ASAP.

**Comment by alanag13** [comment]
@rlepinski this will mean a new release for the xamarin component as well, correct? Just curious since that's what I'm actually consuming.

**Comment by rlepinski** [comment]
@alanag13 Yep. Here is the repo - https://github.com/urbanairship/xamarin-component

We use carthage to build the framework that the xamarin component consumes. I believe we need to do a change to the shared scheme and do a patch release to the component. I will let you know when its out.

**Comment by rlepinski** [comment]
@alanag13 Is it causing any other issues than the warnings?

**Comment by alanag13** [comment]
@rlepinski not from what I can tell, no. Functionality doesn't seem to be affected, which makes sense since it seems these warnings are happening when trying to generate a dsym file. Everything otherwise compiles and runs fine, at least for the functionality that I'm using.

**Comment by rlepinski** [comment]
@alanag13 ok, so i think our settings are correct for majority of applications consuming our framework through carthage, since normally the build will happen on the same machine and the debug symbols will be the local derived data - https://github.com/Carthage/Carthage#known-issues. We will try out the `--no-use-binaries` option and see what that gives us.

**Comment by alanag13** [comment]
@rlepinski Ah I see, so this is a Xamarin-specific problem since that is the only circumstance where the framework would be built beforehand. That makes sense. Thanks for looking, let me know what you come up with.

**Comment by rlepinski** [comment]
@alanag13 Fixed in 4.2.2 of the xamarin component
