### ISSUE TITLE
generate_header_imports.sh doesn't work with spaces in the path

### ISSUE THREAD

**Issue by sixten** [urbanairship/ios-library#129]
It appears that `AirshipKit/Scripts/generate_header_imports.sh` is not quoting/escaping the path for the start of the `find` command it's executing, and thus fails if that path contains spaces.

**Comment by BrianBatchelder** [comment]
Thanks for notifying us of the issue. We will take a look at it ASAP.

**Comment by BrianBatchelder** [comment]
This issue should be fixed in release [8.2.2](https://github.com/urbanairship/ios-library/releases/tag/8.2.2). If this does not resolve your issue, please re-open.
