### ISSUE TITLE
Getting no device property tags

### ISSUE THREAD

**Issue by Fjandin** [urbanairship/ios-library#132]
Somehow my users do not get any device property tags accosiated anymore. (It has worked before)

What i get now is only these:

```
"tag_groups": {
  "ua_background_enabled": ["true"],
  "ua_opt_in": ["true"]
},
```

Where before i also got tags like these:
```
...
"timezone": ["Europe/Paris"],
"ua_android_app_version": ["1.2.1"],
"ua_locale_country": ["US"],
...
```

Any idea why all of a sudden it acts like this?

**Comment by BrianBatchelder** [comment]
@Fjandin: This is a question for our support team. Please email support@urbanairship.com. If you are on a free tier you may need to post to our forums - https://support.urbanairship.com/hc/en-us/community/topics
