### ISSUE TITLE
Deprecated API's warnings (iOS10)

### ISSUE THREAD

**Issue by JuhaO81** [urbanairship/ios-library#133]
When compiling project with iOS 10 as min OS version UA is giving deprecated warnings

- 'UIUserNotificationSettings' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationSettings
- 'UIUserNotificationActionContext' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's -[UNNotificationCategory actions] or -[UNNotificationCategory minimalActions]
- 'UIUserNotificationAction' is deprecated: first deprecated in iOS 10.0 - Use UserNotifications Framework's UNNotificationAction

**Comment by ralepinski** [comment]
@JuhaO81 We still support iOS 8 & 9, so sadly we still have to use those APIs but we only do so for older iOS versions. If you set your deployment target to 8 the warnings will go away, but if you are only supporting 10+ there will be warnings. Not much we can do about that.

**Comment by rlepinski** [comment]
@JuhaO81 We still support iOS 8 & 9, so sadly we still have to use those APIs but we only do so for older iOS versions. If you set your deployment target to 8 the warnings will go away, but if you are only supporting 10+ there will be warnings. Not much we can do about that.

**Comment by JuhaO81** [comment]
@rlepinski Could you consider suppressing deprecation warnings in headers? Example below 

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
- (nullable UIUserNotificationAction *)asUIUserNotificationAction;
#pragma GCC diagnostic pop

**Comment by rlepinski** [comment]
@JuhaO81 We will take a look at some options in future release. I know its annoying.

**Comment by JuhaO81** [comment]
@rlepinski We are having thread-warnings-as-errors flag on and this kind of breaks the build now.

**Comment by rlepinski** [comment]
@JuhaO81 We will hopefully address the warnings in SDK 8.4.0 that should be released this week or next.

**Comment by JuhaO81** [comment]
![homer-simpson-04-happy-icon](https://user-images.githubusercontent.com/29195184/27623117-9cf72140-5be3-11e7-9ca9-9af1dee391de.png)

**Comment by rlepinski** [comment]
@JuhaO81 We believe 8.4.1 should take care of the warnings you are seeing. If not, please reopen and we can do another patch release.
