### ISSUE TITLE
Support for multiple UNNotificationServiceExtension

### ISSUE THREAD

**Issue by avnerbarr** [urbanairship/ios-library#134]
Is there a way to embed multiple `UNNotificationServiceExtension` to my app? I need to roll a custom extension alongside the UA extension.

**Comment by ralepinski** [comment]
@avnerbarr Not that I am aware of. You most likely need to extend our extension to make it work. What is your use case? I might be able to help with some sample code, if not we may need to make the extension service easier to extend.
