### ISSUE TITLE
Auto deep link without click when app is in foregound

### ISSUE THREAD

**Issue by aainanewscorp** [urbanairship/ios-library#146]
When app is in the foreground and getting push notification having a deep link, it's automatically navigating to that screen as per deep link, that is causing weird behaviour. Deep link should always happen when user click on push notification. We have applied temporary solution for now. But what can be the solution for this issue?

**Comment by rlepinski** [comment]
How are you using the deep link action? Do you provide your own? Sdk version?

**Comment by rlepinski** [comment]
Nvm, we found an issue in our actions were the predicate is not being applied that would reject foreground push. We will have a fix today.

**Comment by rlepinski** [comment]
Released in 8.5.2
