### ISSUE TITLE
Unknown iOS versions in .xib in Xcode 9

### ISSUE THREAD

**Issue by shahrukhnewscorp** [urbanairship/ios-library#154]
This issue gives **"ibtoold WARNING: Unhandled destination metrics: (null)"** warning in archive logs for a bitcode enabled app even with the latest release of UrbanAirship SDK (8.6.0).
Could you resolve this issue or help me to get a fix.

**Comment by ralepinski** [comment]
We will take a look. Thanks for reporting the issue.

**Comment by BrianBatchelder** [comment]
It looks like this is a known Xcode issue: https://github.com/lionheart/openradar-mirror/issues/18666 . We will keep an eye on it.
