### ISSUE TITLE
Cannot install the pod SDK anymore

### ISSUE THREAD

**Issue by geraldeersteling** [urbanairship/ios-library#157]
While trying to run `pod install` the installation hangs on `Installing UrbanAirship-iOS-SDK`, all other pods install just fine. Everything works fine whenever I comment out installing the SDK, the pod install succeeds but then I've got no UA in my project of course.

What happened to the pod? Was just working fine a day ago.

I'm using the latest Cocoapods on High Sierra.

**Comment by rlepinski** [comment]
We pushed an update. Could you post your pod file, pod lock file, and logs? Make sure your pod repo is up to date.

**Comment by geraldeersteling** [comment]
It works again! Thanks for pushing the update!

> Do you still need the podfile?

**Comment by rlepinski** [comment]
Nope. Glad its working.
