### ISSUE TITLE
Unable to build with Xcode 9.2 using the new build system

### ISSUE THREAD

**Issue by spekke** [urbanairship/ios-library#161]
We are using CocoaPods  1.4.0.rc.1 to integrate UrbanAirship-iOS-SDK to our project and we get the following error:

```
:-1: unable to build node: '/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist' (node is produced by multiple commands; e.g., '1fe6e101de90eb9023865ab07de3d46915cd38196504071e6ee342bfdf6b0fe5:CopyPlistFile //DerivedData/buzxxruyxmmoyjcbkmqwwygkpedy/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist /Work/Personal/ios-library/AirshipKit/AirshipResources/ios/Info.plist' and '1fe6e101de90eb9023865ab07de3d46915cd38196504071e6ee342bfdf6b0fe5:ProcessInfoPlistFile DerivedData/buzxxruyxmmoyjcbkmqwwygkpedy/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist /Pods/Target Support Files/UrbanAirship-iOS-SDK/ResourceBundle-AirshipResources-Info.plist')
```

and warning:
```
warning: duplicate output file '/Library/Developer/Xcode/DerivedData/-buzxxruyxmmoyjcbkmqwwygkpedy/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist' on task: ProcessInfoPlistFile /Library/Developer/Xcode/DerivedData/iphoneshell-buzxxruyxmmoyjcbkmqwwygkpedy/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist /Pods/Target Support Files/UrbanAirship-iOS-SDK/ResourceBundle-AirshipResources-Info.plist (in target 'UrbanAirship-iOS-SDK-AirshipResources')
```

It seems like deleting `Info.plist` from `AirshipKit/AirshipResources/ios/` fixes the problem. Do we need an `Info.plist` for a resource bundle?

**Comment by BrianBatchelder** [comment]
I am unable to reproduce this problem. Could you please remove your derived data folder, Podfile.lock and Pods folder, and then `pod install` and try the build again? Let us know if the problem persists.

**Comment by spekke** [comment]
Here's an example project where it's reproducible:
[UrbanAirshipExample.zip](https://github.com/urbanairship/ios-library/files/1570780/UrbanAirshipExample.zip)

Step to reproduce:
* Run `bundle install` to make sure we use latest version of CocoaPods
* Run `bundle exec pod install`
* Now build from Xcode or run `xcodebuild -workspace "UrbanAirshipExample.xcworkspace" -scheme "UrbanAirshipExample" -configuration "Debug" -sdk "iphonesimulator" -destination "name=iPhone 7" clean build`

```
Build settings from command line:
    SDKROOT = iphonesimulator11.2

Removing '~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build'
note: Planning build
note: Constructing build description
Build system information
warning: Target Pods-UrbanAirshipExample product Pods_UrbanAirshipExample cannot link framework Foundation.framework

Build system information
warning: missing creator for mutated node: ('~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/AirshipResources') (in target 'UrbanAirship-iOS-SDK-AirshipResources')

Build system information
warning: duplicate output file '~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist' on task: ProcessInfoPlistFile ~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist ~/tmp/UrbanAirshipExample/Pods/Target Support Files/UrbanAirship-iOS-SDK/ResourceBundle-AirshipResources-Info.plist (in target 'UrbanAirship-iOS-SDK-AirshipResources')

Build system information
error: unable to build node: '/~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist' (node is produced by multiple commands; e.g., 'ba3be4b6d7c7123d90255d2fdb3cc34d76a06d319196ced5f5fa78c5d415cd23:CopyPlistFile ~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist ~/tmp/UrbanAirshipExample/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/Info.plist' and 'ba3be4b6d7c7123d90255d2fdb3cc34d76a06d319196ced5f5fa78c5d415cd23:ProcessInfoPlistFile ~/Library/Developer/Xcode/DerivedData/UrbanAirshipExample-gwinzraadrzpizfrzlijnrsxmyei/Build/Products/Debug-iphonesimulator/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist ~/tmp/UrbanAirshipExample/Pods/Target Support Files/UrbanAirship-iOS-SDK/ResourceBundle-AirshipResources-Info.plist')

** BUILD FAILED **
```

**Comment by BrianBatchelder** [comment]
@spekke Thanks for the sample code. We'll take a look at it today.

**Comment by BrianBatchelder** [comment]
You are setting the "BuildSystemType" to "Latest" in UrbanAirshipExample.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, thereby opting-in for Xcode's new build system. We are not yet supporting the new build system, as it is an opt-in preview . See "Building and Linking" in [What's New in Xcode 9](https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/WhatsNewXcode/xcode_9/xcode_9.html).

Thank you for bringing this to our attention. We will make sure our SDK works with the new build system when it is released. Until that time, please opt-out of the new build system for builds.

**Comment by muralinewscorp** [comment]
Shall we have this new build support now in our urbanairship ?

@BrianBatchelder

**Comment by BrianBatchelder** [comment]
Support for Xcode's new build system was released in SDK 9.0. Upgrading your SDK will allow you to build.

**Comment by iosdev27** [comment]
Hi, this still seems to be an issue. I'm using XCode 9.3. 


Showing Recent Messages
:-1: unable to build node: '/Users/vc/Library/Developer/Xcode/DerivedData/THDConsumer-efwiajbllfcnbhawgcbhvraxzwir/Build/Products/Debug-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist' (node is produced by multiple commands; e.g., 'd6b12ce58de3dd5caa4dcce9b693d67cc0183c242923f7962a9f9a86ecf28a69:Debug:CopyPlistFile /Users/vinodchopra/Library/Developer/Xcode/DerivedData/THDConsumer-efwiajbllfcnbhawgcbhvraxzwir/Build/Products/Debug-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist /Users/vc/Desktop/ConsumerApp/THDPro/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/Info.plist' and 'd6b12ce58de3dd5caa4dcce9b693d67cc0183c242923f7962a9f9a86ecf28a69:Debug:ProcessInfoPlistFile /Users/vc/Library/Developer/Xcode/DerivedData/THDConsumer-efwiajbllfcnbhawgcbhvraxzwir/Build/Products/Debug-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist /Users/vc/Desktop/ConsumerApp/THDPro/Pods/Target Support Files/UrbanAirship-iOS-SDK/ResourceBundle-AirshipResources-Info.plist')

**Comment by BrianBatchelder** [comment]
Which SDK version are you using? Can you try removing all of the DerivedData?

**Comment by iosdev27** [comment]
Here is the pod info:
pod 'UrbanAirship-iOS-SDK', :git => 'https://github.com/urbanairship/ios-library.git', :tag => '9.1.0', :modular_headers => false

Also many other files are erroring out with a no rule to build them. Here is an example.


Showing Recent Messages
:-1: missing input '/Users/vc/Desktop/ConsumerApp/THDPro/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/UADefaultMessageCenterPlaceholderIcon.png' and no rule to build it

**Comment by iosdev27** [comment]
I removed all DerivedData, and still getting the same errors.

**Comment by BrianBatchelder** [comment]
Have you tried your example project from above? I believe I verified that it worked with that project.

**Comment by iosdev27** [comment]
Hi yes, I was able to build the project above, also was to resolve the issue on the local project. It just required some env. cleanup.

However I'm seeing the follwing issue now: "UAWebViewDelegate" is not being recognised. Do I need to do any specific bridging header imports for UAWebViewDelegate to be visible?

**Comment by BrianBatchelder** [comment]
`UAWebViewDelegate` had been deprecated, and was removed in version 9. Please see the [migration guide](https://github.com/urbanairship/ios-library-dev/blob/master/Documentation/Migration/Migration%20Guide.md#classes-1).

Please open a new issue if you have other issues.

**Comment by Mani0080** [comment]
Xcode Version: 10.3.
Using 
pod 'UrbanAirship-iOS-SDK'

Multiple commands produce '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist':
1) Target 'UrbanAirship-iOS-SDK-AirshipResources' (project 'Pods') has copy command from '/Users/manikandan/MyAPP/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/Info.plist' to '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist'
2) Target 'UrbanAirship-iOS-SDK-AirshipResources' (project 'Pods') has process command with output '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist'

If I change the workSpaceSettings to LegacyBuildsystem, It is working and running. But why is that needed? 
<img width="536" alt="Screenshot 2019-09-20 at 6 34 06 PM" src="https://user-images.githubusercontent.com/41666550/65329073-5b6e8f00-dbd5-11e9-861c-5b85e2415ed2.png">
