### ISSUE TITLE
Generate AirshipLib.h build phase breaks incremental builds

### ISSUE THREAD

**Issue by josephlord** [urbanairship/ios-library#163]
With this build step happening incremental builds of my application are prevented (Framework is manually installed as a dependency). Can the header be provided in an alternative way, included in the repo? Or potentially a new file generated and compared with the existing one only to replace it if it has changed.

**Comment by marc-scig** [comment]
Hi there,

Thanks for the feedback. That sounds doable. We're in the middle of a large SDK update that should be coming the next few weeks – I'll see if I can get this added to our todo list in the meanwhile.

**Comment by gdavis** [comment]
We're also having this issue which makes working in a large project very, very slow. @josephlord @marc-scig Do you have any suggestions for a workaround in the meantime?

**Comment by josephlord** [comment]
Yes, have worked around by running the build so it generates the file and then disabling that build step. We have the UA project within our repo so it is fairly easy to have the generated file committed. @gdavis

**Comment by gdavis** [comment]
@marc-scig Swift with the latest Xcode

**Comment by marc-scig** [comment]
Also are you folks using the new (preview) Xcode 9 build system?

**Comment by gdavis** [comment]
@marc-scig No, we're using the default build system.

**Comment by josephlord** [comment]
Mostly Swift with Urban Airship header included in the bridging header file (so I think being included project wide). I’m pretty sure it is generally the default build system.

**Comment by gdavis** [comment]
We were able to add a check to the generation script to check if the .h file already exists, and abort if its already there. We don't track this file in git, so a fresh checkout for developers will generate this file once and quit. This is working for us to get incremental builds back in place without changing the UA build process too much.

**Comment by marc-scig** [comment]
Thanks for your patience. @josephlord or @gdavis would either of you be willing to try this updated script out? Just drop it in place of the existing generate_header_imports.sh:

https://gist.github.com/marc-scig/4977fdbceb2dcf9bf99b3726a6b47f94

If it works for you I'll make sure it goes into the upcoming release, which should be a soon as next week.

**Comment by josephlord** [comment]
Works for me in my initial test. Will add this to our build and will feed back if we hit any issues.

**Comment by marc-scig** [comment]
Thanks!

**Comment by rlepinski** [comment]
Should be fixed in 9.0.0

**Comment by thebugcode** [comment]
Due to usage of the '/tmp/AirshipKit/' the build script often hangs , fails (On both build machines and local macs) due to missing permissions. Would it be possible to change this, so that it only works in the local directory?

**Comment by ralepinski** [comment]
Probably, could you open up a new issue? I will have my team look into it.

**Comment by Michael-Vorontsov** [comment]
Have the same issue. Thanks @thebugcode  found out that 'tmp/AirshipKit/'was created by current user with default permissions, so Jenkins user was unable to write to it. Solved it by changing permission to 777, so any user able to use it.

**Comment by thebugcode** [comment]
Let's press this issue in the related issue and hopefully we find a fix together
