### ISSUE TITLE
Error building project

### ISSUE THREAD

**Issue by netgfx** [urbanairship/ios-library#168]
Hello,

I have a project using UrbanAirship, I update frameworks through Carthage, running this command: `carthage update --platform iOS --no-use-binaries` but when I try to build my main project I get two errors:

```
UAActionSchedule.h' file not found
// and
Could not build Objective-C module 'AirshipKit'
```
project targets 9.3 iOS devices

any ideas?

Thanks!

**Comment by BrianBatchelder** [comment]
Could you please try a clean build and/or cleaning your build folder? If that doesn't work, please delete `Cartfile.resolved` and the `Carthage` directory, and then run `carthage update`.

**Comment by netgfx** [comment]
Yup that fixed it, thanks!
