### ISSUE TITLE
Error : Failed to associate named user with status: 403

### ISSUE THREAD

**Issue by manishpathak99** [urbanairship/ios-library#173]
I am working on Urban Airship integration in my iOS mobile application. Push Notification is working fine , but when I try to call

```
UAirship.namedUser().identifier = name
UAirship.push().updateRegistration()
```
We are getting Error` Failed to associate named user with status: 403` Please suggest me the possible solution .

**Comment by rlepinski** [comment]
Please contact support for usage issues.

https://docs.urbanairship.com/guides/engage-settings/#ug-settings-named-users
