### ISSUE TITLE
how to disable UAirship.defaultMessageCenter()

### ISSUE THREAD

**Issue by prjgithub** [urbanairship/ios-library#179]
As per documentation: https://docs.urbanairship.com/tutorials/ea-ios-message-center-customization/
By default, when the app receives a push notification carrying a Message Center Action, the Message Center will be automatically displayed in a modal view controller.

We'd like to suppress showing defaultMessageCenter, how do we accomplish that?

**Comment by rlepinski** [comment]
If you assign an inbox delegate you have full control of what message center is displayed. https://docs.urbanairship.com/tutorials/ea-ios-message-center-customization/#uainboxdelegate

If you need more help, please contact support.
