### ISSUE TITLE
Difference betwwen DeepLink vs Extra field

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/ios-library#184]
Hi there!

I need to push a news to all Apps and also navigate to that particular news (ID). I've implemented this using the notification field like this:

var bizmsg = new
                {
                    extra = new
                    {
                        newsid = **NewsID**
                    }
                    
                };

{
                    audience = "all",
                    device_types = new[] { "ios", "android" },
                    notification = new
                    {
                        alert = **"NewsHeadLineTitleHere"**,
                        ios = **bizmsg**,
                        android = **bizmsg**
                    }
                };

In this way I have achieved to push a Title and to navigate to that particular News (ID).

So, my question is whats the difference or the plus using Deep Linking in this case? I mean the basic fee is U$D 50 and the one supporting Deep Linking is $99.

Thanks in advance.

**Comment by rlepinski** [comment]
There is really no difference, just minor convenience. Our deep links work through extras as well. If its working for you I would not change it, especially if it costs extra.

**Comment by gonzalovinas** [comment]
Its a very nice rule to follow :)
But,
should I ask to the Android forum if there is different ? I mean... Whats' the catch for additional U$D50 or where/who to ask?

Thanks!
