### ISSUE TITLE
Xcode 10 build issue

### ISSUE THREAD

**Issue by osip34** [urbanairship/ios-library#185]
![screen shot 2018-07-20 at 4 31 17 pm 2](https://user-images.githubusercontent.com/24256114/43005246-f3a8e644-8c3a-11e8-990c-bb664b609663.png)

# Report
The issue is caused by multiple info.plist files that are getting written into the same path. It causes conflict, that is unacceptable by new Xcode build system. You can simply remove plist files from your resourses, this will eliminate the "copy" command, and there would be only one command left.

### What unexpected behavior are you seeing?
ℹ The error during the build, using new Xcode build system.

### Expected behavior:
ℹ New Xcode build system can build UrbanAirship-IOS-SDK

###  Steps to reproduce the unexpected behavior:
ℹ Build the project, that has UrbanAirship-IOS-SDK pod, using new build system.

**Comment by rlepinski** [comment]
What cocoapods, Xcode beta, and UA SDK pod version are you using? I thought we fixed it in a newer pod version.

**Comment by rlepinski** [comment]
@osip34 It was fixed in 9.0 but we most of overlooked that detail as its not in the changelog. Glad its working for you!
