### ISSUE TITLE
Failed to verify bitcode in AirshipKit.framework/AirshipKit

### ISSUE THREAD

**Issue by salimbutex** [urbanairship/ios-library#187]
# Preliminary Info
Everything working perfect while running on simulator and real device. I am receiving push too..
But when I am trying to Archive for ipa....  It says... 

Failed to verify bitcode in AirshipKit.framework/AirshipKit

I followed everything, explained here... 
https://docs.urbanairship.com/platform/ios/?swift#sdk-installation

Thanks In advance

**Comment by BrianBatchelder** [comment]
@salimbutex : we don't have enough information to analyze your issue. Could you please fill out the standard issue template, including the version of our SDK, the version of Xcode, and anything else that might help us understand what you are seeing. Thanks.

**Comment by BrianBatchelder** [comment]
@salimbutex : I'm going to close this issue. If you continue to have problems with your app, please open a new issue. Thanks.
