### ISSUE TITLE
Warning received from Apple due to use of CoreLocation APIs

### ISSUE THREAD

**Issue by eugie** [urbanairship/ios-library#188]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact [support](https://support.urbanairship.com/hc/en-us).

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.

`pod 'UrbanAirship-iOS-SDK', '~> 8.6.2'`

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

Xcode 9.3.1

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.

After our most recently upload to App Store Connect, we received the following email from Apple:

> App Store Connect: Your app "\<App Name\>" has one or more issues
>
> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "\<App Name\>". Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> "Missing Purpose String in Info.plist File. Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy)."
>
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
> 
> Best regards,
> 
> The App Store Team

This was odd, since our app doesn't request permission to use the user's location. We searched the codebase and discovered that the UA pod is the only place that uses `CLLocationManager`, in [UALocation.m](https://github.com/urbanairship/ios-library/blob/master/AirshipKit/AirshipKit/common/UALocation.m). Even though we don't use enable that functionality, App Store Connect still detects that the code is present during processing, which is what caused this warning to be sent. It also looks like they'll stop accepting our app altogether in 2019 unless we set this usage description.

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.

Our app doesn't use the user's location, so we shouldn't have to set an `NSLocationAlwaysUsageDescription` and we shouldn't receive a warning when uploading to App Store Connect. It would be nice if we had the ability to not include this functionality at all (e.g. by making it part of a sub-pod), since I'm not a huge fan of having this code in our binary if we aren't using it.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.

1. Add the UA pod to your app.
2. Upload app to App Store Connect.

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.

**Comment by thebugcode** [comment]
Same issue we have, as soon as 2019 we will be blocked from releasing due to Urban Airship's usage or CoreLocation. 

Additionally, Urban Airship is accessing the user's location without asking  - violating terms of service, user privacy, GDPR and our user's personal data. 

I highly suggest that this be fixed as soon as possible.

**Comment by rlepinski** [comment]
@thebugcode That is completely incorrect and a total misunderstanding of the issue here. We are NOT tracking the user location without asking, we are NOT violating user privacy and GDPR. We simply provide a small wrapper around the corelocation apis to make it easy to track user's location. The feature is disable by default, and if you enable it, it will prompt the user to allow location to be enabled. 

Not only that, you will not be locked out of your app, but you might have to provide a single location usage description in your plist.

@eugie Thanks for the report. We will take a look at our options.

**Comment by marc-scig** [comment]
@eugie Thanks. We're considering potential options for repackaging the SDK with location services as a separate module, but don't have a timeline on that yet. As a short term solution, adding the requested usage descriptions should be a suitable workaround.

This appears to be new behavior from Apple (as in the last 24 hours or so), and may be erroneous on their end, but it's too early to tell. Regarding this section:

```
Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. 
```
My interpretation of this is that they have merely noted that the SDK imports <CoreLocation/CoreLocation.h>, and that there are possible code paths that access location data, whether or not your app is actually using them. If you're not using any of our location APIs adding the usage string should have no effect on the UX of your app, as the usage string is only displayed as part of the prompt when location is requested.

I fully agree in principle that you shouldn't have to worry about this, and it looks like the longer term solution is to modularize this stuff to make it easier to completely strip out this feature if it's not needed. However the SDK isn't amenable to that approach in its current form, so we're going to have to give some thought as to how to do this the right way.

**Comment by marc-scig** [comment]
To reiterate in the strongest possible terms, and for anyone else following this thread: we do not collect sensitive data without the user's consent, and the only location features in our SDK are simple wrappers around the CoreLocation APIs which require conscious developer intervention, and which are disabled by default. Our code is open source and all of this can be easily verified.

**Comment by BrianBatchelder** [comment]
It appears Apple has fixed their application analysis, and is no longer issuing warnings for apps that include, but do not use, CoreLocation without defining the corresponding usage descriptions. We are closing this issue. Please reach out if you receive a similar warning from Apple in the future.

**Comment by zkyronex** [comment]
Hi all, this issue has come up again as I am guessing Apple has implemented their 
> Starting spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.
Just the fact that the requestAlwaysAuthorization() code exists regardless of whether that function is called causes the rejection. Please advise.

**Comment by crow** [comment]
@zkyronex The current workaround is to provide the `Always` and `When In Use` strings regardless of your Urban Airship location API usage. This is something we are currently working on a clean, long term solution for - and we appreciate your understanding.
