### ISSUE TITLE
Unexpected behavior for didRegisterForRemoteNotificationsWithDeviceToken

### ISSUE THREAD

**Issue by richardliveraise** [urbanairship/ios-library#191]
# Preliminary Info

### What Urban Airship dependencies are you using?
10.0.0

### What are the versions of any relevant development tools you are using?
Xcode 10.0, iOS 12

# Report

### What unexpected behavior are you seeing?
didRegisterForRemoteNotificationsWithDeviceToken gets called after app uninstall and reinstall.  Immediately called upon app launch, showing cached deviceToken. 

When user is prompted for push notification permission and accepted, didRegisterForRemoteNotificationsWithDeviceToken is not called.

### What is the expected behavior?
didRegisterForRemoteNotificationsWithDeviceToken shouldn't be called after uninstall and reinstall.
It should get called when user granted the permission for push notification. 
 
### What are the steps to reproduce the unexpected behavior?
1. Install app
2. Request push notification permission
3. Accept push notification permission
4. Uninstall app
5. Reinstall app
6. didRegisterForRemoteNotificationsWithDeviceToken gets called with cached token.

**Comment by BrianBatchelder** [comment]
@richardliveraise: Registering for remote notifications is a [two-step process](https://developer.apple.com/documentation/uikit/uiapplication/1623078-registerforremotenotifications?language=objc):

1. Call `UIApplication's` `registerForRemoteNotifications` to initiate the registration process.
2. Call `UNUserNotificationCenter's` `requestAuthorizationWithOptions:completionHandler:` to request authorization from the user.

Our SDK calls the first method when we are initialized, to start the process. ASAP. You can see this in: https://github.com/urbanairship/ios-library/blob/492bda932a1df8fb21efd4c039a80c8374329574/AirshipKit/AirshipKit/common/UAPush.m#L150-L152
This call is what is triggering the `didRegisterForRemoteNotificationsWithDeviceToken` callback.

Our SDK calls the second method when `UAirship.push().userPushNotificationsEnabled` is set to `true`.
This will immediately request authorization from the user, so your app should be careful when to set it, as noted in our documentation [here](https://docs.urbanairship.com/platform/ios/#enabling-user-notifications):
>Enabling `userPushNotificationsEnabled` will prompt the user for permission to send notifications. To increase the likelihood that the user will accept, you should avoid prompting the user for permission immediately, and instead wait for a more appropriate time in the app.

FYI - you can be notified when the user answers the authorization prompt by using our [`UARegistrationDelegate`](https://docs.urbanairship.com/reference/libraries/ios/latest/Protocols/UARegistrationDelegate.html#/c:objc(pl)UARegistrationDelegate(im)notificationRegistrationFinishedWithAuthorizedSettings:categories:status:).
