### ISSUE TITLE
Manually provide token to the SDK

### ISSUE THREAD

**Issue by shivamkapur** [urbanairship/ios-library#193]
# Preliminary Info

### What Urban Airship dependencies are you using?
UrbanAirship iOS SDK v9.4.0

### What are the versions of any relevant development tools you are using?
Xcode 10, iOS 12, CocoaPods 

# Report

### What unexpected behavior are you seeing?
I'm unable to manually register for push notifications. 
Ideally when I disable "isAutomaticSetupEnabled" I should be able to provide the token to UrbanAirShip somehow. Which in turn enables push notifications.

The registration delegate returns the device token as empty, and there is no other way to provide a device token to UrbanAirship.
### What is the expected behavior?
I need to be able to add tokens to UrbanAirship manually
### What are the steps to reproduce the unexpected behavior?
        let config = UAConfig()
        config.isChannelCaptureEnabled = true
        config.isAnalyticsEnabled = true
        config.developmentLogLevel = UALogLevel.info
        config.productionLogLevel = UALogLevel.none
        config.isAutomaticSetupEnabled = false
        config.isChannelCreationDelayEnabled = true
         UAirship.takeOff(config)
        
        UAirship.push()?.pushTokenRegistrationEnabled = true
        UAirship.push().pushNotificationDelegate = self
        UAirship.push().registrationDelegate = self
        UAirship.inbox().delegate = self
### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
Could you answer the following:
- Why do you need to manually register for push?
- Why is your delegate returning an empty token?
- What is your use case?

Thanks!

**Comment by shivamkapur** [comment]
Hey, you may find the answers below: 

Why do you need to manually register for push?
 

> Well part of the reason is that I would like to reuse the token to one of the other private BE services that'll send push notifications.

Why is your delegate returning an empty token?

> Not my delegate, it is the UARegistrationDelegate that is returning me an empty token, I do get a channel ID, though.

What is your use case?

> I want to be able to send push notifications from UrbanAirship and via a backend service, hence the need of the device token.
