### ISSUE TITLE
Rate Action Crash

### ISSUE THREAD

**Issue by blazierkyle** [urbanairship/ios-library#195]
# Preliminary Info

### What Urban Airship dependencies are you using?
Latest release - UrbanAirship-iOS-SDK version 10.0.1 (also seeing this on 9.4)

### What are the versions of any relevant development tools you are using?
Xcode 10, app deploying on iPhone & iPad, iOS 10.3+

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
We're seeing a fairly large number of crashes from the AirshipKit-SDK when using the app review prompt. This crash is happening on iOS 10.3.1, 10.3.3, 11.3, 11.3.1, 11.4, 11.4.1, 12.0, and 12.0.1. The crash is caused by removing objects in an array while iterating over it. The crash log (attached) shows the crash coming from the following line `UARateAppAction.m line 169 in -[UARateAppAction storeTimestamp:] (UARateAppAction.m:169)`. Reviewing this code it is clear that while iterating over an array, that array should not be mutated.

### What is the expected behavior?
The SDK properly handles removing old timestamps and does not crash.

### What are the steps to reproduce the unexpected behavior?
I believe having stored app review prompt timestamps that are older than 1 year when getting a new app review prompt will cause this crash.

### Do you have logging for the issue?
No logs but relevant part of crash log attached below.
<img width="1120" alt="ua_crash" src="https://user-images.githubusercontent.com/9664844/47100393-5ce54980-d205-11e8-8318-3bc88d85a1e9.png">

**Comment by marc-scig** [comment]
Hey @blazierkyle,

Thanks for bringing this to our attention. A patch release should be going out with a fix no later than tomorrow.

**Comment by marc-scig** [comment]
10.0.2 is out with a fix for this issue.

**Comment by blazierkyle** [comment]
Thanks for the quick turnaround @marc-scig !
