### ISSUE TITLE
CoreData error : Can't merge models with two different entities named 'uascheduletriggerdata'

### ISSUE THREAD

**Issue by dnunespossible** [urbanairship/ios-library#198]
# Preliminary Info

### What Urban Airship dependencies are you using?
Airshipkit,AirshipAppExtensions

### What are the versions of any relevant development tools you are using?
Xcode 10.1

# Report

### What unexpected behavior are you seeing?
When updating from version 8.0.4 to 10.0.3, App crashed with error:
Can't merge models with two different entities named 'uascheduletriggerdata'

### What are the steps to reproduce the unexpected behavior?
Run the project and run
NSManagedObjectModel *model = [NSManagedObjectModel mergedModelFromBundles:[NSBundle allBundles]];

### Possible fix, I deleted the old CoreData Model version 2 and 1 and my projets is running normally.

**Comment by rlepinski** [comment]
Thanks for the report. We will take a look

**Comment by BrianBatchelder** [comment]
@dnunespossible : the `mergedModelFromBundles` method will fail if any of the models in your bundle are versioned, as some of the UA models are. Instead, you need to merge just the models you want to migrate and leave the UA models out. 

Here are some resources that might help:
- https://augustl.com/blog/2011/unit_testing_ios_core_data_versioned_or_multiple_models/
- https://stackoverflow.com/a/2282152/1587892
