### ISSUE TITLE
Build Active Architecture Only Release

### ISSUE THREAD

**Issue by Awalz** [urbanairship/ios-library#199]
# Preliminary Info

### What Urban Airship dependencies are you using?
* `iOS-library 10.0.3`

# Report

### What unexpected behavior are you seeing?
* Being unable to deploy release builds due to **Build Active Architecture Only** set to **Yes**. 

### What is the expected behavior?
* Almost all dependancies/frameworks set this to **No** for Release targets. This is because you want release to contain all supported architectures, not just the currently active ones. **Yes** is fine for debug since it is being run on device, but this prevents us from submitting builds without having to manually disable every time dependancies get updates

**Comment by rlepinski** [comment]
@Awalz Thanks for the report. We will look into this today.

**Comment by Awalz** [comment]
We are using Carthage

**Comment by rlepinski** [comment]
Thanks!

**Comment by rlepinski** [comment]
I see the setting set to NO on AirshipAppExtensions, AirshipResources, and AirshipLib. What one are you having issues with? Just AirshipAppExtensions?

**Comment by rlepinski** [comment]
This should be fixed in 10.0.4/10.1.0. Let me know if you still have issues.
