### ISSUE TITLE
Uploading to App Store Fails Due to Unsupported Architectures Error

### ISSUE THREAD

**Issue by sungjin0213** [urbanairship/ios-library#200]
# Preliminary Info

### What Urban Airship dependencies are you using?
iOS-library 10.0.3 AirshipKit & AirshipExtensions

### What are the versions of any relevant development tools you are using?
Xcode 10.1, Carthage 0.29, Fastlane deliver 2.111.0

# Report

### What unexpected behavior are you seeing?
- Uploading an iOS app with Urban Airship 10.0.3 with following error messages and fail to upload to App Store.

```
[Transporter Error Output]: ERROR ITMS-90087: "Unsupported Architectures. The executable for APPNAME.app/Frameworks/AirshipKit.framework contains unsupported architectures '[x86_64, i386]'."
[Transporter Error Output]: ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'APPNAME.app/Frameworks/AirshipKit.framework/AirshipKit' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
[Transporter Error Output]: ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
```

### What is the expected behavior?
- Uploading an iOS app will be successful.

### What are the steps to reproduce the unexpected behavior?
- Add 10.0.3 AirshipKit.framework to a project using Carthage.
- Create an App Store build
- Upload to App Store

**Comment by BrianBatchelder** [comment]
@sungjin0213 : Make sure you follow the instructions at: https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos . In particular, it sounds like you may not have added the copy-frameworks script step.

**Comment by sungjin0213** [comment]
@BrianBatchelder thanks for the response. 

Yes, it has been successful to submit in App Store in the past. However, we were using static binary file (with extension .a) instead of Carthage framework. 

We do not use build phase to build Carthage, but rather use Cartfile with `github "urbanairship/ios-library"` and run `carthage update` to generate framework. As far as I know both approaches does not differ, but let me know if it's not, so I could try that method also.

So to give a little more background, let me explain what I have done so far. According to the error log, I think I see a potential solution: removing unsupported architecture i386 and x86_64 from the project, and rebuild it. However, when I make that change locally and rebuild it pointing to the absolute path to my local project using "file//", it continually checks out the project before I made that change. I tried clearing cache for Carthage, and it did not help.

So I'm stuck here and will appreciate any feedback. I will try to follow the Carthage integration steps carefully one more time in the meantime.

**Comment by sungjin0213** [comment]
@BrianBatchelder thanks for the lead. You were right. I can't really understand why, but including the Carthage output in where .xcodeproj was and adding that copy-framework step was vital. 

I was able to get success on the App Store build after these. I'm guessing copy-framework step also strips down unnecessary architectures. Thanks for leading me into right direction.
