### ISSUE TITLE
App crash at launch on iOS9 with SDK 10.x due to missing UserNotifications.framework

### ISSUE THREAD

**Issue by fredhdroz** [urbanairship/ios-library#201]
# Preliminary Info

### What Urban Airship dependencies are you using?
- Sample project - 10.0.4

### What are the versions of any relevant development tools you are using?
- Xcode 10.1, iOS 9.0, Objective-C

# Report

### What unexpected behavior are you seeing?
The app crashes at launch when running on iOS9 devices

### What is the expected behavior?
2 possibilities:
- As the readme indicates the projects must target >= iOS8, the app should not crash at launch on iOS 9.  
- If iOS 8-9 are no longer supported, the readme should indicate that projects must target >= iOS 10.

### What are the steps to reproduce the unexpected behavior?
- Download the sample project
- Select the "Sample" target and set the deployment target to "9.0"
- Run the sample

### Do you have logging for the issue?

'''
dyld: Library not loaded: /System/Library/Frameworks/UserNotifications.framework/UserNotifications
  Referenced from: /.../Build/Products/Debug-iphonesimulator/AirshipKit.framework/AirshipKit
  Reason: image not found
'''

### Additional information 
I've got another app running fine on iOS9-12 with SDK v9.4.0, but if I update the SDK to v10.0.4 then the exact same issue happens at launch.

Does the SDK v10.x still supports iOS 9 ?

**Comment by BrianBatchelder** [comment]
@fredhdroz : Thanks for the catch. Indeed, we support iOS 10 and newer. I have updated the README.
