### ISSUE TITLE
Tags are not updated when changed

### ISSUE THREAD

**Issue by songhailiang** [urbanairship/ios-library#206]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ 10.2.0, manually imported with static library downloaded from https://bintray.com/urbanairship/iOS/urbanairship-sdk/10.2.0

### What are the versions of any relevant development tools you are using?
ℹ Xcode 10.1 with Swift 4.2

# Report

### What unexpected behavior are you seeing?
In my app, when user logged in, a tag will be added to the device, this works correctly.
When user logged out, the previous tag will be removed, and another tag will be added, but this does not work. 
I did call ```updateRegistration``` after set new tags. 
From Charles, i can't find the channels api request made, and the Last Registration is not updated from Device Lookup in Airship Console.
https://device-api.urbanairship.com/api/channels/xxxxx (this was made when user logged in)

Note: This works correctly when i switch Library to 10.1.0.

### What is the expected behavior?
The new tags should be updated when they changed.

### What are the steps to reproduce the unexpected behavior?
1. Open the App, Airship takeoff, channels registration works correctly.
2. Logged in an account, tags changed, channels registration updated correctly.
3. Logged out, channels registration is not updated.

### Do you have logging for the issue?
From Xcode console, i saw some logs like:
'Ignoring registration request, one already in progress.'

Do you have any suggestion? 
Thank you very much!

**Comment by rlepinski** [comment]
Could you provide code snippets around where you are adding tags when the user logs in and when the user logs out?

**Comment by songhailiang** [comment]
Sorry, it's hard to do this. We developed another framework to implement tags adding or updating using Airship. There are serval tags need to be added or updated when user logged in or logged out. We will call ```updateRegistration ``` after each tag adding or updating. I'm not sure whether this will cause the issue, but this works correctly in 10.1.0 and previous version of Airship frameworks.

**Comment by rlepinski** [comment]
@songhailiang Please contact support. They will help gather the information we need.

**Comment by rlepinski** [comment]
@songhailiang We found an issue in the channel registration with 10.2.0 & 10.2.1. Ill let you know when the patch release is available.

**Comment by rlepinski** [comment]
Should be fixed with 10.2.2
