### ISSUE TITLE
Add prebuilt carthage framework to every release

### ISSUE THREAD

**Issue by gotev** [urbanairship/ios-library#207]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.

* 10.2.2

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

* Xcode 10.2.1
* carthage 0.33.0

# Report

## Description
Add a prebuilt carthage framework to every UrbanAirship release to speed up build times when using it in apps.

## Motivation and Context
I'm using carthage as dependency manager for my projects and I use UrbanAirship SDK. Carthage builds all the dependencies from source every time, unless they have a prebuilt framework attached to the github release. By attaching it, the client simply downloads the framework and build times are much faster.

## Proposed Solution
```
## do this only the first time on your mac or CI
## https://github.com/github/hub
brew install hub

## to create a release, from the project's root
carthage build --archive
hub release create -a UrbanAirship.framework.zip -m "tag comment" "tag version"
```
And you will get a release like this (taken from RxSwift)
![Schermata 2019-05-10 alle 11 44 06](https://user-images.githubusercontent.com/16792495/57518274-f480c580-7318-11e9-950e-3e5d831beed9.png)

**Comment by crow** [comment]
This is probably something we can do. Thank you for the suggestion.

**Comment by crow** [comment]
A pre-built carthage framework will now attached alongside our standard releases. 

Airship 11.1.0 release is now available as a prebuilt carthage framework [here](https://github.com/urbanairship/ios-library/releases/download/11.1.0/Airship.framework.zip
)

Thanks for bringing this to our attention.
