### ISSUE TITLE
[UAirship location].locationUpdatesEnabled simple gone in new release!

### ISSUE THREAD

**Issue by tomcalmon** [urbanairship/ios-library#208]
Guys, your preliminary infos are not so clear, so I will ignore it!
Maybe You could create a more detailed questions for help us.

I've just updated my pods and I saw that UrbanAirship released v11.0.0.

Now I can't build my app because of **No known class method for selector 'location'**!
`[UAirship location].locationUpdatesEnabled = YES;`

It seems that your documentation is outdated:
[Airship Docs - Location](https://docs.airship.com/platform/ios/location/)

Thank you.

**Comment by rlepinski** [comment]
Working on updating the docs. For now take a look at https://github.com/urbanairship/ios-library/blob/master/Documentation/Migration/migration-guide-10-11.md

You will need to include a new pod `UrbanAirship-iOS-Location` in order to access the AirshipLocationKit.

**Comment by rlepinski** [comment]
Docs have been updated. Thanks!
