### ISSUE TITLE
Hide the status bar after close the video player for message center details

### ISSUE THREAD

**Issue by asaduzzaman-shuvro** [urbanairship/ios-library#209]
# Code 

    class MessageDetailsVC: UAMessageCenterMessageViewController {
    
    private var messageToDisplay: UAInboxMessage

    init(with message: UAInboxMessage) {
        self.messageToDisplay = message
        super.init(nibName: "UAMessageCenterMessageViewController", bundle: UAirship.resources())
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.rightBarButtonItem?.action = #selector(deleteButtonPressed)
        self.setCustomBackButton()
        self.loadMessage(forID: messageToDisplay.messageID, onlyIfChanged: true) {
            //
        }
    }
    
    @objc func deleteButtonPressed()  {
        if !self.message.deleted {
            UAirship.inbox()?.messageList.markMessagesDeleted([self.message], completionHandler: { [weak self] in
                self?.navigationController?.popViewController(animated: true)
            })
        }
    } }

# Preliminary Info

### What Airship dependencies are you using?
ℹ 10.2.2

### What are the versions of any relevant development tools you are using?
ℹ xcode 10.1

# Report

### What unexpected behavior are you seeing?
ℹ If you create a video message and try show with message center details view the problem  arises. The status bar is hidden when i press the cross button of player. i need the restart the app to show status bar again. 

### What is the expected behavior?
ℹ The status bar should not be hidden forever. u

### What are the steps to reproduce the unexpected behavior?
ℹ Make a video message with message center and try to play. it will hide the status bar forever.

**Comment by crow** [comment]
@asaduzzaman-shuvro Thanks for reporting. I'll see if I can reproduce this behavior.

**Comment by crow** [comment]
I'm not able to reproduce this behavior in the sample application. Are you able to force the status bar to reappear by adding the following override to your MessageCenterViewController?

```
override var prefersStatusBarHidden: Bool {
    return true
}
```
