### ISSUE TITLE
'Location Enabled' on Airship console set to 'disabled'

### ISSUE THREAD

**Issue by sammiller-hhl** [urbanairship/ios-library#210]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Airship dependencies are you using?
UrbanAirship-iOS-SDK 11.0.0
UrbanAirship-iOS-Location 11.0.0

### What are the versions of any relevant development tools you are using?
Xcode 10.2.1 and cocoapods 1.5.3

# Report

### What unexpected behavior are you seeing?
I have integrated the SDKs for Airship and Airship Location so that our app can report user location updates to Airship. I have followed the short programming guide found here https://docs.airship.com/platform/ios/location/#enabling-location.

After accepting the permissions for both in use and when app is in background, I can see location updates coming through on the device but according to the Device Properties on the Airship console for my device, the 'Location Enabled' property is set to 'Location Disabled'.

I am new to these APIs so my first question would be, should I expect the console to say 'Location Enabled' once I've accepted the permissions?

### What is the expected behaviour?
After accepting the permissions in app, the console should display 'Location Enabled' for the specified device.

### What are the steps to reproduce the unexpected behavior?
1. Request permissions from the user via `UALocation.shared()?.isLocationUpdatesEnabled = true`
2. Accept the permissions in app.
3. Log in to the Urban Airship console and observe the device properties for the specified device.

### Do you have logging for the issue?
n/a

**Comment by crow** [comment]
@sammiller-hhl Did you recently opt-in to location? If so, there might be a delay between when you set your location opt-in status and when it is updated on the device lookup console. You are correct in assuming it should eventually say "Location Enabled" once you have set isLocationUpdatesEnabled and authorized for location through the system authorization prompt.

**Comment by crow** [comment]
I'm able to see some delay in testing. Will keep my eye on it.

**Comment by sammiller-hhl** [comment]
Hi @crow , thanks for getting back to me. So I've checked the console this morning and it is now reading 'enabled'. Can you confirm whether or not any action was taken from your side or do you think it was simply a delay? If we think it's a delay I'll close the issue and do some further testing to keep an eye on things.

cheers.

**Comment by rlepinski** [comment]
@sammiller-hhl There is a delay on device property tags. Not sure what the current numbers are but if you need more info please contact support.
