### ISSUE TITLE
Second run of a takeOff leads to an unknown state

### ISSUE THREAD

**Issue by edgarclerigo** [urbanairship/ios-library#211]
# Preliminary Info
Running: UrbanAirship-iOS-SDK  10.0.0

When running the app on the first run, after the TakeOff the `UARegistrationDelegate` are called with success. On the second run the takeOff any of the methods `registrationSucceeded` or `registrationFailed` from the `UARegistrationDelegate` are called ... I need to know if the takeoff was completed with success or not.

Debugging I've found that on the class `UAChannelRegistrar.m` , on the method 
`- (void)registerForcefully:(BOOL)forcefully`

The method `shouldUpdateRegistration` returns false, and the `return` on the parent method is called. Which leads to this...

### What Airship dependencies are you using?
None
# Report

### What unexpected behavior are you seeing?
The method `registrationSucceeded` or `registrationFailed` from the `UARegistrationDelegate` on the second run of the application aren't called, which leads me to a point, where I'm not able to know if the `takeoff` was a success or not

### What is the expected behavior?
Since the previous registration is still valid, I assume that any of those methods should be called ... or at least there should be a way to know this ....

### What are the steps to reproduce the unexpected behavior?
Perform a `takeOff` on a app. Kill the app, run the app and perform a new `takeoff`

**Comment by rlepinski** [comment]
Channel registration only happens if something actually changes. It has no indication about takeOff. If takeOff is called with the proper credentials then it will always be successful.
