### ISSUE TITLE
Archive was blocked with 8.6.3

### ISSUE THREAD

**Issue by SendorWang** [urbanairship/ios-library#212]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What are the versions of any relevant development tools you are using?
XCode10.1, swift4.2

# Report

### What unexpected behavior are you seeing?
Archiving was blocked at: UrbanAirShip-iOS-SDK | Setting mode of 1 of 1 files

### What is the expected behavior?
Archive successfully

### What are the steps to reproduce the unexpected behavior?
I use  UrbanAirship in my project. This is my podfile:
```
  #UrbanAirship,  https://go.urbanairship.com
  pod 'UrbanAirship-iOS-SDK'
  target 'NotificationService' do
      pod 'UrbanAirship-iOS-AppExtensions'
  end
```
 Today,  I run ‘pod install’， I got:
`Using UrbanAirship-iOS-AppExtensions (8.0.5)  
Using UrbanAirship-iOS-SDK (8.6.3)
`
Then I run 'Product'->'Archive' and was blocked at: 'UrbanAirShip-iOS-SDK | Setting mode of 1 of 1 files'

**Comment by SendorWang** [comment]
I am afraid this problem comes from macOS 10.14

**Comment by crow** [comment]
Thanks for reporting. Are there specific reasons why you are using xcode 10.1 with the UrbanAirship-iOS-SDK 8.6.3? and UrbanAirship-iOS-AppExtensions 8.0.5? These modules are both ~2 years old. It might be worth attempting to upgrade to later version(s). I'd be happy to try and reproduce your issue, but would first like to get more of an idea of your project's specific requirements that are preventing the mentioned upgrades.
