### ISSUE TITLE
How to sync badge count with server after app reset badge?

### ISSUE THREAD

**Issue by chengsam** [urbanairship/ios-library#213]
# Preliminary Info

### What Airship dependencies are you using?
UrbanAirship-iOS-SDK 11.1.0

### What are the versions of any relevant development tools you are using?
Xcode 10.2.1

# Report

### What unexpected behavior are you seeing?
When the user starts the app, the badge count reset to 0. But when a new notification is received, the badge count incremented by 1 from the previous badge count. E.g. the badge count is 3, the user opens the app and the badge is cleared, new notification is received and the badge count is 4.

I have added the following code in `didFinishLaunchingWithOptions`:
`[[UAirship push] setAutobadgeEnabled:YES];
  [[UAirship push] resetBadge];`

and the following in `applicationDidBecomeActive`:
`[[UAirship push] resetBadge];`

### What is the expected behavior?
The server should keep in sync with the app, the new badge count should be 1 after reset.

### What are the steps to reproduce the unexpected behavior?
1. Send 3 notifications to the app
2. The badge displayed is 3
3. Open the app and the badge is reset
4. Send a notification again and the badge is 4

### Do you have logging for the issue?

**Comment by crow** [comment]
@chengsam Please contact [support]( https://support.airship.com/) with how-to guidance.
 
Specifying how are you sending the pushes (through an API request, through the airship dashboard, etc) would be helpful to support in identifying your issue. The payload itself if you are sending an API request would also be helpful.
