### ISSUE TITLE
iOS 9 'hasStrings' crash

### ISSUE THREAD

**Issue by Cloov** [urbanairship/ios-library#215]
# Preliminary Info

We use the cordova plugin, *urbanairship-cordova 7.5.3*

# Report

### What unexpected behavior are you seeing?

We are experiencing a crash in our app, when the app becomes active, and only on iOS 9 (we've only tested specifically 9.3.5 as all our iOS 9 devices are on 9.3.5).

The Xcode console gives us the following information:

`-[UIPasteboard hasStrings]: unrecognized selector sent to instance 0x16d95830
2019-08-02 15:16:47.367 PasteboardTest[227:7142] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIPasteboard hasStrings]: unrecognized selector sent to instance 0x16d95830'` 

We think we understand the cause of the error. According to iOS documentation, `hasStrings` should only be used on iOS 10 and above: https://developer.apple.com/documentation/uikit/uipasteboard/1829416-hasstrings

We investigated dependencies and frameworks that we use, and found that `UAChannelCapture.m` makes a call to `hasStrings` that isn't guarded with an iOS version check. This is done in the `didBecomeActive` method, which matches exactly with where our crash occurs:

https://github.com/urbanairship/ios-library/blob/7dd19c054fffa12c4ca3d63f1211c02ca96d8a40/AirshipKit/AirshipKit/ios/UAChannelCapture.m

When writing similar code in a test project of our own, we get this warning:

`'hasStrings' is only available on iOS 10.0 or newer`
`Enclose 'hasStrings' in an @available check to silence this warning`

I'm not sure what the replacement should be when on iOS 9 and the `hasStrings` method can't be used, but I believe that using `UIPasteboard.strings` to go on and obtain the contents without the slightly-more-sensible initial check, would probably be sufficient - it's just reported to be marginally less efficient.

**Comment by rlepinski** [comment]
@Cloov Our SDK only supports iOS 10, 11, and 12. We only support the last 3 versions of iOS.

That is probably the first error that the SDK would hit. The entire SDK assumes 10, so even if we changed that it would fail somewhere else.

You either need to drop iOS 9 support or use an older version of the cordova plugin.
