### ISSUE TITLE
UrbanAirship-iOS-Location 11.1.1 missing from cocoapod repo

### ISSUE THREAD

**Issue by henrylau-sa** [urbanairship/ios-library#216]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Stuck in `"urbanairship-react-native": "3.1.2",` due to this issue.

### What are the versions of any relevant development tools you are using?

cocoapod on a mac

# Report

### What unexpected behavior are you seeing?

Result from `pod search UrbanAirship-iOS-Location` is ran after `pod repo update`
```
-> UrbanAirship-iOS-Location (11.1.0)
   Airship iOS Location
   pod 'UrbanAirship-iOS-Location', '~> 11.1.0'
   - Homepage: https://www.airship.com
   - Source:   https://github.com/urbanairship/ios-library.git
   - Versions: 11.1.0, 11.0.0 [master repo]
(END)
```
### What is the expected behavior?

Can install UrbanAirship-iOS-Location version 11.1.1 with cocoapods

### What are the steps to reproduce the unexpected behavior?

1. `pod repo update` 
2. `pod search UrbanAirship-iOS-Location`

**Comment by crow** [comment]
@henrylau-sa if you run `pod repo update` again it should work. Thanks for brining this to our attention.

**Comment by henrylau-sa** [comment]
Thank you very much
