### ISSUE TITLE
Carthage fails to fetch

### ISSUE THREAD

**Issue by Prince2k3** [urbanairship/ios-library#218]
# Preliminary Info

### What Airship dependencies are you using?
11.1.1

### What are the versions of any relevant development tools you are using?
Carthage  

# Report

### What unexpected behavior are you seeing?
Carthage failing to fetch ios-library

### What is the expected behavior?
Carthage fetching iOS-library and continuing to fetch other dependencies

### What are the steps to reproduce the unexpected behavior?
inside Cartfile 
github "urbanairship/ios-library" 

then
carthage update --platform ios

when it gets to ios-library its fails

### Do you have logging for the issue?
```
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/urbanairship/ios-library.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/prince.ugwuh/Library/Caches/org.carthage.CarthageKit/dependencies/ios-library)) failed with exit code 1
```

**Comment by Prince2k3** [comment]
```
*** Fetching apollo-ios
*** Fetching lottie-ios
*** Fetching uikit-additions
*** Fetching network-hijack
*** Fetching Quick
*** Downloading binary-only framework Fabric at "https://building42.github.io/Specs/Carthage/iOS/Fabric.json"
*** Fetching Bond
*** Fetching JWTDecode.swift
*** Fetching ios-library
A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/urbanairship/ios-library.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/prince.ugwuh/Library/Caches/org.carthage.CarthageKit/dependencies/ios-library)) failed with exit code 1
```
still outputs the same message ...I didn't see anything different

**Comment by Prince2k3** [comment]
Seems my co developer is not having this issue ...so I'm going to investigate some more. But at least I know it isn't this library

**Comment by Prince2k3** [comment]
nvm ...both me and my co worker are now experiencing this issue.

**Comment by Prince2k3** [comment]
So after doing some Googling. Turns out this is a Carthage issue. running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` clears Carthage cache and things seem to work fine.

**Comment by kissingfire123** [comment]
> So after doing some Googling. Turns out this is a Carthage issue. running `rm -rf ~/Library/Caches/org.carthage.CarthageKit` clears Carthage cache and things seem to work fine.

Thanks so much , it worked for me.  ---from Mac
