### ISSUE TITLE
ITMS-90809: Deprecated API Usage - UIWebView

### ISSUE THREAD

**Issue by KeimyPlaza** [urbanairship/ios-library#219]
# Preliminary Info

### What Airship dependencies are you using?
v10.0.3 via Cocoapods

### What are the versions of any relevant development tools you are using?
Xcode 10.3

# Report

Just submitted my app to TestFlight and got an email with the error:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I was wondering if all the code related to UIWebView will have to be removed and only keep WKWebView.

It was just a warning, the build ended up being available on TestFlight, but I think this is something that will have to be addressed at some point.

Thks

**Comment by BrianBatchelder** [comment]
@KeimyPlaza : SDK 12.0.0-beta.2 is available with all usage of UIWebView removed. Please take a look at it and let us know if it meets your needs. Thanks.

**Comment by pradeep-opsuccess** [comment]
I have tried updating the UrbanAirship to 12.0.0 (pod 'UrbanAirship-iOS-SDK', '~> 12.0.0'). I can see that all the UIWebViews are removed. But i am not able to compile my project. I am getting the error **No such module 'AirshipKit'**. I have tired deleting the derived data, changed the framework search paths but with no help. I still can't run my App. Any help would be appreciated.

**Comment by gmoney494** [comment]
@BrianBatchelder any way to get the UIWebView removal into the 11.1.x series? I need to support iOS 10 but also remove UIWebView references to make Apple happy.
