### ISSUE TITLE
Build error w/ 12.0.0: UAUtils.h:126:45: error: expected ')'

### ISSUE THREAD

**Issue by NathanWalker** [urbanairship/ios-library#220]
# Preliminary Info

### What Airship dependencies are you using?
12.0.0

### What are the versions of any relevant development tools you are using?
XCode 10.3 (10G8)

# Report

### What unexpected behavior are you seeing?

Cannot build using latest pod 12.x:

```
Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAUtils.h:126:45: error: expected ')'
+ (nullable UIWindow *)mainWindow:(nullable UIWindowScene *)scene API_AVAILABLE(ios(13.0));
                                            ^
Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common/UAUtils.h:126:35: note: to match this '('
+ (nullable UIWindow *)mainWindow:(nullable UIWindowScene *)scene API_AVAILABLE(ios(13.0));
```

### What is the expected behavior?

Can build.

### What are the steps to reproduce the unexpected behavior?

Use 12.x and build an iOS project with XCode 10.3.

**Comment by marc-scig** [comment]
Hi @NathanWalker,

UIWindowScene is a new type as of iOS 13, which is not supported by XCode 10. Version 12.0 of the SDK requires XCode 11 to build.

**Comment by NathanWalker** [comment]
That makes sense, thank you @marc-scig - I was thinking might be nice to have conditional around that area to make it possible to build with either but I'll upgrade to use 12 👍

**Comment by marc-scig** [comment]
We usually are in the habit of requiring the latest Xcode, since you can still support earlier OS versions and deal with new types using runtime checks. It looks like this wasn't called out explicitly in the CHANGELOG, so I'll see about adding an extra note in there. Thanks for the heads up.
