### ISSUE TITLE
Xcode Version: 10.3 Build system issue

### ISSUE THREAD

**Issue by Mani0080** [urbanairship/ios-library#221]
Xcode Version: 10.3.
Am Using pods. 'UrbanAirship-iOS-SDK'

 if I run with New Build system in Xcode I am getting the following error.

```
Multiple commands produce '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist':
	1	Target 'UrbanAirship-iOS-SDK-AirshipResources' (project 'Pods') has copy command from '/Users/manikandan/MyAPP/Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/Info.plist' to '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist'
	2	Target 'UrbanAirship-iOS-SDK-AirshipResources' (project 'Pods') has process command with output '/Users/manikandan/Library/Developer/Xcode/DerivedData/MyAPP-bmhodmqueqvvozejdpxvzebumkxj/Build/Products/Development-iphoneos/UrbanAirship-iOS-SDK/AirshipResources.bundle/Info.plist'

``` 
I got an answer in stackoverflow. 
Changing the workspace settings will do the magic. So I changed that to Legacy Build system. 
`Xcode->File->Workspace Settings...`

<img width="536" alt="Screenshot 2019-09-20 at 6 34 06 PM" src="https://user-images.githubusercontent.com/41666550/65416717-1be2b580-de16-11e9-8cf3-4b3ba319bf6c.png">

If I change the workSpaceSettings to LegacyBuildsystem, It is working and running. 
But why is that needed?

**Comment by rlepinski** [comment]
We need to know what version of our SDK you are using. Could you please provide the pod.lock file?

**Comment by Mani0080** [comment]
Am using UrbanAirship-iOS-SDK (8.6.3).

**Comment by rlepinski** [comment]
You are using an outdated version of our SDK before the new build system was introduced. We made our SDK work with 9.0+. The current SDK version that is compatible with Xcode 10.3 is 11.1.2, but if you want to use Xcode 11, please use SDK 12.0
