### ISSUE TITLE
UI API Called on a Background Thread

### ISSUE THREAD

**Issue by santibernaldo** [urbanairship/ios-library#222]
Hi

I receive this full stack trace from the Xcode console when I just click on the 'Allow' button after being prompted for receiving the Push Notifications. Can you please tell me what is happening? I'm using the last version of the SDK in my podfile:

pod 'UrbanAirship-iOS-SDK'

And this is happening with Xcode 10.2, even with Xcode 11.

=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 3477, TID: 647122, Thread name: (none), Queue name: com.apple.usernotifications.UNUserNotificationServiceConnection.call-out, QoS: 0
Backtrace:
4   AirshipKit                          0x0000000105f93a9c -[UAPush userPushNotificationsAllowed] + 88
5   AirshipKit                          0x0000000105f9351c -[UAPush createChannelPayload] + 388
6   AirshipKit                          0x0000000105ecc3a4 -[UAChannelRegistrar registerForcefully:] + 200
7   AirshipKit                          0x0000000105f94060 -[UAPush updateChannelRegistrationForcefully:] + 248
8   AirshipKit                          0x0000000105f93f58 -[UAPush updateRegistration] + 468
9   AirshipKit                          0x0000000105f8fd10 -[UAPush setAuthorizedNotificationSettings:] + 376
10  AirshipKit                          0x0000000105f945d8 -[UAPush notificationRegistrationFinishedWithAuthorizedSettings:] + 196
11  AirshipKit                          0x0000000105ea6ea8 __63-[UAAPNSRegistration updateRegistrationWithOptions:categories:]_block_invoke_2 + 84
12  AirshipKit                          0x0000000105ea680c __65-[UAAPNSRegistration getAuthorizedSettingsWithCompletionHandler:]_block_invoke + 112
13  libdispatch.dylib                   0x0000000107f076f4 _dispatch_call_block_and_release + 24
14  libdispatch.dylib                   0x0000000107f08c78 _dispatch_client_callout + 16
15  libdispatch.dylib                   0x0000000107f10bf4 _dispatch_lane_serial_drain + 712
16  libdispatch.dylib                   0x0000000107f118ec _dispatch_lane_invoke + 512
17  libdispatch.dylib                   0x0000000107f1b77c _dispatch_workloop_worker_thread + 1148
18  libsystem_pthread.dylib             0x00000001e3b6a114 _pthread_wqthread + 304
19  libsystem_pthread.dylib             0x00000001e3b6ccd4 start_wqthread + 4
2019-09-25 12:19:11.006164+0200 DEV[3477:647122] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication isRegisteredForRemoteNotifications]
PID: 3477, TID: 647122, Thread name: (none), Queue name: com.apple.usernotifications.UNUserNotificationServiceConnection.call-out, QoS: 0
Backtrace:
4   AirshipKit                          0x0000000105f93a9c -[UAPush userPushNotificationsAllowed] + 88
5   AirshipKit                          0x0000000105f9351c -[UAPush createChannelPayload] + 388
6   AirshipKit                          0x0000000105ecc3a4 -[UAChannelRegistrar registerForcefully:] + 200
7   AirshipKit                          0x0000000105f94060 -[UAPush updateChannelRegistrationForcefully:] + 248
8   AirshipKit                          0x0000000105f93f58 -[UAPush updateRegistration] + 468
9   AirshipKit                          0x0000000105f8fd10 -[UAPush setAuthorizedNotificationSettings:] + 376
10  AirshipKit                          0x0000000105f945d8 -[UAPush notificationRegistrationFinishedWithAuthorizedSettings:] + 196
11  AirshipKit                          0x0000000105ea6ea8 __63-[UAAPNSRegistration updateRegistrationWithOptions:categories:]_block_invoke_2 + 84
12  AirshipKit                          0x0000000105ea680c __65-[UAAPNSRegistration getAuthorizedSettingsWithCompletionHandler:]_block_invoke + 112
13  libdispatch.dylib                   0x0000000107f076f4 _dispatch_call_block_and_release + 24
14  libdispatch.dylib                   0x0000000107f08c78 _dispatch_client_callout + 16
15  libdispatch.dylib                   0x0000000107f10bf4 _dispatch_lane_serial_drain + 712
16  libdispatch.dylib                   0x0000000107f118ec _dispatch_lane_invoke + 512
17  libdispatch.dylib                   0x0000000107f1b77c _dispatch_workloop_worker_thread + 1148
18  libsystem_pthread.dylib             0x00000001e3b6a114 _pthread_wqthread + 304
19  libsystem_pthread.dylib             0x00000001e3b6ccd4 start_wqthread + 4

Thanks!

**Comment by rlepinski** [comment]
What version of the pod? Could you post your pod lock file?
