### ISSUE TITLE
Urban Airship SDK latest sdk(Version 12.0.0) not getting updated through pod install

### ISSUE THREAD

**Issue by PratibhaShetty** [urbanairship/ios-library#223]
Hi,

I observed that latest UA SDK Version 12.0.0 is not getting installed through pod. Current version used in the project is 11.1.2.  Please refer a screenshot for your reference. 

<img width="424" alt="Screen Shot 2019-10-04 at 3 29 29 PM" src="https://user-images.githubusercontent.com/18182731/66199220-c8952080-e6bb-11e9-8890-3323a44c3459.png">

**Comment by BrianBatchelder** [comment]
You might need to run `pod update` as explained [here](https://guides.cocoapods.org/using/pod-install-vs-update.html). If this does not resolve the issue, please post your Podfile.
