### ISSUE TITLE
Support for Swift Package Manager?

### ISSUE THREAD

**Issue by MoridinBG** [urbanairship/ios-library#224]
Now that Xcode 11 is officially out, is SPM support planned?

**Comment by rlepinski** [comment]
@MoridinBG We are waiting for SPM to support resources before we can use it.

**Comment by pedrosilva88** [comment]
Did you implemented this already?

**Comment by BrianBatchelder** [comment]
Our SDK and many other libraries use and require resource bundles. As noted above, Swift Package Manager does not yet support resources. There is a long discussion of SPM resource support [here](https://forums.swift.org/t/swift-pm-bundles-and-resources/13981). We are monitoring SPM and will look into adding support when we are able.

**Comment by joshuapoq** [comment]
Do you have an update on this @BrianBatchelder? I'm assuming you will have this in for around September?

**Comment by BrianBatchelder** [comment]
No update. Stay tuned.

**Comment by criticalmatter** [comment]
No SPM support in 14.0?  Bummer.

**Comment by rlepinski** [comment]
@criticalmatter SDK 14 still depends on Xcode 11 and is not our build that will require Xcode 12. That will land in SDK 14.1. We should have a beta next weekish for all the new features (App clips, new location permission, SPM, etc..). I will keep you posted.

**Comment by rlepinski** [comment]
@criticalmatter https://github.com/urbanairship/ios-library/tree/14.1.0-beta1

We will have a final release once Xcode 12 GM is out
