### ISSUE TITLE
Swift Compile Error - No such module 'AirshipKit' - Swift

### ISSUE THREAD

**Issue by pradeep-opsuccess** [urbanairship/ios-library#225]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
12.0.0

### What are the versions of any relevant development tools you are using?
Xcode 11.1, iOS 12.0

# Report

### What unexpected behavior are you seeing?
Getting error as **No such module 'AirshipKit'** after installing 12.0.0 through Pods

### What is the expected behavior?
Need the Library to run along with the App

### What are the steps to reproduce the unexpected behavior?
Upadating the Pods to 12.0.0

### Do you have logging for the issue?
No

**Comment by marc-scig** [comment]
Hi @pradeep-opsuccess,

Have you tried cleaning your resources, such as deleting the derived data folder or running `pod deintegrate` and `pod install`?  Also, what version of Cocoapods are you using?

**Comment by marc-scig** [comment]
Ah, I see your other comment, never mind about the derived data. Another question, are you using the `use_frameworks!` directive in your Podfile? I believe that's a requirement.

**Comment by pradeep-opsuccess** [comment]
Hi Urbanairship/Ios-Library,

I have removed the derived data but haven't tried use_frameworks. Why is it
needed?

**Comment by marc-scig** [comment]
AirshipKit is written in Objective-C, and this means it can't be imported from Swift as a static library without also creating a bridging header, which to my knowledge CocoaPods doesn't do. the `use_frameworks!` directive makes CocoaPods package it as a proper dynamic framework, which makes Swift integration much easier. 

We mention it in the [Getting Started](https://docs.airship.com/platform/ios/getting-started/#cocoapods) docs, so I'd recommend checking those out if you haven't already. Let us know if that helps.

**Comment by pradeep-opsuccess** [comment]
Hi Urbanairship/Ios-Library,

I am using use_frameworks! in the Pod File. But that doesn't help anyway. I
still get the same error.

Thanks & Regards,
Pradeep Reddy Kypa
8801908980

**Comment by marc-scig** [comment]
That's strange. Can you share your podfile?  Also, what does cocoapods say on the command line when you run `pod install`?
