### ISSUE TITLE
Split UI into a subpod

### ISSUE THREAD

**Issue by bofeizhu** [urbanairship/ios-library#226]
Hi UA team,

Could you consider split UI-related files/resources into a subpod/dependency? ]

Thanks

**Comment by rlepinski** [comment]
@bofeizhu Thanks for the suggestion. What issues are our resources causing?

**Comment by bofeizhu** [comment]
We’ve been trying to reduce our app size.

**Comment by rlepinski** [comment]
@bofeizhu SDK is now split up into subspecs. See https://docs.airship.com/platform/ios/getting-started/#cocoapods
