### ISSUE TITLE
Doesn't compile with Xcode11  

### ISSUE THREAD

**Issue by umapandey700** [urbanairship/ios-library#227]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

   UrbanAirship-iOS-SDK (12.0.0)
### What are the versions of any relevant development tools you are using?

I am seeing compilation error on 
.../Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipResources/ios/UAMessageCenterMessageViewController.xib:OX7-dF-5oP: error: WKWebView before iOS 11.0 (NSCoding support was broken in previous versions) [6]

Also there are other xib files in Resources directory, they all have Deployment target set to XCODE 10, Can you change it to **_Xcode11 and later_**
<img width="261" alt="Screen Shot 2019-10-23 at 10 27 09 AM" src="https://user-images.githubusercontent.com/20000275/67403358-cb2ebb80-f57f-11e9-91c9-0bd8833c6625.png">

### What is the expected behavior?

No compilation error

**Comment by BrianBatchelder** [comment]
Thanks for the report. We will look into it.

**Comment by crow** [comment]
@umapandey700 What version of Xcode were you using here? "Latest Xcode" option should select Xcode 11 when opened in Xcode 11.

**Comment by umapandey700** [comment]
I was using xcode11

**Comment by crow** [comment]
This appears to be an issue with Xcode itself. The nibs have the correct setting (latest) but Xcode fails to select the latest version. Deployment is properly updating to latest (11). This could potentially be an issue with running Xcode 11 nibs in Mojave. I've made a not to re-check this behavior when we're able to update our work environments to Catalina.
![image](https://user-images.githubusercontent.com/2199816/67964596-c55b5a80-fbbd-11e9-99f1-376f5a3c9efe.png)

**Comment by BrianBatchelder** [comment]
This is an issue with Xcode 11.2. Creating a new XIB causes the exact same behavior. Upgrading a xib to `Opens in Xcode 11` only upgrades the tools and plugins versions. It does not change any data in the xib. Upgrading also adds the line `<development version="11000" identifier="xcode"/>` to indicate Xcode 11, but then removes the line when the xib is next opened, reverting the dialog back to `Opens in Latest Xcode (10.0)`

I manually checked all of our XIBs, and none of them are specifying Xcode 10. We will continue to monitor this issue in new versions of Xcode.
