### ISSUE TITLE
Crash in NSManagedContext+UAAdditions.m file while launching the application

### ISSUE THREAD

**Issue by Aishwaryalaxmi** [urbanairship/ios-library#236]
We are facing a crash while launching the application in NSManagedContext+UAAdditions.m file.

Please find the attached logs.

Xcode Used - 11.0
Airship SDK Version - 13.0.2
**Crashes observed on 11.4, 11.0.1 iOS versions**
===============================================

-[__NSFrozenDictionaryM bytes]: unrecognized selector sent to instance 0x1c4235200
(
	0   CoreFoundation                      0x0000000182162da4 <redacted> + 252
	1   libobjc.A.dylib                     0x000000018131c5ec objc_exception_throw + 56
	2   CoreFoundation                      0x0000000182170098 <redacted> + 0
	3   CoreFoundation                      0x00000001821685c8 <redacted> + 1380
	4   CoreFoundation                      0x000000018204e41c _CF_forwarding_prep_0 + 92
	5   Foundation                          0x0000000182aa1928 <redacted> + 316
	6   Foundation                          0x0000000182aa17ac <redacted> + 44
	7   Foundation                          0x0000000182ac0580 <redacted> + 64
	8   CoreData                            0x0000000184a41350 <redacted> + 2476
	9   CoreData                            0x0000000184a790b0 <redacted> + 456
	10  CoreData                            0x0000000184c5a548 <redacted> + 780
	11  CoreData                            0x0000000184c5bc80 <redacted> + 388
	12  CoreData                            0x0000000184c500e4 <redacted> + 24
	13  CoreData                            0x0000000184ab5000 <redacted> + 248
	14  CoreData                            0x0000000184b37ba4 <redacted> + 84
	15  libdispatch.dylib                   0x000000010817919c _dispatch_client_callout + 16
	16  libdispatch.dylib                   0x00000001081869bc _dispatch_queue_barrier_sync_invoke_and_complete + 120
	17  CoreData                            0x0000000184b37aa0 <redacted> + 256
	18  CoreData                            0x0000000184c280cc <redacted> + 264
	19  CoreData                            0x0000000184b698f8 <redacted> + 236
	20  CoreData                            0x0000000184b64fcc <redacted> + 204
	21  CoreData                            0x0000000184a47704 <redacted> + 660
	22  CoreData                            0x0000000184b44d80 <redacted> + 1592
	23  CoreData                            0x0000000184b3d758 <redacted> + 268
	24  CoreData                            0x0000000184a47130 <redacted> + 416
	25  CoreData                            0x0000000184a6818c <redacted> + 1264
	26  Airship                             0x000000010674b4ac -[NSManagedObjectContext(UAAdditions) safeSave] + 312
	27  Airship                             0x00000001068797e4 __77-[UARemoteDataStore overwriteCachedRemoteDataWithResponse:completionHandler:]_block_invoke + 744
	28  Airship                             0x000000010674b28c __56-[NSManagedObjectContext(UAAdditions) safePerformBlock:]_block_invoke + 180
	29  CoreData                            0x0000000184b04554 <redacted> + 156
	30  libdispatch.dylib                   0x000000010817919c _dispatch_client_callout + 16
	31  libdispatch.dylib                   0x0000000108187dfc _dispatch_queue_serial_drain + 768
	32  libdispatch.dylib                   0x000000010817c6ac _dispatch_queue_invoke + 328
	33  libdispatch.dylib                   0x0000000108188d54 _dispatch_root_queue_drain_deferred_wlh + 352
	34  libdispatch.dylib                   0x000000010818fe38 _dispatch_workloop_worker_thread + 676
	35  libsystem_pthread.dylib             0x0000000181d87e70 _pthread_wqthread + 860
	36  libsystem_pthread.dylib             0x0000000181d87b08 start_wqthread + 4
)

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by crow** [comment]
@Aishwaryalaxmi Thanks for reporting. We've found the issue and will get a patch out as soon as possible.

**Comment by rlepinski** [comment]
Fixed in 13.0.3
