### ISSUE TITLE
nskeyedunarchivefromdatatransformername error on latest Airship version in iOS 13.3

### ISSUE THREAD

**Issue by Rahul379** [urbanairship/ios-library#238]
# Preliminary Info

### What Airship dependencies are you using?
Airship version: 13.0.4

### What are the versions of any relevant development tools you are using?
Xcode: 11.3.1
iOS: 13.3
Using Cocoapods for installing UA

# Report

### What unexpected behavior are you seeing?
Getting nskeyedunarchivefromdatatransformername error in iOS 13 device.

CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

### What is the expected behavior?
App should work without issue and crashes.

### What are the steps to reproduce the unexpected behavior?
Run App with latest Arship version 13.0.4 in iOS 13 and above.

### Do you have logging for the issue?
[error] fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
CoreData: fault: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.
2020-01-16 15:45:47.553643+0530 MySolaire[10472:197175] [error] CoreData: One or more models in this application are using transformable properties with transformer names that are either unset, or set to NSKeyedUnarchiveFromDataTransformerName. Please switch to using "NSSecureUnarchiveFromData" or a subclass of NSSecureUnarchiveFromDataTransformer instead. At some point, Core Data will default to using "NSSecureUnarchiveFromData" when nil is specified, and transformable properties containing classes that do not support NSSecureCoding will become unreadable.

**Comment by crow** [comment]
@Rahul379 Looking into this, thanks for reporting.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by crow** [comment]
@Rahul379 Are you certain that you have successfully updated to the Airship version 13.0.4? Is 13.0.4 listed in your podfile.lock? I am not currently able to reproduce this behavior using the parameters you've supplied.

**Comment by Rahul379** [comment]
Yes it updated to 13.0.4
![Screen Shot 2020-01-17 at 10 39 15 AM](https://user-images.githubusercontent.com/25200769/72585882-b448fc80-3915-11ea-89bf-293a691151af.png)

![Screen Shot 2020-01-17 at 10 18 02 AM](https://user-images.githubusercontent.com/25200769/72585891-bca13780-3915-11ea-9c2d-a7dc9768213d.png)

**Comment by Rahul379** [comment]
Hi Crow,

Issue got resolved after restart of machine and clean build.
Thanks for help.
