### ISSUE TITLE
How to use UALegacyInAppMessageFactoryDelegate

### ISSUE THREAD

**Issue by RedPlumber** [urbanairship/ios-library#239]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

I am using version 13.1.0

### What are the versions of any relevant development tools you are using?

Xcode 11.3

# Report

### What unexpected behavior are you seeing?

How to create an object UAInAppMessageScheduleInfo from UALegacyInAppMessaging.scheduleInfo in swift?

UAirship.legacyInAppMessaging()!.scheduleInfo(for: message) does not work anymore

**Comment by BrianBatchelder** [comment]
Can you provide more details as to how the method is not working for you?
