### ISSUE TITLE
UAMessageCenterMessageViewController not loading messages

### ISSUE THREAD

**Issue by drw86312** [urbanairship/ios-library#240]
# Preliminary Info

### What Airship dependencies are you using?
  - UrbanAirship-iOS-AppExtensions (12.0.0)
  - UrbanAirship-iOS-Location (12.0.0):
  - UrbanAirship-iOS-SDK (12.0.0)

### What are the versions of any relevant development tools you are using?
Xcode 11.3
Simulator: iPhone 8 Plus, iOS 13.3

# Report

### What unexpected behavior are you seeing?
When presenting UAMessageCenterMessageViewController and calling `loadMessage(forID: String, onlyIfChanged: Bool, onError: (() -> Void)?`, with valid messageID, nothing is displayed and the error block is not invoked. When the view controller is presented, the only thing visible is a black screen.

### What is the expected behavior?
UAMessageCenterMessageViewController should load and render the message corresponding to the message id.

### What are the steps to reproduce the unexpected behavior?
See image screenshot.
<img width="628" alt="Screen Shot 2020-02-26 at 1 33 40 PM" src="https://user-images.githubusercontent.com/5992668/75381441-5b6a6d80-589e-11ea-93d6-bf6051a6a61a.png">

### Do you have logging for the issue?
No

### What are the steps to reproduce the unexpected behavior?
See screenshot
 
### Do you have logging for the issue?
No

**Comment by marc-scig** [comment]
Hi @drw86312,

The way you're instantiating the view controller is just a basic init with no arguments, so it won't load with the correct xib file and will essentially be blank. Try it like this:

`let vc = UAMessageCenterMessageViewController(nibName: "UAMessageCenterMessageViewController", bundle: UAMessageCenterResources.bundle());`

Also, note that there's already a default implementation of the message center that already takes care of this stuff in UAMessageCenter. In most cases, you're probably better off just calling `        UAMessageCenter.shared().displayMessage(forID: myID)`. If you're doing a custom implementation then disregard that, but nibName and bundle are mandatory arguments for the view controller.

**Comment by drw86312** [comment]
Thanks @marc-scig, I thought that might be the issue. I'm rolling a partial custom implementation, soI want to use UAMessageCenterMessageViewController, but present it myself.

**Comment by marc-scig** [comment]
@drw86312 sorry, I just noticed you're using SDK 12.0.0. The code will look slightly different in that case. I'll post an update in just a sec.

**Comment by marc-scig** [comment]
Equivalent example code for SDK 12.x:

`let vc = UAMessageCenterMessageViewController(nibName: "UAMessageCenterMessageViewController", bundle: UAirship.resources());`

`
UAirship.messageCenter()?.displayMessage(forID: myID);
`

We moved some things around to support modularization in SDK 13. The basic idea is the same, though.

**Comment by marc-scig** [comment]
I'm going to close this issue for now, but feel free to reopen it if you have any further problems.
