### ISSUE TITLE
Multiple named users result in no PNs

### ISSUE THREAD

**Issue by netgfx** [urbanairship/ios-library#242]
# Preliminary Info

### What Airship dependencies are you using?
UA 12.1.2

### What are the versions of any relevant development tools you are using?
latest iOS 13.3.1

# Report

### What unexpected behavior are you seeing?
When a user logs in they can receive PNs normally, if they logout and another user logs in and we change the named user. Everyone stops receiving PNs.

### What is the expected behavior?
When the named user changes, they can receive PNs normally.

### What are the steps to reproduce the unexpected behavior?
Change named user without uninstalling the App

Also wondering if there is a standard way to reset the named user (I couldn't find any information about this). Or if this is a UA limitation in general.

**Comment by BrianBatchelder** [comment]
To force an update of the named user, call [`UAirship.namedUser().forceUpdate()`](https://docs.airship.com/reference/libraries/ios/latest/Airship/Classes/UANamedUser.html#/c:objc(cs)UANamedUser(im)forceUpdate).
To verify the named user, in your [Airship dashboard](http://go.airship.com), go to Audience -> Device Lookup, where you can search by named user.
To reset the named user, set the [identifier](https://docs.airship.com/reference/libraries/ios/latest/Airship/Classes/UANamedUser.html#/c:objc(cs)UANamedUser(py)identifier) to null.
