### ISSUE TITLE
Deprecation warning on Xcode 11.4

### ISSUE THREAD

**Issue by malomartin** [urbanairship/ios-library#244]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
Installed version 12.1.2 using Cocoapods.

### What are the versions of any relevant development tools you are using?

Xcode 11.4
# Report

### What unexpected behavior are you seeing?

When compiling, Xcode raises deprecation warnings: 

/**Users/martinmalo/git/smd-ios/Pods/Pods.xcodeproj MobileCoreServices has been renamed. Use CoreServices instead.**

### What is the expected behavior?

A warning free framework

### What are the steps to reproduce the unexpected behavior?

Build any code using Xcode 11.4 with Airship installed with Cocoapods

### Do you have logging for the issue?

/Users/martinmalo/git/smd-ios/Pods/Pods.xcodeproj MobileCoreServices has been renamed. Use CoreServices instead.

**Comment by crow** [comment]
@malomartin Looks like we have an old reference in our service extension. This will be fixed in the next release. Thanks for reporting.

**Comment by spenrose** [comment]
Looks like it didn't make the latest release, any update on this?

**Comment by marc-scig** [comment]
@spenrose As far as I can tell, we can't fix this warning for the time being. CoreServices is only available on iOS 12 and above, and we still target a minimum of iOS 11, so our pod will fail validation otherwise. I suspect it's a bug, or a hastily coded feature, in Xcode 11.4.

**Comment by BrianBatchelder** [comment]
Release 13.3.2 should solve this issue.
