### ISSUE TITLE
Release 13.2.0 - UAMessageCenterMessageViewDelegate.h file not found when importing Airship

### ISSUE THREAD

**Issue by willemfrishert** [urbanairship/ios-library#245]
# Preliminary Info

### What Airship dependencies are you using?
13.2.0

### What are the versions of any relevant development tools you are using?
- Xcode 11.1
- Carthage 0.34.0

# Report

### What unexpected behavior are you seeing?
```#import Airship```

gives me the following error:
```Could not build Objective-C module 'Airship'```
```'UAMessageCenterMessageViewDelegate.h' file not found```

### What is the expected behavior?
I'm able to upgrade from 13.1.1 to 13.2.0 without breaking changes

### What are the steps to reproduce the unexpected behavior?
- Have a working version to `#import Airship`
- Update dependencies from 13.1.1 to 13.2.0
- Clean project and rebuild

### Do you have logging for the issue?
I'm attaching an image from my xcode where it shows that the `UAMessageCenterMessageViewDelegate.h`-file is added to the project level instead of being public.

<img width="1058" alt="Screen Shot 2020-04-23 at 19 46 06 " src="https://user-images.githubusercontent.com/10768931/80169840-5c1c3900-859b-11ea-91ad-046cd3273788.png">

Let me know if you need me to provide additional information

Thanks in advance!
Will

**Comment by BrianBatchelder** [comment]
@willemfrishert : Thanks for the report. We'll look into it ASAP.

**Comment by BrianBatchelder** [comment]
Looks like you found something, @willemfrishert . If you change that header to public, does the build succeed?

**Comment by willemfrishert** [comment]
@BrianBatchelder: Yes, I can confirm that changing `UAMessageCenterMessageViewDelegate.h` from `project` to `public` will allow me to get a successful build.

**Comment by BrianBatchelder** [comment]
@willemfrishert : We will fix and get a patch out today.

**Comment by BrianBatchelder** [comment]
@willemfrishert : Release 13.2.1 is available. Please give it a try. Let us know how it goes. Thanks.

**Comment by willemfrishert** [comment]
@BrianBatchelder: I just updated to 13.2.1 and got a successful build. Thank for your help!
