### ISSUE TITLE
Duplicate symbol '_versionString'

### ISSUE THREAD

**Issue by fontesrp** [urbanairship/ios-library#247]
# Preliminary Info

### What Airship dependencies are you using?

I'm using `"urbanairship-react-native": "6.1.3"`, which includes the following pod:

`pod  'Airship', '13.1.1'`

### What are the versions of any relevant development tools you are using?

The conflict occurs with a variable that has the same name in `"@sentry/react-native": "1.4.0"`, which includes the pod:

`pod 'Sentry', '~> 5.1.0'`

# Report

### What unexpected behavior are you seeing?

When trying to build our project, we are getting the following error:

```
duplicate symbol '_versionString' in:
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Airship/libAirship.a(UAirshipVersion.o)
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Sentry/libSentry.a(SentryMeta.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The conflict seem to be between [this](https://github.com/urbanairship/ios-library/blob/b8989daf22cfbdf98a87cee2e49b6c5ddefacbc0/Airship/AirshipCore/Source/common/UAirshipVersion.m#L5) global variable declared in `UAirshipVersion.m` and [this](https://github.com/getsentry/sentry-cocoa/blob/0523938387135009121d6c06cd57cb7c0076e4b4/Sources/Sentry/SentryMeta.m#L5) one from `SentryMeta.m`.

### What is the expected behavior?

Project compiling with no error of duplicate symbols. I would suggest adding a prefix to global variables, something like `NSString *const UAirship_versionString = @"13.3.0";`.

I have also opened an [issue](https://github.com/getsentry/sentry-cocoa/issues/546) on Sentry.

### What are the steps to reproduce the unexpected behavior?

1. `npx react-native init myapp`;
2. `cd myapp`;
3. `yarn add @sentry/react-native urbanairship-react-native`;
4. Open Xcode and try to run the app.

### Do you have logging for the issue?

```
duplicate symbol '_versionString' in:
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Airship/libAirship.a(UAirshipVersion.o)
    /Users/rfontes/Library/Developer/Xcode/DerivedData/belezanaweb-gxoinejiyskzddabyitlqjcmbqbe/Build/Products/Debug-iphonesimulator/Sentry/libSentry.a(SentryMeta.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by crow** [comment]
@fontesrp Will look into and discuss options with the team. Thanks for reporting.

**Comment by philipphofmann** [comment]
I just opened up a PR (https://github.com/getsentry/sentry-cocoa/pull/549) to fix this issue for our repo. 
Currently the compiler adds the constant `versionString` to the global symbol table and it might clash with other constants. When adding the static keyword the compiler replaces all occurrences with the value and you should be good.

**Comment by BrianBatchelder** [comment]
@philipphofmann : Thanks for addressing it on your end. We are in the process of doing the same on our end.

**Comment by BrianBatchelder** [comment]
Version 13.3.2 of the iOS SDK and version 7.0.0 of the Airship React-Native plugin are now available. Please update and let us know if you see further issues.
