### ISSUE TITLE
Is urban airship suitable for testing on the latest xcode version?

### ISSUE THREAD

**Issue by achen173** [urbanairship/ios-library#248]
Is urban airship suitable for testing on the latest xcode version?

**Comment by BrianBatchelder** [comment]
Which version of Xcode are you using? Which version of the Airship SDK are you using? Are you using one of our cross-platform frameworks, e.g. React-Native or Xamarin, or the native SDK?

**Comment by achen173** [comment]
I am trying to build an IOS app capable of push notification. First I want to test airship on xcode 11.5 simulator. I would imagine all the airship code will be written in swift, so the native SDK. Can the simulator display the notification if build successfully? Furthermore, is it possible to test airship on the simulator without IOS developer program membership?

https://docs.airship.com/platform/ios/getting-started/

**Comment by BrianBatchelder** [comment]
It is not possible to receive a push notification in the simulator through Apple's servers (APNS). As of [Xcode 11.4](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes), it is possible to simulate push notifications in the simulator by generating an [APNS JSON payload](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification) and dropping it on the simulator (or using the `simctl` command). I am unsure if membership in the developer program is required.

**Comment by achen173** [comment]
Do you know if there is a work around for the APNS like using a cross platform framework or does all ios apps require APNS for push notifications?

**Comment by BrianBatchelder** [comment]
All iOS apps require APNS for push notification delivery.
