### ISSUE TITLE
Issues when migrating from version 12 to 13

### ISSUE THREAD

**Issue by Ricardo1980** [urbanairship/ios-library#250]
# Report

Hello,

I'm updating my app from version 12 to version 13 and I have some issues.
I am trying to use exactly version 13.4.0. My current one is 12.1.2.

I already change the pods, which are different and some small details. But I have some issues I don't know how to fix. Can you help me?

What happened with UAWKWebViewDelegate and UAWKWebViewNativeBridge?
My app uses a WKWebView to render the messages and I need that logic to open the deeplinks.

In these guides, I don't see anything about that:
from 12 to 13
https://github.com/urbanairship/ios-library/blob/master/Documentation/Migration/migration-guide-12-13.md
from 11 to 12
https://github.com/urbanairship/ios-library/blob/6a8f9262703c2fba54937986158c6cfa3d9beae1/Documentation/Migration/migration-guide-11-12.md

I see something here:
https://github.com/urbanairship/ios-library/blob/7dd19c054fffa12c4ca3d63f1211c02ca96d8a40/Documentation/Migration/migration-guide-legacy.md
but when I tap "iOS Message Center Customization Topic Guide" the link is broken.
 
Apart from that:

My app was usig launchRichPushMessageAvailable (and showInboxMessage), to update my inbox if presented, otherwise, present the message with my own vc.
What do I do use now?
Is displayMessageCenterForMessageID something like a unification of launchRichPushMessageAvailable and showInboxMessage?

My app also uses these methods not available anymore.
richPushMessageAvailable: to append the new message to my own inbox view controller.

richPushNotificationArrived and applicationLaunchedWithRichPushNotification:  to refresh the app's badge number with
[[UIApplication sharedApplication] setApplicationIconBadgeNumber:[UAirship inbox].messageList.unreadCount];

What should I use for those cases?
Should I contact the support team for this?

Thanks a lot for your time.

### What Airship dependencies are you using?
  pod 'Airship', '13.4.0'
  pod 'Airship/Core', '13.4.0'
  pod 'Airship/MessageCenter', '13.4.0'

### What are the versions of any relevant development tools you are using?
My xcode is Version 11.5 (11E608c)
I am trying to use exactly version 13.4.0. My current one is 12.1.2.

### What unexpected behavior are you seeing?
Some missing methods when migrating from 12 to 13 and I don't find proper docs.

### What is the expected behavior?
How to migrate old methods.

### What are the steps to reproduce the unexpected behavior?
Try to migrate an old app from 12 to 13.

### Do you have logging for the issue?
NA

**Comment by rlepinski** [comment]
**UAWKWebViewDelegate and UAWKWebViewNativeBridge**

`UAWKWebViewNativeBridge` is just `UANativeBridge` now. `UAWKWebViewDelegate` was an extension of `WKNavigationDelegate` that added a close method, it has been replaced with `UANativeBridgeDelegate` that no longer extends `WKNavigationDelegate`. You can assign to the `UANativeBridge` instance. If you need `WKNavigationDelegate` methods forwarded to you from the native bridge, assign a `WKNavigationDelegate` as a `forwardNavigationDelegate` on the `UANativeBrige`.

Looking into the message center questions next. We will also update the migration guide.

**Comment by rlepinski** [comment]
**Message Center**

For updating the badge, you could use the NSNotification `UAInboxMessageListUpdatedNotification`, and just set it anytime the list is updated. Normally we recommend just updating the [during applicationWillResignActive:](https://docs.airship.com/platform/ios/message-center/#badge-updates)

To handle displaying, we no longer expose when a message is available because that caused some delay in actions if you tap the notification and expected it to navigate directly to message since it requires an additional http request. Instead, you need to use `displayMessageCenterForMessageID:` to handle showing a message. The message may not be available in the listing, so you might need to refresh the message list first. We show a loading indicator while doing that in our provided view controllers. [Example in our view controller](https://github.com/urbanairship/ios-library/blob/master/Airship/AirshipMessageCenter/Source/Display/UADefaultMessageCenterMessageViewController.m#L245)

Instead of `richPushMessageAvailable:`, we just have the UAInboxMessageListUpdatedNotification, where you can sync the message list with your view controller. If that doesn't work for you please let us know why and maybe we can provide a better solution.

We did try to improve the view controllers we expose to be more modular, so you may want to check them out again:
- UADefaultMessageCenterMessageViewController 
- UADefaultMessageCenterListViewController
- UADefaultMessageCenterListViewController

**Comment by Ricardo1980** [comment]
Thanks a lot @rlepinski 

What do you think about this?

With version 12, when I present a message in a web view, decidePolicyForNavigationAction is called when the message is loaded and when the user pressed a button. At that point, I apply my logic to intercept deeplinks and apply my logic (that opens the proper screen inside my app).
I can even see the source code of your bridge.
<img width="1510" alt="Screenshot 2020-06-26 at 13 25 17" src="https://user-images.githubusercontent.com/738681/85862343-8bc50880-b7b9-11ea-8869-d88353160877.png">

However, when I use version 13.4.0, I see that decidePolicyForNavigationAction is called (in my app) when the message is loaded, but not when I tap the button inside the message. Nothing happens. And I cannot see your source code.

Do you know if I am missing something?
Thanks a lot.

**Comment by BrianBatchelder** [comment]
In SDK 13.4.0, if the button is a deep link action, that is handled internally and not passed to the [forwardNavigationDelegate](https://docs.airship.com/reference/libraries/ios/latest/Airship/Classes/UANativeBridge.html#/c:objc(cs)UANativeBridge(py)forwardNavigationDelegate). You would instead get a call to your [deepLinkDelegate](https://docs.airship.com/reference/libraries/ios/latest/Airship/Classes/UAirship.html#/c:objc(cs)UAirship(py)deepLinkDelegate)'s [receivedDeepLink:completionHandler:](https://docs.airship.com/reference/libraries/ios/latest/Airship/Protocols/UADeepLinkDelegate.html#/c:objc(pl)UADeepLinkDelegate(im)receivedDeepLink:completionHandler:) method. The advantage of this method is that the same code can handle deep links from wherever they come: push notifications, message center messages and in-app messages.

**Comment by BrianBatchelder** [comment]
BTW, the source code should be visible to you. It has moved to a new file: `Airship/AirshipCore/Source/ios/UANativeBridge.m`.

**Comment by Ricardo1980** [comment]
Hello @BrianBatchelder 

If I use [UAirship shared].deepLinkDelegate and receivedDeepLink, I don't receive anything.
But I realised my app is using [[[UAirship shared].actionRegistry updateAction] with a block, and I see that block is called with the deeplink. 
In fact, the deeplink was processed properly and a new screen was open, the reason I didn't see this is because the message (with a webview) was not removed.
IS there any problem with that deeplink logic?

Apart from that, I found another bug. 
My app was using decidePolicyForNavigationAction and detecting the deeplink, but not to open it, but to close the message view.
If pressing the button only triggers the deeplink logic, how can I detect that the button was tapped?
I realised that in actionRegistry:updateAction, when a deeplink is received when pressing the button, I also have situation == UASituationWebViewInvocation. Should I use that to detect the tap in the webview that loads the message? is there any other mechanism?

Thanks a lot :)

**Comment by BrianBatchelder** [comment]
@Ricardo1980 : 
> In fact, the deeplink was processed properly and a new screen was open, the reason I didn't see this is because the message (with a webview) was not removed.

Was it your code that opened the new view? I believe your code is handling the message view, so you should have all the control you need to make that work correctly.

> IS there any problem with that deeplink logic?

Overriding the deepLink action is fine.

> Apart from that, I found another bug.
> My app was using decidePolicyForNavigationAction and detecting the deeplink, but not to open it, but to close the message view.
> If pressing the button only triggers the deeplink logic, how can I detect that the button was tapped?
> I realised that in actionRegistry:updateAction, when a deeplink is received when pressing the button, I also have situation == UASituationWebViewInvocation. Should I use that to detect the tap in the webview that loads the message? is there any other mechanism?

If you are using our message view controller, you probably want to use the [close command](https://docs.airship.com/platform/ios/advanced/message-center-custom-webview/). Add ` UAirship.close()` to your javascript and execute it when the button is pressed. Here's an example of what that might look like:

```html
<span class="btn" data-ua-id="Button" data-ua-link="" data-ua-text="Click Here" dir="auto">
    <a href="#" onclick="javascript: 
        if(!window.UAirship || !window.UAirship.runAction) { return true } 
        window.UAirship.runAction(&quot;^d&quot;, &quot;https://docs.airship.com&quot;, Function()); 
        window.UAirship.close(); 
        return false\">Airship Docs</a>
</span>
```

**Comment by Ricardo1980** [comment]
**"Was it your code that opened the new view? I believe your code is handling the message view, so you should have all the control you need to make that work correctly."**
Yes, I have a custom inbox. When you tap a message, I open another screen, I extract the url from the message and then I load that url into a WKWebView.

**"If you are using our message view controller"**
Nope, it is a custom view.
Do I check that thing about javascript in my specific scenario? The HTML/javascript I am presenting is what it comes from the URL I am loding.
Am I missing something?

What's your opinion about using UASituationWebViewInvocation? It seems it is working. I send a notification to the notification center and then the custom controller detects it and closes the custom message view controller.

Thanks a lot for your help.

**Comment by BrianBatchelder** [comment]
Ah, given that the message is displayed in your own WKWebView, you would need to close that view yourself when you open the url in the new view. 

`UASituationWebViewInvocation` will be the situation whenever the action is triggered through our native bridge. If you don't have the ability to send `UAirship.close()`, then you can definitely use `UASituationWebViewInvocation` to indicate the deep link came from the message view. Be aware that you would also receive that situation for any links in an In-App Automation message, as those messages also use our native bridge.

**Comment by marc-scig** [comment]
When `UAirship.close` is handled by the native bridge, this event ultimately gets passed to the native bridge delegate, as the `close` method:

https://github.com/urbanairship/ios-library/blob/35fa74a2f7bed00fd9fce6cc33d95264e523d035/Airship/AirshipCore/Source/ios/UANativeBridge.h#L32 
  
https://github.com/urbanairship/ios-library/blob/90f764174cadd2ecc84981e5b8a6ad7874d90676/Airship/AirshipCore/Source/ios/UANativeBridgeDelegate.h

This method is already implemented by `UADefaultMessageCenterMessageViewController`, which handles out of the box functionality. If you're using your own custom view controller stack, you'll need add the appropriate view controller as a native bridge delegate, and implement that method to receive the callback and close the window yourself.

**Comment by Ricardo1980** [comment]
Thanks @BrianBatchelder and @marc-scig 

There is something I don't understand about UAirship.close.

Right now my inbox and my detail view controllers are custom view controllers/views.
My inbox uses:
[[UAMessageCenter shared].messageList retrieveMessageListWithSuccessBlock
and my message detail view uses the URL from inboxMessage.messageBodyURL to load that into a webview.

A URL like: https://c00211-dl.urbanairship.com/binary/token/aXXXXXXXXX-6x9fysag/fXXXXXX-b479-11ea-8087-02421cf05178?t=Q7bMwXXXXXXXXXXXX_9CP6Rzba5Hi0h8&d=b-WScHC1g3OXXXXXXXXXXXpthU6X8jQ0Db4

When I create a request and load it, I receive an HTML with javascript. This one:

```
<html><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1,user-scalable=no">
    <title>Text</title>
    <style>
        * {
            margin:0;
            padding:0;
            -webkit-box-sizing:border-box;
            -moz-box-sizing:border-box;
            box-sizing:border-box;
        }
        html {
            height:100%;
        }
        body {
            background:#fff;
            color:#333;
            font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;
            height:100%;
        }
        img {
            border:0;
        }
        /* Type */
        h1, h2, h3, h4, h5, h6 {
            line-height:1;
            text-rendering:optimizeLegibility;
            word-wrap:break-word;
        }
        h1 {
            font-size:1.75em; /* 28px */
            padding:0 0 0.71428571428571em;
        }
        h2 {
            font-size:1.5em; /* 24px */
            padding:0 0 0.83333333333333em;
        }
        h3 {
            font-size:1.25em; /* 20px */
            padding:0 0 1em;
        }
        h4 {
            font-size:1.125em; /* 18px */
        }
        h5 {
            font-size:1em; /* 16px */
        }
        h6 {
            font-size:.875em; /* 14px */
        }
        p, ul, ol, dl, table, label, figcaption {
            font-size:.875em;  /* 14px */
            padding:0 0 1.42857142857143em;
        }
        ul p, ol p, table p, ul ul, ol ol, ul ol, ol ul {
            font-size:1em; /* 14px / 14px */
        }
        strong {
            font-weight:bold;
        }
        em {
            font-style:italic;
        }
        small {
            font-size:.85714285714286em;  /* 12px / 14px */
        }
        .btn {
            display:block;
        }
        .btn > a {
            background:#1d2233;
            border-radius:3px;
            color:#fff;
            display:block;
            font-size:20px;
            font-weight:500;
            height:auto;
            line-height:20px;
            margin:0 auto 15px;
            padding:15px 30px;
            text-align:center;
            text-shadow:0 -1px #12161a;
            text-decoration:none;
            white-space:normal;
            width:auto;
            word-wrap:break-word;
        }
        /* grid */
        .row {
            clear:both;
            margin:0 auto;
            padding-top:1.42857142857143em;
            width:93.333333333333%;
        }
        .col {
            float:left;
            margin-left:6.666666666667%;
            min-height:1px;
            position:relative;
            width:20%;
        }
        /* fluid column units */
        .col.two {width:46.666666666667%;}
        .col.three {width:73.333333333333%;}
        .col.four {width:100%;}
        .col:first-child {margin-left:0;}
        /* column offsets */
        .col.offset-1 {margin-left:26.666666666667%;}
        .col.offset-2 {margin-left:53.333333333333%;}
        .col.offset-3 {margin-left:80%;}
        /* fluid column offset sibling widths */
        .col+.col.offset-1 {margin-left:33.333333333333%;}
        .col+.col.offset-2 {margin-left:60%;}
        /* clear floats */
        .row:after {clear:both;content:" ";display:block;font-size:0;height:0;visibility:hidden;}
    </style>
    <script data-ua-id="Page" data-ua-onload="" type="text/javascript">void Function(decodeURIComponent(atob('d2luZG93LmFkZXXXXXXXXXXXXXXXXXXXXXXXXXKCklMkMlMjBmYWxzZSk=')))();</script>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"></head><body class="">
<div class="row">
    <h1 data-ua-id="Headline" data-ua-text="Editable Headline" dir="auto">teatsda</h1>
    <p data-ua-id="Content" data-ua-text="This is editable text. Click here or use the menu to the right to update this content." dir="auto">dsadsaadssddsaddas</p>
    <span class="btn" data-ua-id="Button" data-ua-link="" data-ua-text="Click Here" dir="auto"><a href="#" onclick="javascript: if(!window.UAirship || !window.UAirship.runAction) { return true} void Function(decodeURIComponent(atob('KGZ1XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9uKCkpJTIwJTdEKSgp')))(); return false">test</a></span>
</div>

</body></html>
```
As you can see, there is nothing about UAirship.close there. 
How does that work? Should I inject it? I guess your system is generating that HTML/javascript file.

**"Add UAirship.close() to your javascript and execute it when the button is pressed."**
How can I do that?

BTW, this is a project created many years ago, I just started here and trying to maintain it.

Reading this document, I don't see which one is my case:
https://docs.airship.com/guides/data/custom-events/

Thanks a lot for suggestions.

**Comment by BrianBatchelder** [comment]
@Ricardo1980 : Do you get a deep link action when you click on the button in this message?

**Comment by Ricardo1980** [comment]
@BrianBatchelder Yes, in the composer I select deeplink and that is what I receive in the app. It is processed properly and the correct screen is open when I tap the button in the HTML is presented in my web view. The only issue I have is how to close the message view. Right now I am using notification center and situation == UASituationWebViewInvocation in the closure it is called when a deeplink is received. 
Not sure it this is the best way.  I was wondering if I have to UAirship.close() but I don't see how.
Thanks for suggestions.

**Comment by BrianBatchelder** [comment]
Using `UASituationWebViewInvocation` is your best choice. `UAirship.close()` would also work, but you would need to user our API rather than the Composer to create your messages.

**Comment by Ricardo1980** [comment]
OK, thanks a lot!
