### ISSUE TITLE
iOS 14: UIPasteboard Issue

### ISSUE THREAD

**Issue by kcatigbe** [urbanairship/ios-library#251]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

iOS SDK 12.1.2
### What are the versions of any relevant development tools you are using?

Xcode 12 / iOS 14 Beta
# Report

### What unexpected behavior are you seeing?

Pasteboard access alert
### What is the expected behavior?

no pasteboard access alert
### What are the steps to reproduce the unexpected behavior?

launch an app with SDK installed
### Do you have logging for the issue?

I'm sure you've all seen the news by now about pasteboard access;

Just wondering if a fix will be incoming for the Airship SDK?

**Comment by crow** [comment]
@kcatigbe Thanks for reporting this. We are working on getting the the latest Xcode and iOS related fixes in the upcoming release.

**Comment by rlepinski** [comment]
Yep. We use the clipboard to check if a special token is available to display an alert with the channel ID. Its useful for finding a channel on a device without any dev resources - https://docs.airship.com/platform/ios/advanced/channel-capture-tool/

For now, you can set `channelCaptureEnabled` to `NO` in the config. We will try to have an alternative solution by the time iOS 14 is out, or we will have to remove this feature.

**Comment by kcatigbe** [comment]
Awesome thank you very much for your quick responses!

**Comment by joshuapoq** [comment]
Is there an update on the alternate solution? Why was this closed?

**Comment by rlepinski** [comment]
@joshuapoq We disabled channel capture tool by default in 13.5.2, and reenabled it in 14.0.0 with a new activation mechanism. In 14.0, you have to foreground the app 6 times in 30 seconds then the SDK will write the channel to the pasteboard with a 1 min expiry.

**Comment by jskrepnek** [comment]
I can't reproduce on: https://app.testobject.com/#/kohotechteam/koho-alpha-ios/manual/viewer?device=iPad_Air_2_IOS14_Beta_3_real_us&dc=US&tunnelIdentifier=
