### ISSUE TITLE
Systematic crash during Accengage user migration

### ISSUE THREAD

**Issue by Woildan** [urbanairship/ios-library#253]
# Preliminary Info

### What Airship dependencies are you using?
AirshipCore 13.4.0
AirshipAccengage 13.4.0
AirshipAutomation 13.4.0
AirshipLocation 13.4.0

Installed using Carthage.

### What are the versions of any relevant development tools you are using?

iOS 13.0 & 13.5.1
XCode Version 11.5 (11E608c)
Carthage 0.34.0

# Report

### What unexpected behavior are you seeing?

Some of our users (possibly a lot!) are experiencing a **systematic** crash on app startup after migrating to our last release.
This release integrates the Airship SDKs.
Before this we were using the **Accengage SDK version 6.4.3**.

The crash occurs right at startup (after splashscreen) during Airship takeOff.
The problem seems to come from the Accengage data migration (see stack trace provided).

Please note that because the crash occurs so early during app launch that no crash reports are reported in AppCenter.
We were able to notice this problem and gather this stack trace only because we noticed the problem on some of our devices.

_**So it is possible affecting quite a lot of our user base, and since the only workaround is to delete then re-install the app, this issue is critical.**_

### What is the expected behavior?

No crash, proper Accengage data migration.

### What are the steps to reproduce the unexpected behavior?

Migrate from an app running Accengage SDK to an app running Airship SDK, but this is enough on its own to reproduce the crash.
Our guess is it depends on the content of the Accengage data file (corrupted? specific data inside? old format?).

### Do you have logging for the issue?

```
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:
abort() called

Last Exception Backtrace:
0   CoreFoundation                	0x1aa7e554c __exceptionPreprocess + 224
1   libobjc.A.dylib               	0x1aa5000c8 objc_exception_throw + 59
2   Foundation                    	0x1aab327c8 -[NSCoder+ 636872 (Exceptions) __failWithException:] + 171
3   Foundation                    	0x1aab328dc -[NSCoder+ 637148 (Exceptions) __failWithExceptionName:errorCode:format:] + 275
4   Foundation                    	0x1aaba11c0 _decodeObjectBinary + 503
5   Foundation                    	0x1aaaeffa4 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 867
6   Foundation                    	0x1aaac2b58 -[NSArray+ 179032 (NSArray) initWithCoder:] + 175
7   Foundation                    	0x1aaba180c _decodeObjectBinary + 2115
8   Foundation                    	0x1aaaeffa4 -[NSKeyedUnarchiver _decodeArrayOfObjectsForKey:] + 867
9   Foundation                    	0x1aaab8c64 -[NSDictionary+ 138340 (NSDictionary) initWithCoder:] + 179
10  Foundation                    	0x1aaba180c _decodeObjectBinary + 2115
11  Foundation                    	0x1aaba0d14 _decodeObject + 343
12  Foundation                    	0x1aaaa8b44 -[NSKeyedUnarchiver decodeObjectForKey:] + 171
13  Foundation                    	0x1aaafec44 +[NSKeyedUnarchiver unarchiveObjectWithData:] + 91
14  AirshipAccengage              	0x1017598e0 -[UAAccengage accengageSettings] + 22752 (UAAccengage.m:80)
15  AirshipAccengage              	0x101759efc -[UAAccengage migrateSettingsToAnalytics:] + 24316 (UAAccengage.m:151)
16  AirshipAccengage              	0x10175959c -[UAAccengage initWithDataStore:channel:push:analytics:] + 21916 (UAAccengage.m:43)
17  AirshipAccengage              	0x10175979c +[UAAccengage accengageWithDataStore:channel:push:analytics:] + 22428 (UAAccengage.m:58)
18  AirshipAccengage              	0x10175833c +[UAAccengageModuleLoader moduleLoaderWithDataStore:channel:push:analytics:] + 17212 (UAAccengageModuleLoader.m:24)
19  AirshipCore                   	0x10194a4e0 +[UAirship accengageModuleLoaderWithDataStore:channel:push:analytics:] + 287968 (UAirship.m:567)
20  AirshipCore                   	0x101948808 -[UAirship initWithRuntimeConfig:dataStore:] + 280584 (UAirship.m:194)
21  AirshipCore                   	0x101949544 +[UAirship executeUnsafeTakeOff:] + 283972 (UAirship.m:336)
22  AirshipCore                   	0x10194909c __20+[UAirship takeOff:]_block_invoke + 282780 (UAirship.m:257)
23  libdispatch.dylib             	0x1aa48d088 0x1aa48a000 + 12424
24  libdispatch.dylib             	0x1aa48e770 0x1aa48a000 + 18288
25  AirshipCore                   	0x10194905c +[UAirship takeOff:] + 282716 (UAirship.m:256)
26  Mappy                         	0x100ce1ae8 0x100c04000 + 908008
27  Mappy                         	0x10127529c 0x100c04000 + 6754972
28  UIKitCore                     	0x1ae843768 0x1ade2f000 + 10569576
```

**Comment by BrianBatchelder** [comment]
@Woildan : Thanks for your report. We are looking into it.

**Comment by BrianBatchelder** [comment]
@Woildan : BTW, urgent and critical issues should be reported to our [support team](https://support.airship.com).

**Comment by rlepinski** [comment]
@Woildan Thanks for reporting the issue. 13.5.3 is out with a fix.

**Comment by Woildan** [comment]
Thanks for the fix.
Now that our user base has started migrating to Airship without the module we won't do another release to re-integrate it.
I hope this can avoid other people a bad surprise.
