### ISSUE TITLE
'NSJSONSerialization+UAAdditions.h' file not found 

### ISSUE THREAD

**Issue by yashbedi** [urbanairship/ios-library#255]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info
I'm getting compile time error in  `UAInboxAPIClient.m`  

The error is :
`'NSJSONSerialization+UAAdditions.h' file not found`

![23](https://user-images.githubusercontent.com/3687481/90387889-9c507b80-e0a4-11ea-97e9-ac9a76f52fd6.png)

### What Airship dependencies are you using?

UrbanAirship-iOS-SDK, 12.1.2
### What are the versions of any relevant development tools you are using?

Xcode 11.6
# Report

**Comment by BrianBatchelder** [comment]
@yashbedi : I am unable to reproduce your issue. Some questions for you:

- What changed? 
- Did this start happening when you upgraded to Xcode 11.6? 
- Have you tried a clean build? 
- Did you run `pod install` after upgrading Xcode?
- What's in your `Podfile`?

**Comment by yashbedi** [comment]
Hey @BrianBatchelder hope you're well.
So

**1,2.** Yes post updating my XCode to 11.6.  This started happening.
**3.** Clean build many a times. Even tried downloading Xcode 11.3 and doing all such as clean build + removing derived data, quitting and re-opening.
**4.** I've already tried running `pod install` post updating Xcode. Even tried with de-integrating.
**5.** This is in the `Podfile` -> `pod 'UrbanAirship-iOS-SDK','12.1.2'`

This is what it says as well : `Lexical or Preprocessor Issue Group`
[check here for better understanding ](https://ibb.co/WsbhVy3)

Since `'NSJSONSerialization+UAAdditions.h'` is in more than 30 files.

The moment I fix one error it jumps to another file.

The fix I applied was: Instead of using `import "NSJSONSerialization+UAAdditions.h"`
I tried `import <NSJSONSerialization+UAAdditions.h>`

I'm using angular brackets instead of quotes and it started working. 

Now the problem is, this change is in the `Pods/UrbanAirship-iOS-SDK/*.swift` . 
> PS `*.swift` -> Signifies the files which have the above reported error.

Which I clearly don't want everyone todo + our team is of more than 10+ iOS Devs.

Couple of colleagues are facing this problem initially I thought I'm having it.


You mind suggesting what should I do so that there are no changes I would be making in `Pods/Urban.....`.

Thank you.!

**Comment by BrianBatchelder** [comment]
@yashbedi : Thanks for getting back to us. Some more questions for you:
- What version of CocoaPods are you using?
- When you wrote "Even tried with de-integrating", do you mean you removed `Podfile.lock` and the Pods directory and then re-ran `pod install`?
- Is CocoaPods actually copying `'NSJSONSerialization+UAAdditions.h'`? It should be in `Pods/UrbanAirship-iOS-SDK/AirshipKit/AirshipKit/common`.
- Is `'NSJSONSerialization+UAAdditions.h'` appearing under the Pods project in Xcode?
![Screen Shot 2020-08-18 at 8 31 20 AM](https://user-images.githubusercontent.com/2123928/90533375-3f4cd800-e12d-11ea-823d-3d43d7c213d9.png)
- If it is, does its target membership look like this?
![Screen Shot 2020-08-18 at 8 33 12 AM](https://user-images.githubusercontent.com/2123928/90533795-d3b73a80-e12d-11ea-9914-23decd948247.png)
- Are you installing any non-Airship pods? If so, are they working correctly?
- Finally, make sure you have `use_frameworks!` in your Podfile. Here's what mine looks like:
```
use_frameworks!
platform :ios, '11.0'

target 'SwiftSample' do
  pod 'UrbanAirship-iOS-SDK', '~> 12.1'
  pod 'UrbanAirship-iOS-DebugKit', '~> 12.1'
end

target 'SampleServiceExtension' do
  pod 'UrbanAirship-iOS-AppExtensions', '~> 12.1'
end
```

**Comment by yashbedi** [comment]
ahh.!!!
got it.

You can close this issue. 
So we've our development pod and it happens to have the 'NSJSONSerialization+UAAdditions.h' file with `.m` file.

May be coz of that. it is happening .

Thank you so much for your time, Man.
