### ISSUE TITLE
Crash in iOS SDK - in [UAPreferenceDataStore setObject:forKey:]

### ISSUE THREAD

**Issue by iosmagesh18** [urbanairship/ios-library#256]
This is one of our top crashes. We're using the SDK version 10.0.4.

Here is the detailed crash log:

Crashed: NSOperationQueue 0x1578263e0 (QOS: UNSPECIFIED)
0  libobjc.A.dylib                0x1ae6d9dc0 objc_release + 16
1  Foundation                     0x1aed713ac -[NSObject(NSKeyValueObservingPrivate) _changeValueForKeys:count:maybeOldValuesDict:maybeNewValuesDict:usingBlock:] + 652
2  Foundation                     0x1aecbc06c -[NSObject(NSKeyValueObservingPrivate) _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 816
3  CoreFoundation                 0x1ae88b284 -[CFPrefsSource forEachObserver:] + 324
4  CoreFoundation                 0x1ae88cce4 -[CFPrefsSource _notifyObserversOfChangeFromValuesForKeys:toValuesForKeys:] + 108
5  CoreFoundation                 0x1ae9e4974 ___CFPrefsDeliverPendingKVONotificationsGuts_block_invoke + 468
6  CoreFoundation                 0x1ae8ecefc __CFDictionaryApplyFunction_block_invoke + 28
7  CoreFoundation                 0x1ae9cb554 CFBasicHashApply + 140
8  CoreFoundation                 0x1ae8ece98 CFDictionaryApplyFunction + 204
9  CoreFoundation                 0x1ae9e0898 _CFPrefsDeliverPendingKVONotificationsGuts + 264
10 CoreFoundation                 0x1ae9e0770 -[_CFXPreferences _deliverPendingKVONotifications] + 92
11 CoreFoundation                 0x1ae90f744 __108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 436
12 CoreFoundation                 0x1ae90ef68 normalizeQuintuplet + 356
13 CoreFoundation                 0x1ae87bf64 -[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 136
14 CoreFoundation                 0x1ae87f0e4 -[_CFXPreferences setValue:forKey:appIdentifier:container:configurationURL:] + 124
15 CoreFoundation                 0x1ae9e2cac _CFPreferencesSetAppValueWithContainerAndConfiguration + 136
16 Foundation                     0x1aecb69dc -[NSUserDefaults(NSUserDefaults) setObject:forKey:] + 68
**17 AirshipKit                     0x100e2a32c -[UAPreferenceDataStore setObject:forKey:] + 144**
18 AirshipKit                     0x100e36774 __52-[UARemoteDataManager refreshWithCompletionHandler:]_block_invoke + 172
19 AirshipKit                     0x100e35280 __51-[UARemoteDataAPIClient fetchRemoteData:onFailure:]_block_invoke_2 + 876
20 AirshipKit                     0x100e3a1c8 __81-[UARequestSession operationWithRequest:retryDelay:retryWhere:completionHandler:]_block_invoke + 104
21 AirshipKit                     0x100e4f718 __44-[UAURLRequestOperation startAsyncOperation]_block_invoke + 192
22 CFNetwork                      0x1b1c486ec CFNetServiceBrowserSearchForServices + 96248
23 CFNetwork                      0x1b1c593ec _CFHTTPMessageSetResponseProxyURL + 8176
24 Foundation                     0x1aed8a004 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 24
25 Foundation                     0x1aec8c5a4 -[NSBlockOperation main] + 104
26 Foundation                     0x1aed8c344 __NSOPERATION_IS_INVOKING_MAIN__ + 24
27 Foundation                     0x1aec8c27c -[NSOperation start] + 752
28 Foundation                     0x1aed8cd70 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
29 Foundation                     0x1aed8c830 __NSOQSchedule_f + 184
30 libdispatch.dylib              0x1ae657f24 _dispatch_block_async_invoke2 + 144
31 libdispatch.dylib              0x1ae64b5ac _dispatch_client_callout + 20
32 libdispatch.dylib              0x1ae64dd60 _dispatch_continuation_pop + 408
33 libdispatch.dylib              0x1ae64d4c0 _dispatch_async_redirect_invoke + 588
34 libdispatch.dylib              0x1ae65a724 _dispatch_root_queue_drain + 348
35 libdispatch.dylib              0x1ae65aed0 _dispatch_worker_thread2 + 116
36 libsystem_pthread.dylib        0x1ae6b16dc _pthread_wqthread + 216
37 libsystem_pthread.dylib        0x1ae6b79c8 start_wqthread + 8

We are facing a lot of crashes. Could you please look into this issue and resolve it at the earliest. Thanks!

**Comment by BrianBatchelder** [comment]
@iosmagesh18 : It's not clear to me _what_ the crash is. Do you have any more information, e.g. what exception is being thrown by this thread?

**Comment by marc-scig** [comment]
@iosmagesh18 A few more questions. How frequent is the crash? Is it limited to specific iOS versions? Also is your app doing any KVO on NSUserDefaults?

**Comment by iosmagesh18** [comment]
@BrianBatchelder 

Here is the exception logs that we got from the crash logs.

Crashed: NSOperationQueue 0x1578263e0 (QOS: UNSPECIFIED)
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000006747d62c0

@marc-scig We are not doing any KVO mechanism on NSUserDefaults.

**Comment by marc-scig** [comment]
@iosmagesh18 How frequent is the crash? Are there particular iOS versions affected by this?

**Comment by SebastianBoldt** [comment]
Any Progress on this one? We are also experiencing the same issue.
