### ISSUE TITLE
Missing UAAutomation.xcdatamodeld file in the Copy Bundle Resources phase

### ISSUE THREAD

**Issue by matteozajac** [urbanairship/ios-library#257]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Release 14.1.0
### What are the versions of any relevant development tools you are using?

Xcode 12
# Report

### What unexpected behavior are you seeing?

Missing UAAutomation.xcdatamodeld file in the Copy Bundle Resources phase.
Calling takeOff throws _Cannot load NSManagedObjectModel.  nil is an illegal URL parameter_
### What is the expected behavior?

TakeOff should run without issue.

**Comment by rlepinski** [comment]
@matteozajac How are you integrating the SDK? Swift Package Manager, Cocaopods, Carthage, Xcframework, or some other way?

**Comment by matteozajac** [comment]
@rlepinski Git submodule

**Comment by rlepinski** [comment]
Could you be more specific? Are you manually linking the projects?

**Comment by rlepinski** [comment]
I see in our build phase that is indeed missing, not sure why its not an issue for our samples.

**Comment by matteozajac** [comment]
Sorry, installation process was based on Add an XCframework to your project from the
https://docs.airship.com/platform/ios/advanced/alternative-installation-methods/#selecting-frameworks

I've migrated directly from 13.2 to 14.1 and issue has occurred.

**Comment by marc-scig** [comment]
@matteozajac Thanks for the report. We're looking into it, and I'll keep you updated.

**Comment by marc-scig** [comment]
@matteozajac 14.1.1 is released. This should clear up your issue, but do let us know if you encounter any other problems. Thanks for you patience.
