### ISSUE TITLE
library not found for -lAirshipExtensions on Xcode 12 Simulator. 

### ISSUE THREAD

**Issue by srinadh-k** [urbanairship/ios-library#258]
# Preliminary Info

### What Airship dependencies are you using?

I am using Airship (14.1.1) and AirshipExtensions (14.1.1) dependencies with help of CocoaPods. 
### What are the versions of any relevant development tools you are using?

Xcode 12

# Report

### What unexpected behavior are you seeing?

My application is not able to compile on iOS Simulator and getting the following error after upgrading to Xcode 12 from Xcode 11.7

**library not found for -lAirshipExtensions** 

### What is the expected behavior?

I was able to run my iOS app on  Xcode 11.7  simulators with the following Airship dependencies. 
Airship (14.0.0-beta1)
AirshipExtensions (14.0.0-beta1)

### What are the steps to reproduce the unexpected behavior?
upgrade Airship (14.1.1) and AirshipExtensions (14.1.1) and run on Xcode 12 and getting the following error 
**library not found for -lAirshipExtensions** 

NOTE: integrated Airship and AirshipExtensions using CocoaPods.

Anyone facing a similar type of issue on Xcode 12?

**Comment by rlepinski** [comment]
What version of cocoapods are you using? Have you tried clearing your derived data and calling `pod install` again after updating to latest Xcode? What is the default xcode command line version ?

**Comment by srinadh-k** [comment]
Cocopods Version: 1.9.3
Default Commander Line: Xcode 12.0 (12A7209)

Yes removed derived data and did pod install and still same issue in simulator.

**Comment by rlepinski** [comment]
@srinadh-k could you share your pod file? are you using `use_frameworks` flag ?

**Comment by srinadh-k** [comment]
@rlepinski  no not using in pod file.

**Comment by rlepinski** [comment]
Could you post the contents of the podfile?

**Comment by srinadh-k** [comment]
I can not provide all the content of the pod file due to the company policies.

**Comment by marc-scig** [comment]
@srinadh I'm unable to reproduce this issue. what do the logs look like in the command line when running `pod install` with your podfile?

**Comment by srinadh-k** [comment]
@marc-scig I got **Pod installation complete!** But i am getting an error when I run the application on iOS Simulator but the application compiling and running fine on a real iPhone device.

Please find attached images for your reference.
 
<img width="892" alt="Screen Shot 2020-09-24 at 4 40 12 PM" src="https://user-images.githubusercontent.com/28667119/94203326-cefc4980-fe84-11ea-8a17-986922b8a257.png">
<img width="1250" alt="Screen Shot 2020-09-24 at 4 36 45 PM" src="https://user-images.githubusercontent.com/28667119/94203335-d4599400-fe84-11ea-822f-2549a373125f.png">

**Comment by rlepinski** [comment]
@srinadh-k I think we will need more information than what you can share in order to reproduce your problem. Please contact support.

**Comment by srinadh-k** [comment]
@rlepinski  can you please tell me what other information required. so i will provide you.

**Comment by rlepinski** [comment]
I think we need the contents of your pod file, full logs, and if you can somehow reproduce this in a sample app that you can share that would be ideal. When we configure a new app using cocoapods we are not having those issues.

**Comment by srinadh-k** [comment]
Please check my pod file and I removed all other dependencies and what full logs you needed please let me know. 
 
[Podfile.txt](https://github.com/urbanairship/ios-library/files/5279413/Podfile.txt)

**Comment by marc-scig** [comment]
@srinadh-k Well the first thing that jumps out at me is that your Podfile defines the notification service target within the definition for test bundle, instead of its own top level target

```
target 'xxxxTests' do
        inherit! :search_paths
        # Pods for testing
    end
    target 'XXXNotificationService' do
        inherit! :search_paths
        pod 'AirshipExtensions', '~>14.0', :modular_headers => true
    end
end
```

**Comment by srinadh-k** [comment]
@marc-scig No, if you observer the entire my pod file below you can find test bundle and NotificationService bundle withing main level target. 

```
target 'xxxxxx' do

    pod 'Airship', '~>14.0', :modular_headers => true
    # *************** - React Native Pods ************** #
    pod 'RCTTypeSafety', :path => "../../consumer_apps_rn/node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-Core', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-CoreModules', :path => '../../consumer_apps_rn/node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../../consumer_apps_rn/node_modules/react-native/'


target 'xxxxTests' do
        inherit! :search_paths
        # Pods for testing
    end
    target 'XXXNotificationService' do
        inherit! :search_paths
        pod 'AirshipExtensions', '~>14.0', :modular_headers => true
    end
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
```

**Comment by marc-scig** [comment]
@srinadh-k OK, I see. The indentation is a bit confusing. Ultimately what I mean though is that your notification service is its own target, not a "subtarget" of your app. You'll probably have an easier time if you break it out into its own top level definition.

**Comment by srinadh-k** [comment]
@marc-scig  you mean to keep it our side top-level as like below 

```
target 'xxxxxx' do

    pod 'Airship', '~>14.0', :modular_headers => true
    # *************** - React Native Pods ************** #
    pod 'RCTTypeSafety', :path => "../../consumer_apps_rn/node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-Core', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-CoreModules', :path => '../../consumer_apps_rn/node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../../consumer_apps_rn/node_modules/react-native/'


target 'xxxxTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
target 'XXXNotificationService' do
    inherit! :search_paths
    pod 'AirshipExtensions', '~>14.0', :modular_headers => true
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
```

**Comment by marc-scig** [comment]
@srinadh-k This just changes the indentation. There is no `end` beneath the line `pod 'React-Core/DevSupport', :path => '../../consumer_apps_rn/node_modules/react-native/'` to finish the definition of `'xxxxxx` before moving on. Compare with the definitions of `xxxxTests` and `XXXNotificationService`.

**Comment by srinadh-k** [comment]
@marc-scig  now please check it below. still the same issue.

```

target 'xxxxxx' do

    pod 'Airship', '~>14.0', :modular_headers => true
    # *************** - React Native Pods ************** #
    pod 'RCTTypeSafety', :path => "../../consumer_apps_rn/node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-Core', :path => '../../consumer_apps_rn/node_modules/react-native/'
    pod 'React-CoreModules', :path => '../../consumer_apps_rn/node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../../consumer_apps_rn/node_modules/react-native/'
end

target 'xxxxTests' do
        inherit! :search_paths
        # Pods for testing
end


target 'XXXNotificationService' do
    inherit! :search_paths
    pod 'AirshipExtensions', '~>14.0', :modular_headers => true
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
```

**Comment by marc-scig** [comment]
That looks pretty normal to me, and I still can't reproduce this issue with an app of my own either way, so I'm not sure what to make of it. It really would be best to contact support from here. We can go back and forth on how your project is set up ad infinitum, but this is primarily a channel for discussing SDK bug reports, and I'm not convinced there's anything wrong with our SDK or podspecs based on my own testing. Support engineers will be better equipped to walk you through the process of narrowing down what your problem is, providing sample code in less public setting, etc.

**Comment by srinadh-k** [comment]
@marc-scig  Sure. Thanks for your help today. we raise a support ticket.

**Comment by sridharsaminathn** [comment]
Open your .xcworkspace in Xcode and Make this settings.

<img width="810" alt="Screenshot 2023-07-25 at 8 27 54 PM" src="https://github.com/urbanairship/ios-library/assets/57259375/dfcaa6fb-52df-4a77-a6ea-f68b1cb41311">
