### ISSUE TITLE
launchOption returns nil when clicking interactive buttons on Rich Push Notification

### ISSUE THREAD

**Issue by iosmagesh18** [urbanairship/ios-library#260]
I'm using rich push notification with pre-defined interactive buttons on my iOS application.

It all works well when the app is in background mode, with my code inside -- **(void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void(^)())completionHandler** is being called as expected.

However, if the app is not running, clicking on one of the interactive buttons will make the app open, but the call to - **(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions** is being return the launchOptions value as nil.

It works as expected if I click the notification itself, instead of any of the interactive buttons.

I am using Xcode 11.3.1, iOS 13.6.1, and Airship 14.0.0.

Any idea what is going on here? Any help would be really appreciated.

Regards,
Magesh M

# Preliminary Info

### What Airship dependencies are you using?
Airship 14.0.0

### What are the versions of any relevant development tools you are using?
 Xcode 11.3.1, iOS 13.6.1

# Report

### What unexpected behavior are you seeing?
launchOptions are nil after using pre-defined interactive buttons on Push Notification

**Comment by marc-scig** [comment]
Hey @iosmagesh18,

I wouldn't necessarily expect the launch options to be non-nil in this case. Foregrounding notification action buttons should trigger a UNNotificationResponse, which you can either listen for directly from the UNNotificationCenter or through the `UAPushNotificationDelegate` protocol.

**Comment by iosmagesh18** [comment]
Thanks for your response @marc-scig 

Following points are my understanding based on your response, correct me if I am wrong.

1. If the app is not running, the launch options will be nil when clicking the interactive button.
2. If point #1 is yes, please confirm that this is expected behaviour by Airship SDK?

Please note that we are changing the root view controller based on the launch option in our application.

We assumed that launch option will not be returned nil when clicking the interactive buttons.

Also, we’ve used the below property for enabling pre-defined interactive button lists available in this [link](https://docs.airship.com/reference/integration/built-in-interactive-notifications/) so please confirm that any configuration to be needed for enabling pre-defined interactive buttons apart from this property.

[UAirship push].requireAuthorizationForDefaultCategories = YES;

Kindly advise. Thanks!

Regards,
Magesh M

**Comment by ralepinski** [comment]
@iosmagesh18 we do not control the launch options for iOS, that is an OS behavior. We try to make it easier by providing things like push protocol so you have consistent callbacks.

**Comment by iosmagesh18** [comment]
Thanks for your response @ralepinski
