### ISSUE TITLE
Built-In Interactive Notification button doesn't display when the user sends a rich push notification

### ISSUE THREAD

**Issue by iosmagesh18** [urbanairship/ios-library#261]
Hi,

The interactive buttons are not showing up when long-press the rich push notification.

We have used the below property for enabling the interactive buttons which are available in this [link](https://docs.airship.com/reference/integration/built-in-interactive-notifications/) but we couldn't see it in the notification.

Please confirm if we have missed any configuration for enabling the interactive buttons apart from this property.

[UAirship push].requireAuthorizationForDefaultCategories = YES;

Regards,
Magesh M

# Preliminary Info

### What Airship dependencies are you using?
Airship 14.0.0

### What are the versions of any relevant development tools you are using?
Xcode 11.3.1, iOS 13.6.1

# Report

### What unexpected behavior are you seeing?
Interactive buttons are not displayed when long-press the rich  push notification

### What is the expected behavior?
Interactive buttons should be displayed when long-press the rich push notifications

**Comment by marc-scig** [comment]
Hi @iosmagesh18,

This is probably a better question for support. As far as I can tell the feature is working properly, but they can walk you through the process of troubleshooting your problem.
