### ISSUE TITLE
Landing page view keeps on displaying on subsequent app launches

### ISSUE THREAD

**Issue by iosmagesh18** [urbanairship/ios-library#263]
I'm using rich push notification with pre-defined interactive buttons on my iOS application.

The landing page view keeps on displaying on subsequent app launches after clicking 'X' in it and also notices the landing page view stays over the Home page after killing the app and relaunching it.

In some scenarios, the landing page view appears again for some time on app relaunch and then disappears by itself.

Kindly advise. Thanks!

### What Airship dependencies are you using?
Airship 14.1.2

### What are the versions of any relevant development tools you are using?
Xcode 12.0.1, iOS 12.4.8 & iOS 14.0

### What unexpected behavior are you seeing?
The landing page view keeps on displaying on subsequent app launches.

### What is the expected behavior?
The landing page view should disappear after clicking 'X' in it.

**Comment by marc-scig** [comment]
@iosmagesh18 how are you scheduling the landing page? I just sent myself a push with a landing page action in the composer, and it behaves as expected (no subsequent displays after dismissing).
