### ISSUE TITLE
SPM failure

### ISSUE THREAD

**Issue by drw86312** [urbanairship/ios-library#264]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
14.1.0

### What are the versions of any relevant development tools you are using?
Xcode 11.7

# Report

### What unexpected behavior are you seeing?
Package resolution failure

### What is the expected behavior?
Package resolution success

### What are the steps to reproduce the unexpected behavior?
I have followed the steps outlined in documentation for including Airship using Swift Package Manager

### Do you have logging for the issue?
<img width="738" alt="Screen Shot 2020-10-28 at 10 10 53 PM" src="https://user-images.githubusercontent.com/5992668/97521478-a11a9100-196b-11eb-8a78-ae06d58c2dfc.png">

**Comment by marc-scig** [comment]
Hi @drw86312,

SDK 14.1.x requires Xcode 12 due to new symbols added in iOS 14. If you're unable to upgrade your dev tools for any reason, the most recent version compatible with Xcode 11 is 14.0.1.

**Comment by drw86312** [comment]
Ok, thank you @marc-scig
