### ISSUE TITLE
iOS Airship SDK: Use of undeclared identifier 'UNAuthorizationStatusEphemeral'

### ISSUE THREAD

**Issue by alu0100207385** [urbanairship/ios-library#265]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
pod 'Airship'
v14.1.3

### What are the versions of any relevant development tools you are using?

IDE: Version 11.3.1 (11C505)

# Report

### What unexpected behavior are you seeing?
I got an error in Pods > Airship > Core > UAAPNSRegistration.m > -uaStatus (line 72):
```
Semantic issue
Use of undeclared identifier 'UNAuthorizationStatusEphemeral'; did you mean 'UAAuthorizationStatusEphemeral'?
Replace 'UNAuthorizationStatusEphemeral' with 'UAAuthorizationStatusEphemeral'
```

### What is the expected behavior?
The project should compile.

### What are the steps to reproduce the unexpected behavior?
1. Updates the Airship pod dependency from pod 'UrbanAirship-iOS-SDK', '12.1.2' to pod 'Airship'.

2.Executes $ pod install.

3. Tries to compile and execute in a device/emulator.

### Do you have logging for the issue?
--

Any suggestion? Thanks in advance.

**Comment by rlepinski** [comment]
You need Xcode 12+. Ill fix the README now to reflect that requirement
