### ISSUE TITLE
Improve URL handling in Airship front end, please 

### ISSUE THREAD

**Issue by TorstenKaufmann** [urbanairship/ios-library#267]
### What Airship dependencies are you using?

Airship iOS 14.1.3
### What are the versions of any relevant development tools you are using?

Xcode 12.3  (12C33)
SwiftPackageManager 5.3

# Report

### What unexpected behavior are you seeing?

Customer creates a `Message` for an app of i.e. type Push Notification in Airship front end (https://go.urbanairship.com)
Adding a Deep Link action with a url like `https://<host>/landingpage/19156755 /webview` will not fail if the url entered is not valid. **Note the space after the landing page identifier (19156755)**
### What is the expected behavior?

A basic formal url validation while creating Messages to prevent unexpected behaviour on the message receiving side.
### What are the steps to reproduce the unexpected behavior?

Create a Message containing a deep link url with i.e. spaces. 
### Do you have logging for the issue?

No logging, but implementing a `UADeepLinkDelegate`  will show that `func receivedDeepLink(_ url: URL, completionHandler: @escaping () -> ())` is not called. 
Instead `UAPushNotificationDelegate's` `func receivedNotificationResponse(_ notificationResponse: UANotificationResponse, completionHandler: @escaping () -> Void)`  is assumed to be responsible by the framework.

**Comment by marc-scig** [comment]
Hi @TorstenKaufmann,

Thanks for letting us know. This is outside the scope of what we can do in the SDK, of course, but I'll pass it on to the web team.
