### ISSUE TITLE
Category Method Name Clashes NSString+UAURLEncoding.m

### ISSUE THREAD

**Issue by josueruiz7** [urbanairship/ios-library#269]
Hello folks,

I am implementing Airship on my ios project, but I realized that the category names `urlDecodedString` and `urlEncodedString` are clashing with other third party library.

Can you rename these category method names?

Thanks

**Comment by marc-scig** [comment]
Hi @josueruiz7,

Thanks for letting us know. We follow semantic versioning, so any name change would require a major update. What's the other third party library, and how are you packaging the Airship SDK (Coocapods, SPM, etc)? I'm wondering if there's a potential workaround in the meanwhile, or if the collision can be treated as benign. If the two implementations are functionally identical, it's technically undefined which will be invoked, but the result should be the same.

**Comment by marc-scig** [comment]
Closing this for now, but feel free to reopen it if it's causing problems for you. We'll likely be addressing this in a future release.

**Comment by josueruiz7** [comment]
Sorry for the late reply but we found a workaround updating the other thirdparty library, the category extension had the exact same method names with different functionalitiy each function, that was causing issues for us.
Will be good if it can be addressed in the future to prevent any possible issues. 
@marc-scig thank you.
