### ISSUE TITLE
Undefined Symbols - SPM

### ISSUE THREAD

**Issue by MrSkwiggs** [urbanairship/ios-library#270]
I've been having some issues setting up Airship in our codebase. I've added it as a Swift Package, and ran into issues as described in #259. I was however able to get my imports to work for both the main App target as well as for the notification extension. So all was well, until I then ran into build errors due to linker.

# Preliminary Info

### What Airship dependencies are you using?
Airship 14.2.3, loaded from SPM

### What are the versions of any relevant development tools you are using?
XCode 12.4

# Report

### What unexpected behavior are you seeing?
Errors when building:
```
Undefined symbols for architecture x86_64:
  "_nw_path_get_status", referenced from:
      ___24-[UANetworkMonitor init]_block_invoke in AirshipCore.o
  "_nw_path_monitor_set_queue", referenced from:
      -[UANetworkMonitor init] in AirshipCore.o
  "_nw_path_monitor_set_update_handler", referenced from:
      -[UANetworkMonitor init] in AirshipCore.o
  "_nw_path_monitor_create", referenced from:
      -[UANetworkMonitor init] in AirshipCore.o
  "_nw_path_monitor_start", referenced from:
      -[UANetworkMonitor init] in AirshipCore.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### What is the expected behavior?
Builds without errors

### What are the steps to reproduce the unexpected behavior?
Follow Quick Start guide from Airship website

### Do you have logging for the issue?
N/A

**Comment by MrSkwiggs** [comment]
Quick update on this: that happened when trying to run on simulator, but for real devices the issue persists, with the only difference being that, the arch mentioned in the error message is `arm64` instead of `x86_64`

**Comment by rlepinski** [comment]
Could you try to add `Network.framework` to your app to see if it resolves the issue?

**Comment by MrSkwiggs** [comment]
Well, that did it :d Thanks!

**Comment by marc-scig** [comment]
@MrSkwiggs is your deployment target 11.x by any chance? I think we may just be missing either some conditional compilation directives and/or a Network.framework dependency in the package definition.

**Comment by MrSkwiggs** [comment]
@marc-scig yep, iOS 11.0

**Comment by marc-scig** [comment]
@MrSkwiggs this will be fixed in an upcoming patch. I'm closing the issue for now but let us know if you have other problems.
