### ISSUE TITLE
AirshipLib.h isn't generated when built with Carthage

### ISSUE THREAD

**Issue by badeleux** [urbanairship/ios-library#277]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

14.3.1

### What are the versions of any relevant development tools you are using?
carthage 0.37.0

# Report

### What unexpected behavior are you seeing?
App cannot be properly built as Bridging header is not available (AirshipLib.h is empty)

### What is the expected behavior?
AirshipLib.h should be populated with public headers

### What are the steps to reproduce the unexpected behavior?
`carthage update --platform iOS --use-xcframeworks`
Build the app from xcode and try to use UAirship.push()

### Do you have logging for the issue?
<img width="377" alt="Screenshot 2021-04-21 at 12 53 42" src="https://user-images.githubusercontent.com/1708299/115549612-22166d80-a2a9-11eb-87a7-1fda5c7c480e.png">
<img width="763" alt="Screenshot 2021-04-21 at 12 53 31" src="https://user-images.githubusercontent.com/1708299/115549618-23e03100-a2a9-11eb-9315-1ec09f709ea6.png">

**Comment by fchauvin** [comment]
Not sure if this is entirely related, however we are seeing an issue as well with AirshipLib.h when upgrading to version 14.3.1, also using Carthage. It seems that `AirshipLib.h` is trying to import `NSOperationQueue+UAAdditions.h`, which does not exist in the codebase anymore as far as I can tell.

![Screen Shot 2021-04-21 at 12 39 41 PM](https://user-images.githubusercontent.com/1099119/115590155-a7485500-a29e-11eb-98fe-906cb14c7b12.png)

**Comment by rlepinski** [comment]
@fchauvin I think you might have a caching issue? This commit removed that file and the reference from AirshipLib.h https://github.com/urbanairship/ios-library/commit/78a9222353e0391362a4a22f144fb95056c7fe78

@badeleux We will look into

**Comment by fchauvin** [comment]
@rlepinski Thanks for the quick response. This issue began showing up when we built airship 14.3.1 via carthage for Xcode 12.5, previously we have been using 14.3.1 on Xcode 12.1 successfully without this issue. I can open a separate ticket if needed.

**Comment by rlepinski** [comment]
@fchauvin Yes, please open another issue. The first thing Ill suggest is wiping the carthage folder and rebuilding though

**Comment by oristanovic** [comment]
@badeleux I don't reproduce the issue on my side. Could you share your Cartfile and if possible a sample project that has the issue?

**Comment by prgorasiya** [comment]
I am also facing the same issue on my side, when I upgraded Airship SDK to 14.3.1 using Carthage.
I also cleared out caches, DerivedData but nothing helped.
Eventually I had to go back to previous version to make it work.

**Comment by oristanovic** [comment]
@prgorasiya We're looking into it. What is the version you were using before updating? What Xcode version are you using?

**Comment by rlepinski** [comment]
@prgorasiya also if you could share your cartfile that would be helpful

**Comment by prgorasiya** [comment]
heres is my Cartfile, I was using V14.2.2 before updating and using Xcode V12.4 at the moment.
```
github "Alamofire/Alamofire" ~> 4.7
github "alexlittlejohn/ALCameraViewController"
github "andreamazz/BubbleTransition"
github "socketio/socket.io-client-swift" ~> 15.2.0
binary "https://api.mapbox.com/downloads/v2/carthage/mobile-maps/mapbox-ios-sdk-dynamic.json" ~> 6.3.0
github "mapbox/mapbox-events-ios" ~> 0.10.5
github "kaandedeoglu/KDCircularProgress"
github "tristanhimmelman/ObjectMapper" == 4.1.0
github "DeclarativeHub/Bond"
github "aladinway/TransitionButton"
github "CosmicMind/Motion"
github "urbanairship/ios-library" == 14.2.2
github "bugsnag/bugsnag-cocoa"
github "airbnb/lottie-ios" "master"
```

**Comment by oristanovic** [comment]
@prgorasiya Are you still experiencing the issue with the latest SDK version (14.4.0) ?

**Comment by prgorasiya** [comment]
No its working fine with latest SDK, thank you.
