### ISSUE TITLE
Swift Package Manager warning about un processed files.

### ISSUE THREAD

**Issue by hasanPrestoq** [urbanairship/ios-library#279]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Airsship 14.4.1
### What are the versions of any relevant development tools you are using?

Xcode 12.5
# Report

### What unexpected behavior are you seeing?

found 18 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
.../SourcePackages/checkouts/ios-library/Airship/AirshipChat/Tests/AirshipChatTests.swift
### What is the expected behavior?

No Test related files show up in the delivered framework context.
### What are the steps to reproduce the unexpected behavior?

Add Airship framework to application via Swift Package manager.
### Do you have logging for the issue?

This is a build time issue, so no run time logs are relevant.

**Comment by rlepinski** [comment]
Thanks for the report, we will look into it.

**Comment by rlepinski** [comment]
Should be fixed in 14.5.1
