### ISSUE TITLE
Push Airship launch my app in background.

### ISSUE THREAD

**Issue by santiagoperez96** [urbanairship/ios-library#283]
When I send push notifications my app launches automatically in the background ...

Whether I allow push or not exactly the same thing happens.

Any help on this?

**Comment by rlepinski** [comment]
By launches you just mean wakes up in the background? Are you sending a notification with `content-available` ?

**Comment by santiagoperez96** [comment]
_By launches you just mean wakes up in the background?_
- Yes, my app wakes up in the background.

Are you sending a notification with content-available ?
- No, the property content-available is nil in objective-c

**Comment by santiagoperez96** [comment]
I've been checking the content-available of the push. When I send an in-App message + Push notification the content-available is 1.

How can I control this case so that the app does not open in the background?

**Comment by rlepinski** [comment]
IAM Requires sending a content-available push to work properly. I dont believe you can override that flag if you use an IAM. You might be more interested in not using IAM and instead using In-App Automation which is not tied to a push.

**Comment by santiagoperez96** [comment]
Okay, I got it. Thank you so much.

But in-app messages can be disabled right?

I have disabled them. With the app open I no longer receive it thanks to this statement:
 [[UAInAppAutomation shared] setEnabled: NO];

But with the app in the background or not started, I send an in-app message to the app wake up again!

How do I disable in-app messages then ...

**Comment by rlepinski** [comment]
The content-available is sent server side when defining the push. Just dont include IAM when sending a push.

**Comment by santiagoperez96** [comment]
I understand but if I want to send an in-App message, will I always have this problem?

There is no way to disable in-App messages when I don't have the app open?

**Comment by rlepinski** [comment]
Yes, the only way IAM works is if you launch the app without opening the notification. That is achieved through a content-available pushes. You should consider IAA - https://docs.airship.com/guides/messaging/user-guide/in-app-automation/about/ instead which does not use push to deliver the content.
