### ISSUE TITLE
Unable to compile for Xcode 13 beta 3

### ISSUE THREAD

**Issue by lennartkerkvliet** [urbanairship/ios-library#286]
# Preliminary Info

### What Airship dependencies are you using?
AirshipCore
AirshipAutomation

### What are the versions of any relevant development tools you are using?
14.5.2

# Report

### What unexpected behavior are you seeing?

Xcode 13 beta 3 introduces a breaking change related to API unavailable for iOS extensions: https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes

### What is the expected behavior?

Airship should be able to compile

### What are the steps to reproduce the unexpected behavior?

Add Airship as a dependency in SPM on Xcode 13 beta 3

### Do you have logging for the issue?
-

**Comment by marc-scig** [comment]
Hi @lennartkerkvliet,

Thanks for the report. We'll take a look at this and get it fixed as soon as we can.

**Comment by marc-scig** [comment]
@lennartkerkvliet @amanssharma

We just published a minor update (14.6.0) that includes a fix for this issue. Thanks again for the feedback, and let us know if you have any other issues with the beta.
