### ISSUE TITLE
On iOS 15, Airship In-App Automation messages are not displayed after the system keypad is shown

### ISSUE THREAD

**Issue by kavitha1809** [urbanairship/ios-library#288]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
Airship v 14.6.1 

### What are the versions of any relevant development tools you are using?
Xcode 13 Beta 5

# Report

### What unexpected behavior are you seeing?
In-App Automation messages are not displayed after the system keypad is shown

### What is the expected behavior?
In-App Automation messages should be displayed after the system keypad is shown

### What are the steps to reproduce the unexpected behavior?
Steps to reproduce:
1. Run and install the attached "TestAirship" app via Xcode on  iOS device/simulator
2. Tap on the “Enter text here” text field
3. Now tap on the “Show Hello World” button.

### Do you have logging for the issue?
Sample application "TestAirship" is attached.

More info:
1. On skipping step 2, the In-App Automation message is displayed
2. The below delegate method of "UAInAppMessagingDelegate" is invoked but message UI is not rendered
- (void)messageWillBeDisplayed:(UAInAppMessage *)message scheduleID:(NSString *)scheduleID;
3. This issue is NOT observed on iOS 14 and below OS's

Notes on the app:
1. Every time fresh install the app
2. In the "AirshipConfig.plist"; add your Airship keys (if required); for now set my test keys and secrets
3. App is compatible with Xcode 12 and Xcode 13 beta

**Comment by marc-scig** [comment]
Hi @kavitha1809,

Thanks for the feedback, we'll check it out. Did you have a link to the test app you were mentioning?

**Comment by kavitha1809** [comment]
Hi,

Attached the sample "TestAirship” app.

Message style:  Modal

**Comment by kavitha1809** [comment]
Hi, Any updates on this? Is it an Apple bug?

**Comment by rohitkmodi** [comment]
Hello Team,

I am getting this error for xcode13
Airship/AirshipMessageCenter/Source/Display/UAMessageCenterSplitViewController.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Airship' from project 'Pods')

**Comment by kavitha1809** [comment]
The sample shared is TestAirship, and Airship is not integrated via pod.

**Comment by rlepinski** [comment]
@kavitha1809 It appears that the keyboard is now in its own scene. We display IAA in the last added scene by default. We will most likely just switch to using the first scene instead of the last. That seems to fix. 

Ill try to get a patch out this week.

**Comment by kavitha1809** [comment]
Is the fix available in new release v14.6.2?

**Comment by rlepinski** [comment]
@kavitha1809 yep fixed in 14.6.2
