### ISSUE TITLE
iOS 14 (and/or 15) Minimum Deployment Target Warnings from XIB Files

### ISSUE THREAD

**Issue by RGG-jayoung** [urbanairship/ios-library#289]
# Preliminary Info

### What Airship dependencies are you using?
Airship 14.6.1

### What are the versions of any relevant development tools you are using?
Xcode 12.5, Xcode 13 Beta 5

# Report

### What unexpected behavior are you seeing?
For the 2 XIB files, were seeing warnings on minimum deployment target. We are current supporting iOS 14 & 15 using cocoa pods as a dependency manager. When updating, we now see these warnings:

```swift
UAInAppMessageHTMLViewController.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
```

```swift
UADefaultMessageCenterMessageViewController.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
```

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/53495188/131409214-b8151a0d-4f3e-4894-9d0c-b19ebe766c03.png">

### What is the expected behavior?
Xib file should not produce minimum deployment target warning.

### What are the steps to reproduce the unexpected behavior?
1. Set up an Xcode project with iOS 14 (15 is optional). 
2. Integrate an Xcode project with Airship 14.6.1 SDK.
3. Build and run the project to see the warnings.

### Do you have logging for the issue?
No, just the copied content:

```
/Pods/Airship/Airship/AirshipMessageCenter/Resources/UADefaultMessageCenterMessageViewController.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
```

```
/Pods/Airship/Airship/AirshipAutomation/Resources/UAInAppMessageHTMLViewController.xib:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
```

**Comment by rlepinski** [comment]
Thanks for the report, we will look into it

**Comment by rlepinski** [comment]
The reason why we have to set an explicit version instead of deployment target is due to the xibs containing a WKWebView - https://stackoverflow.com/questions/46221577/xcode-9-gm-wkwebview-nscoding-support-was-broken-in-previous-versions

If we set deployment target instead of an explicit version, app that try to include our SDK for iOS 11+, but still keep min deployment target to 9+ will break with the above error.

We will look into reworking or xibs (or event removing them) in an upcoming release.
