### ISSUE TITLE
Release 14.7.0 has breaking changes for Xcode 12

### ISSUE THREAD

**Issue by joshuapoq** [urbanairship/ios-library#291]
# Preliminary Info

### What Airship dependencies are you using?
`14.7.0` (updating via SPM from `14.6.1`)

### What are the versions of any relevant development tools you are using?
`Xcode 12.5.1`

# Report

### What unexpected behavior are you seeing?
Builds no longer compile with the following errors:
```
❌  /.../SourcePackages/checkouts/ios-library/Airship/AirshipCore/Source/Internal/UATextInputNotificationAction.m:74:9: unknown type name 'UNNotificationActionIcon'; did you mean 'UANotificationActionIcon'?

        UNNotificationActionIcon *icon;
        ^

❌  /.../SourcePackages/checkouts/ios-library/Airship/AirshipCore/Source/Internal/UATextInputNotificationAction.m:77:21: unknown receiver 'UNNotificationActionIcon'; did you mean 'UANotificationActionIcon'?

            icon = [UNNotificationActionIcon iconWithSystemImageName:self.icon.systemImageName];
           ^

❌  /.../SourcePackages/checkouts/ios-library/Airship/AirshipCore/Source/Internal/UATextInputNotificationAction.m:79:21: unknown receiver 'UNNotificationActionIcon'; did you mean 'UANotificationActionIcon'?

            icon = [UNNotificationActionIcon iconWithTemplateImageName:self.icon.templateImageName];
           ^

❌  /.../SourcePackages/checkouts/ios-library/Airship/AirshipCore/Source/Internal/UATextInputNotificationAction.m:82:47: no known class method for selector 'actionWithIdentifier:title:options:icon:textInputButtonTitle:textInputPlaceholder:'

        return [UNTextInputNotificationAction actionWithIdentifier:self.identifier
           ^
```

### What is the expected behavior?

The build should compile. Semantic versioning should be followed.

### What are the steps to reproduce the unexpected behavior?

1. Set up an Xcode project (we target iOS 13+).
2. Add Airship via SPM from `14.0`.
3. Attempt to compile the project.

**Comment by rlepinski** [comment]
It requires Xcode 13.0. It basically the same release as 14.6.2 just with added iOS 15 fields. 

https://github.com/urbanairship/ios-library/releases/tag/14.7.0

We did this release for people who want to target iOS 15 features but without having to deal with all the breaking changes we introduced in SDK 15.0.

**Comment by joshuapoq** [comment]
@rlepinski I understand that. But this should have been released as a major version. This breaks SPM semantic versioning requirements.

**Comment by rlepinski** [comment]
@joshuapoq  Semantic versioning is around API changes not the build tools.

https://developer.apple.com/documentation/swift_packages/version

Sorry for trouble, we will update our examples to specify a version.
