### ISSUE TITLE
Updating from 14.6.1 to 14.7.0 fails to compile

### ISSUE THREAD

**Issue by steprescott** [urbanairship/ios-library#292]
# Preliminary Info

### What Airship dependencies are you using?
Updating from 14.6.1 to 14.7.0

### What are the versions of any relevant development tools you are using?
- Xcode 12.5 
- iOS 14

# Report

### What unexpected behaviour are you seeing?
`Unknown receiver 'UNNotificationActionIcon'; did you mean 'UANotificationActionIcon'?` in `ios-library/Airship/AirshipCore/Source/Internal/UATextInputNotificationAction.m:77:21`

### What is the expected behaviour?
For the framework to compile

### What are the steps to reproduce the unexpected behavior?
Update sample app from 14.6.1 to 14.7.0 with no source changes.

### Do you have logging for the issue?
N/A

**Comment by oristanovic** [comment]
It requires Xcode 13.0. It basically the same release as 14.6.2 just with added iOS 15 fields.

https://github.com/urbanairship/ios-library/releases/tag/14.7.0

We did this release for people who want to target iOS 15 features but without having to deal with all the breaking changes we introduced in SDK 15.0.
