### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by fsgpino** [urbanairship/ios-library#295]
I think it is a mistake.

https://github.com/urbanairship/ios-library/blob/3b0ac9d876ea227a0837eec220ab76423f5c1622/Airship/AirshipCore/Source/EventStore.swift#L18-L19

**Comment by joshuapoq** [comment]
Good catch, it should be `apples`!

**Comment by rlepinski** [comment]
🤦‍♂️ 

I guess we will be seeing a 16.0.1 release in the near future.
