### ISSUE TITLE
Feature Request: API to fetch current attributes on device

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [urbanairship/ios-library#296]
# Preliminary Info

### What Airship dependencies are you using?
16.0.0

### What are the versions of any relevant development tools you are using?
Xcode 13.0 public, iOS 13.x-15.y

# Report

### What unexpected behavior are you seeing?
There is an API to set and another to remove attributes by key name from a channel, but no API to GET the current ones.

### What is the expected behavior?
There should be an API to GET the assigned attributes on a local device. This could either be an async or a sync method to provided on the channel, just like 'getPendingMutations' --> getCurrentMutations or getCurrentAttributes. 

### What are the steps to reproduce the unexpected behavior?
Feature Request - scenario, dynamically fetch content from the server that includes attribute keys, user picks ones they want. I don't want to iterate through keys not selected and call the remove attribute mechanism.

It would be best to be able to query locally what ones exist already, and then optimally set/remove for just the items that change.

### Do you have logging for the issue?
Not Applicable

**Comment by rlepinski** [comment]
`getPendingMutations` is an internal method only, probably want to avoid it. It's made public but undocumented for use in other airship modules. Its only giving you the mutations we have not yet sent up.

We do not have any apis to expose attributes at the moment but can file a product feedback request.

**Comment by SwiftNativeDeveloper** [comment]
Thanks @rlepinski, is there any side effect in the backend API if I were to try and remove an attribute that doesn't currently exist on that device? If not, I can work around for now but that feedback request for new capability would be great!

**Comment by rlepinski** [comment]
You should not have any issues with removing attributes that don't exist on a device

**Comment by SwiftNativeDeveloper** [comment]
@msuslak hey, how can I get in touch with you outside of GitHub to share more details?

**Comment by msuslak** [comment]
@SwiftNativeDeveloper feel free to shoot me an email at meghan@airship.com
