### ISSUE TITLE
Airship iOS SDK 16.0.2 doesn't send notifications and crash on Android [React Native]

### ISSUE THREAD

**Issue by raboija** [urbanairship/ios-library#302]
### What Airship dependencies are you using?
Airship iOS SDK 16.0.2 
urbanairship-react-native:  13.0.1

After upgrading to the latest Airship iOS SDK and urbanairship-react-native,  we started getting _'Airship/AirshipLib.h' file not found_ error

That failed the app build. Our workaround was to use `@import AirshipKit`;  instead 

and add this block of code to AppDelegate:

```
[UAirship takeOff:<#(UAConfig * _Nullable)#> launchOptions:<#(NSDictionary<UIApplicationLaunchOptionsKey,id> * _Nullable)#>]
```

Now the app builds successfully, but doesn't receive notifications.
urbanairship-react-native:  13.0.1 also crashes on android upon update

We were using Airship iOS SDK 14 for a long time and was working perfectly with the same original import, only upgrading to the latest version caused these issues. Did anyone else experience this or have a suggestion? Thank you

<img width="671" alt="Screen Shot 2021-11-05 at 10 32 22 AM" src="https://user-images.githubusercontent.com/47260800/140539135-ec014f62-b4ca-45c2-88f5-276651c8c8e4.png">

**Comment by rlepinski** [comment]
Are you using the react-native plugin or implementing it yourself? Do you have logs? Sample code would be nice to see whats going on.

Did you see the migration guide? https://github.com/urbanairship/ios-library/blob/main/Documentation/Migration/migration-guide-14-16.md

**Comment by rlepinski** [comment]
If you are using our react plugin you should not have to make any direct calls to Airship, it should be handled for you. Not sure why you need to call takeOff

**Comment by raboija** [comment]
Because we have 3 environments, that's why we configured it in AppDelegate we did it manually and was working well until Airship iOS SDK 14.X.

**Comment by rlepinski** [comment]
Could you provide logs and your app delegate code? What notifications are not being received? 

Please open up a react-native issue for your android crash. https://github.com/urbanairship/react-native-module. We prefer to deal with 1 issue per github issue.

**Comment by rlepinski** [comment]
Closing, if you have more info please reopen in the react-native repo
