### ISSUE TITLE
RegistrationDelegate method are not call

### ISSUE THREAD

**Issue by ota-motomi** [urbanairship/ios-library#304]
# Preliminary Info

### What Airship dependencies are you using?

Version 16.1.0

### What are the versions of any relevant development tools you are using?

Xcode 13.0, using SPM
Tested on iPhoneXR OS 14 and iPhone 13 OS 15

# Report

### What unexpected behavior are you seeing?

Migrating from v14 to v16:

`RegistrationDelegate` method is not called when the user allow push notification, it worked on v14 when using `UARegistrationDelegate`. 

Here is the code used on v16:

```
class UrbanAirshipPushNotificationService: NSObject, PushNotificationService {
    
    private weak var delegate: RemoteNotificationDelegate?
    
    init(launchOptions: [UIApplication.LaunchOptionsKey: Any]?) {
        let config = Config.default()
#if BETA
        config.inProduction = true
        config.productionAppKey = AppKeys().urbanAirshipAppKeyBeta
        config.productionAppSecret = AppKeys().urbanAirshipAppSecretBeta
#elseif RELEASE
        config.inProduction = true
        config.productionAppKey = AppKeys().urbanAirshipAppKeyProduction
        config.productionAppSecret = AppKeys().urbanAirshipAppSecretProduction
#else
        config.inProduction = false
        config.developmentAppKey = AppKeys().urbanAirshipAppKeyDevelopment
        config.developmentAppSecret = AppKeys().urbanAirshipAppSecretDevelopment
#endif
        Airship.takeOff(config, launchOptions: launchOptions)
        Airship.push.autobadgeEnabled = true
        Airship.push.backgroundPushNotificationsEnabled = true
        super.init()
        Airship.push.registrationDelegate = self
        Airship.push.pushNotificationDelegate = self
        Airship.shared.deepLinkDelegate = self
}

extension UrbanAirshipPushNotificationService: RegistrationDelegate {
    func notificationRegistrationFinished( withAuthorizedSettings authorizedSettings: UAAuthorizedNotificationSettings, status: UAAuthorizationStatus) {
        delegate?.authorizationStatusUpdated(status.asUNAuthorizationStatus())
    }
}
```

### What is the expected behavior?

`notificationRegistrationFinished` would be called after notification permission is given

### What are the steps to reproduce the unexpected behavior?

After notification permission appear, press the allow or don't allow.

### Do you have logging for the issue?

none

**Comment by oristanovic** [comment]
Thanks for the report, we will look into it

**Comment by oristanovic** [comment]
You're using the tvOS callback, this is the correct one
`optional func notificationRegistrationFinished(
            withAuthorizedSettings authorizedSettings: UAAuthorizedNotificationSettings,
            categories: Set<UNNotificationCategory>,
            status: UAAuthorizationStatus`

**Comment by ota-motomi** [comment]
thank you that works!
