### ISSUE TITLE
Contact is not updated in Airship 16.1.0 on iOS

### ISSUE THREAD

**Issue by simonox** [urbanairship/ios-library#305]
# Preliminary Info

### What Airship dependencies are you using?
Airship 16.1.0 on iOS

### What are the versions of any relevant development tools you are using?
Xcode Version 13.1 with SPM

# Report

The the named user API is  now deprecated. So I try to switch to the new contact API (Airship.contact.identify).

After a user log out and logs in, I want to update the identity with the new customer number.

```
Airship.shared.privacyManager.enableFeatures(.contacts)
Airship.contact.identify(currentCustomerNumber)
```

### What unexpected behavior are you seeing?

I get a warning:
```           
 [Airship] [D] AirshipCore/Contact.swift logOperationResult(operation:response:error:) [Line 647] Contact update for operation: ContactOperation(type: AirshipCore.OperationType.update, payload: Optional(AirshipCore.UpdatePayload(tagUpdates: nil, attrubuteUpdates: Optional([])))) failed with error: Error Domain=com.urbanairship.error Code=1 "Both tags & attributes are empty" UserInfo={NSLocalizedDescription=Both tags & attributes are empty}
```
Contact is not updated in Airship.

### What is the expected behavior?

Contact is updated in Airship. I might also see an HTTP request for this in my HTTP debugger.

**Comment by simonox** [comment]
I tried to migrate this "old" code to the new contacts API:

```
        UAirship.shared().privacyManager.enable(.contacts)
        UAirship.namedUser().identifier = currentCustomerNumber
        UAirship.namedUser().forceUpdate()
```

The old code is working.

**Comment by rlepinski** [comment]
`Airship.contact.identify(currentCustomerNumber)` will not do anything if the channel is already associated to the contact. The update error you are getting should only be a result of tag/attribute changes. Are you doing any operations on the contact other than identify?

**Comment by simonox** [comment]
Hmm.. the channel is already associated to another (old, last login) contact.

Yes, later I try to set an Attribute with the customer number on the channel. That works. I see the outgoing HTTP requests. Looking in Airship Web UI then I can see the channel with the "old" customer number as named user but having an attribute with the current customer number.

**Comment by rlepinski** [comment]
So the `identify` call is not working for you, the channel is stuck on the old named user? Could you provide verbose logs? Let me know if you want my email to send directly instead of pasting here

**Comment by simonox** [comment]
I can confirm, it works perfectly after I resetted my simulator. Then I even see the outgoing HTTP call.

```
{
	"named_user_id": "******",
	"contact_id": "********",
	"channel_id": "********",
	"device_type": "ios"
}
```

**Comment by simonox** [comment]
I can also update the contact identity on the resetted simulator. 

```
{
	"named_user_id": "****",
	"channel_id": "******",
	"device_type": "ios"
}
```
I think we can close this issue.

**Comment by rlepinski** [comment]
I would like to understand why your simulator had an issue before. It should of been able to identify as the updated named user. Any chance you have a way of reproducing that?

**Comment by simonox** [comment]
I will have a try (e.g. installing the old version with the old Airship SDK, updating to the new one).

**Comment by simonox** [comment]
Yes, I can reproduce it on an "old" simulator I did not reset.

**Comment by rlepinski** [comment]
I was unable to reproduce this. Could you provide verbose logs and what steps you are doing to check that its on the old named user?

**Comment by simonox** [comment]
Sure. Do you have an email-address. Could be a bit lengthy (including screenshots of the Airship UI).

**Comment by rlepinski** [comment]
ryan.lepinski@airship.com 

Thanks!
