### ISSUE TITLE
Spelling error in ObjC method name in AppIntegration

### ISSUE THREAD

**Issue by sixten** [urbanairship/ios-library#306]
The attribute specifying the Objective-C name of the method `AppIntegration.application(_:performFetchWithCompletionHandler:)` is missing the "o" in "application": 

https://github.com/urbanairship/ios-library/blob/5855d8d7324b6cc8a8b7943451453a5b67332e25/Airship/AirshipCore/Source/AppIntegration.swift#L28

**Comment by rlepinski** [comment]
Fixed in 16.4
