### ISSUE TITLE
Custom Preference Center Presentation

### ISSUE THREAD

**Issue by h0shy** [urbanairship/ios-library#308]
We want to push (not present) the iOS preference center in non-fullscreen SwiftUI view. Yet there is no way of obtaining just the view (which is an instance of `PreferenceCenterViewController`). The only option is is to present it in the current context.

Would it be possible to add a method simply returning the pref center, enabling the App to handle presentation details? To simply make the initializer of `PreferenceCenterViewController` public would also suffice.

Using: Airship 16.30 / Xcode 13.2.1

**Comment by rlepinski** [comment]
We are working more and more with swiftui and hope to improve compatibility in the future. Most likely we will be switching over to swiftui for all OOTB UI elements in summer.

For now, I'll make a public init method that takes in the preference center ID. We should have a patch EOW.

**Comment by joshuapoq** [comment]
Was also looking for this public init method! Good to hear it'll be there for EOW as that works with our 7th March release date.

**Comment by h0shy** [comment]
> We are working more and more with swiftui and hope to improve compatibility in the future. Most likely we will be switching over to swiftui for all OOTB UI elements in summer.
> 
> For now, I'll make a public init method that takes in the preference center ID. We should have a patch EOW.

Awesome, thanks a lot.

**Comment by rlepinski** [comment]
Made public in 16.3.1

**Comment by rlepinski** [comment]
@h0shy @joshuapoq I am in the process of rewriting our preference center using swiftui. i was wondering if i were to make the code public if you could take a look to make sure it will work for you as well as give any feedback on the exposed views?

**Comment by joshuapoq** [comment]
Hey @rlepinski that sounds great and I'd be happy to take a look. Will try to keep an eye out.

**Comment by rlepinski** [comment]
@joshuapoq Sorry, didnt forget about this, just trying to get it in a better spot. How are you installing the SDK? I am considering doing some alpha releases next week to get some feedback on some of the swift changes we are making.
