### ISSUE TITLE
Get and update Subscriptions iOS Documentation

### ISSUE THREAD

**Issue by h0shy** [urbanairship/ios-library#309]
I see that [android](https://docs.airship.com/platform/android/preference-center/) has a section explaining how subscriptions are retrieved and updated.

```
boolean includePendingUpdates = true;
PendingResult<Set<String>> subscriptionsPendingResult = UAirship.shared().getChannel().getSubscriptionLists(includePendingUpdates);
```

```
void onPreferenceItemToggled(Item item, boolean isSubscribed) {
  if (item instanceof ChannelSubscriptionItem) {
    Item.ChannelSubscription subscription = (Item.ChannelSubscription) item;
    SubscriptionListEditor editor = UAirship.shared().getChannel().editSubscriptionLists();
    if (isSubscribed) {
      editor.subscribe(subscription.getId());
    } else {
      editor.unsubscribe(subscription.getId());
    }
    editor.apply();
  }
}
```

This seems to be missing in [iOS](https://docs.airship.com/platform/ios/preference-center/) entirely?

**Comment by rlepinski** [comment]
@h0shy Ill take a look at our external docs to make sure its all documented, but on iOS we named it `fetch` instead of `get`, as well as default to includePendingUpdates which we might remove the option on Android. you have these two methods:

```
Airship.channel.fetchSubscriptionLists { result, error in
            
}

Airship.contact.fetchSubscriptionLists { result, error in
    
}
```

To edit:
```
Airship.channel.editSubscriptionLists { editor in
  editor.subscribe("some list")
}
```

**Comment by h0shy** [comment]
@rlepinski Thanks a lot, this helps already.

**Comment by rlepinski** [comment]
I think the new guide covers this - https://docs.airship.com/platform/mobile/audience/?groupid=ios-swift
