### ISSUE TITLE
iOS Preference Center Styling

### ISSUE THREAD

**Issue by h0shy** [urbanairship/ios-library#312]
So far the `PreferenceCenterStyle` allows for configuring various fonts. While I'm not quite sure which UI elements these font attributes actually correspond to, the two elements I do want to configure independently are the name and description of a subscription list.

However, those two elements seem to be controller by the same property, namely `preferenceTextFont`:

```
        if let font = style?.preferenceTextFont {
            cell.textLabel?.font = font
            cell.detailTextLabel?.font = font
        }
```

Even in the default preference center styling, the textLabel has a bigger font than the detailTextLabel. Would it be possible to add another font property to also allow independent sizes in custom styles?

Thanks in adavance.

Using: Airship 16.3.1 / Xcode 13.2.1

**Comment by rlepinski** [comment]
Yep, we will add styles for `title` and `subtitle` but default to the generic one to prevent breaking existing views. Ill also extend it to cover all the items that we added for multi-channel preference centers. 

Thanks for the feedback.

**Comment by rlepinski** [comment]
Added in 16.4.0

**Comment by h0shy** [comment]
Thanks so much.
