### ISSUE TITLE
iOS 11 crash at startup

### ISSUE THREAD

**Issue by daveburrowz** [urbanairship/ios-library#317]
# Preliminary Info

### What Airship dependencies are you using?
16.5.1

### What are the versions of any relevant development tools you are using?

- Xcode 13.3.1 
- CocoaPods 1.11.3
- iOS 11.4 device

# Report

### What unexpected behavior are you seeing?

iOS 11 crash on startup

`dyld: Library not loaded: /System/Library/Frameworks/Network.framework/Network
  Referenced from: /private/var/containers/Bundle/Application/F507369A-C571-4BC0-8869-248413C973D7/airshiptest.app/Frameworks/AirshipKit.framework/AirshipKit
  Reason: image not found`

### What is the expected behavior?

Does not crash on startup

### What are the steps to reproduce the unexpected behavior?

- Create an empty iOS app project
- Add Airship dependency via CocoaPods
- Run target on iOS 11 device
- App crashes on startup

### Potential fix

It appears the issue is that the [Network](https://developer.apple.com/documentation/network) library is iOS 12+

I can fix this crash by editing the Airship xxconfig manually and modifying the OTHER_LDFLAGS

Changing:
`-framework "Network"`

To:
`-weak_framework "Network"`

I think this can be done in the Airship podspec by adding:

`core.weak_frameworks = "Network"`

And removing `"Network"` from `core.frameworks `

Looks like this has started happening with the latest version of XCode. As it doesn't look like your podspecs have changed.

Cheers

**Comment by rlepinski** [comment]
Thanks for the report. I am pretty sure we can just remove `Network` all together since its an apple framework. Ill have our Paris team check it out

**Comment by rlepinski** [comment]
We removed `Network` in our pods and it works as expected for us in 16.6.0. Let us know if it resolves your issue.
