### ISSUE TITLE
Suggestion: Remove implicitly unwrapped optionals from public interfaces

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [urbanairship/ios-library#318]
# Preliminary Info

### What Airship dependencies are you using?
N/A

### What are the versions of any relevant development tools you are using?
16.6.0

# Report

### What unexpected behavior are you seeing?
It would be nice to see fewer implicitly unwrapped optional properties in the API (Looking at you MessageCenter.shared!).

### What is the expected behavior?
Ideally, the public interface does not contain any implicitly unwrapped optionals, or the are adequately documented with the promise/guarantee that they'll never explode on you :)

### What are the steps to reproduce the unexpected behavior?
N/A - Code Inspection

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Fixed in 17.0.0
