### ISSUE TITLE
Feature Request: Add unique device id so device not double counted when wiped or app uninstalled/reinstalled

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [urbanairship/ios-library#323]
# Preliminary Info

### What Airship dependencies are you using?
Latest

### What are the versions of any relevant development tools you are using?
Xcode, Apple MDM, Custom Apps

# Report

### What unexpected behavior are you seeing?
When we wipe a device via our MDM tool we use, the device adds a new row to the device table unnecessarily.

### What is the expected behavior?
If we have the means to uniquely identify a device (via MDM capabilities on employee devices), we would like to not have duplicate device tokens and audience counts for a singular device. My teammate wiped his device over 20 times and has just as many audience counts matching his device.

Note this request is different from the Contact API because through MDM you can identify the hardware, where as the Contact API you can specify the User.
https://docs.airship.com/reference/libraries/ios/latest/AirshipCore/Classes/Contact.html

### What are the steps to reproduce the unexpected behavior?
Wipe the device or uninstall/reinstall the app and Airship SDK counts it as a new device (because it doesn't know any better).

### Do you have logging for the issue?
N/A

**Comment by SwiftNativeDeveloper** [comment]
Hey @rlepinski 

My backend team is working with Attributes and estimated device counts for sending targeted pushes and this came up again. If we were able to provide a stable identifier to the Airship SDK to be sent alongside the push token / channel ID, do you think you could de-duplicate or upsert (update or insert) the channel id record?

This assumes we are using an approved mechanism for identifying a device through App Store Review Guidelines. 

Alternatively, an API to 'delete all records of channel ID X except this one I'm sending you now'? I can see this having destructive consequences, so maybe limit it to a backend API call with OAuth tokens our backend would hold vs client key and secret in the 'untrusted' mobile device.

**Comment by rlepinski** [comment]
I sent an email for us to schedule a meeting to come up with a solution

**Comment by crow** [comment]
Feel free to reopen if there's something that needs to be added to this thread.
