### ISSUE TITLE
Message Center - "No messages" label is not visible in dark mode

### ISSUE THREAD

**Issue by ppluskota** [urbanairship/ios-library#327]
# Preliminary Info

### What Airship dependencies are you using?
Airship 16.7.0

### What are the versions of any relevant development tools you are using?
Xcode 13.2.1 && iOS 15

# Report

### What unexpected behavior are you seeing?
The empty list label "No messages" is not visible in dark mode. Seems like the issue is inside **displayEmptyMessage** function:
`[emptyMessage setTextColor:[UIColor blackColor]];`
The text color is the same as the message center list background color that's why it's not visible

### What is the expected behavior?
I should be able to see "No messages" text in dark and light mode.

### What are the steps to reproduce the unexpected behavior?
Switch your current device theme to "Dark Mode" and open the message center screen when you don't have any messages. The text is visible only in "Light Mode"

**Comment by rlepinski** [comment]
Fixed in 16.8.0
