### ISSUE TITLE
Signing issues with Xcode Beta for Airship library installed via CocoaPods

### ISSUE THREAD

**Issue by jakov-clay** [urbanairship/ios-library#328]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
Push notifications
`pod 'Airship'` 
### What are the versions of any relevant development tools you are using?
Xcode Beta (Version 14.0 beta 3 (14A5270f))

# Report

### What unexpected behavior are you seeing?
There are signing issues when framework is installed via CocoaPods
<img width="522" alt="Screenshot 2022-07-08 at 12 48 24" src="https://user-images.githubusercontent.com/56873230/177979192-e4d53592-b4c3-4d9d-be80-6f40de89eb75.png">

### What is the expected behavior?

No signing issues, like for other pods we use in our project.

### What are the steps to reproduce the unexpected behavior?
Install Xcode Beta
Add Airship library via CocoaPods
Try to build project

### Do you have logging for the issue?
Image above

**Comment by oristanovic** [comment]
There seems to be an open issue related to this error [here](https://github.com/CocoaPods/CocoaPods/issues/11402).
It's unclear to me at this point if this is an intended Xcode behaviour or a beta bug but we will keep monitoring and provide a fix if needed.

**Comment by jakov-clay** [comment]
Ok, thanks for info and research.
