### ISSUE TITLE
The backend server receives a large number of abnormal requests, when the iOS App receives the push notification

### ISSUE THREAD

**Issue by Spock0x0** [urbanairship/ios-library#329]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
Airship (16.0.3)

### What are the versions of any relevant development tools you are using?
Xcode 13.2.1, iOS 12

# Report

### What unexpected behavior are you seeing?
backend server receive huge request when app got notification
The user-agent of the request in error will be KKday/1 CFNetwork/1378.1 Darwin/22.0.0
correct user-agent will be like kkday-ios-member/xxxx

![image2022-6-16_19-7-15](https://user-images.githubusercontent.com/105198012/181156724-eb7b5fe4-e9e6-4981-8088-b038b16577a1.png)

<img width="1138" alt="截圖 2022-07-27 上午11 49 16" src="https://user-images.githubusercontent.com/105198012/181156775-529d2454-1cf0-458c-92fc-9c61c5476501.png">

### What is the expected behavior?
There should be no abnormal request issued

### What are the steps to reproduce the unexpected behavior?
When the app receives a push wave, it will trigger a large number of abnormal requests

### Do you have logging for the issue?
NO

**Comment by rlepinski** [comment]
None of those requests are Airship requests. I assume these are requests your app is making and the user agent is not set properly?  When a content-available push is received it will wake the app up but keep it in the background. Maybe you have some code that is setup at a later time in the app lifecycle?

**Comment by Spock0x0** [comment]
thanks, I will look into app lifecycle
