### ISSUE TITLE
Feature Request: Add support for Live Activities push notifications w/ token management

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [urbanairship/ios-library#331]
# Preliminary Info

### What Airship dependencies are you using?
AirshipCore, MessageCenter, latest versions

### What are the versions of any relevant development tools you are using?
Xcode 14 beta 4, iOS 16 beta 4

# Report

### What unexpected behavior are you seeing?
Apple just announced support for Live Activities via ActivityKit. What is different or maybe unexpected, is that each "Live Activity" gets a unique push token for receiving remote updates. This push token is different from the one the application receives in App Delegate.

Tossing an idea out there, maybe Airship could have another SPM target that wrappers or interfaces with the Live Activities push token. Does the Airship have an open forum to discuss ideas on how support could get added to the SDK so we can send Activity type pushes?

Note: Live Activities will not be released with iOS 16.0 but sometime later this fall. Here is pretty much the only available documentation: https://developer.apple.com/documentation/activitykit/displaying-live-data-on-the-lock-screen-with-live-activities

### What is the expected behavior?
n/a

### What are the steps to reproduce the unexpected behavior?
n/a

### Do you have logging for the issue?
n/a

**Comment by rlepinski** [comment]
Added in [16.10.0-beta](https://github.com/urbanairship/ios-library/releases/tag/16.10.0-beta). Push API support should be added sometime next week followed by some docs. A final release will be made available once Xcode 14.1.0 is out
