### ISSUE TITLE
Naming clash with Airship Task protocol and Swift Concurrency Task

### ISSUE THREAD

**Issue by WJacobsNL** [urbanairship/ios-library#332]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

16.8.0
### What are the versions of any relevant development tools you are using?

Xcode 13.3.1
# Report

### What unexpected behavior are you seeing?

When trying to use a Task (from Swift Concurrency) in a file where AirshipCore is imported, the compiler complains about the initialiser not being available. As it then tries to instantiate the protocol Task that is defined in the package.
### What is the expected behavior?

The protocol Task should be renamed to avoid this clash.
### What are the steps to reproduce the unexpected behavior?

import AirshipCore into a file, then try to create an async Task using Swift Concurrency

**Comment by oristanovic** [comment]
Hello, thanks for the report, looking into it

**Comment by rlepinski** [comment]
Yeah, we have run into this internally and its super annoying. We can fix this in a patch since its marked as internal.

**Comment by rlepinski** [comment]
Have 16.9.1 going out right now, it takes a few hours for the pod lint/publish to go through
