### ISSUE TITLE
Message Center: Get deeplink without having to load the landing page

### ISSUE THREAD

**Issue by bezwellington** [urbanairship/ios-library#333]
# Preliminary Info

### What Airship dependencies are you using?
'Airship/MessageCenter', '16.2.0'

### What are the versions of any relevant development tools you are using?
XCode 13.2.1

# Report

### What unexpected behavior are you seeing?
I click on a message and a landing page opens and after I click on the button the Deeplink is triggered

### What is the expected behavior?
I would like to click on the message and get the deeplink associated with the button without having to open the landing page in html.

I tried to fetch the deeplink in the html after it was loaded but the deeplink link was encrypted.

Is there an easier way to select a deeplink to a message?

### Do you have logging for the issue?

![Simulator Screen Shot - iPhone 11 - 2022-08-03 at 10 56 32](https://user-images.githubusercontent.com/17457196/182628826-7c905044-d461-49fc-b431-8b8fc01acd86.png)

<img width="1103" alt="Captura de Tela 2022-08-03 às 10 57 45" src="https://user-images.githubusercontent.com/17457196/182629058-4d5fe834-fe75-4d45-9194-37ae4658f79e.png">

**Comment by rlepinski** [comment]
You should consider using extras on the message center message. You can then override the message center delegate to check if the message has a deep link in the extras and follow it instead of opening the message body.

**Comment by bezwellington** [comment]
Thanks for the reply, @rlepinski. Is there a possibility to put the deeplink component in the extras area to make my marketing team's work easier? Because there I can only see the option to put key:String and value:String

**Comment by rlepinski** [comment]
@bezwellington Not at the moment but I can forward this request to our product team and they can get in touch with you. @msuslak ^

**Comment by bezwellington** [comment]
Thanks for the feedback @rlepinski . It would be really cool to have a deeplink button in the extras area to make the marketing team's job easier. If you need to get in touch, my email is: bezwellington@gmail.com Thank you. 😊
