### ISSUE TITLE
Make the static variables configurable on the UAInAppMessageBannerView

### ISSUE THREAD

**Issue by gfoldv** [urbanairship/ios-library#335]
# Preliminary Info

### What Airship dependencies are you using?
AirshipCore 16.9.1 
AirshipAutomation 16.9.1

### What are the versions of any relevant development tools you are using?
Xcode 13.4.1

# Report

### What unexpected behavior are you seeing?
Values are hardcoded and not customizable

```
static CGFloat const BannerIsBeingTappedAlpha = 0.7;
static CGFloat const ShadowOffset = 2.0;
static CGFloat const ShadowRadius = 4.0;
static CGFloat const ShadowOpacity = 0.5;
```

### What is the expected behavior?
It would be beneficial to make these values configurable in the `LegacyInAppMessageBuilderExtender` or where it fits best.

I am wondering, what was the idea making the dialog semi-transparent when it is tapped?

**Comment by rlepinski** [comment]
The decision was made several years ago, but I assume it has to do with making it respond to clicks without knowing the exact color of the banner since that is all configurable. What would you expect it to do?

**Comment by crow** [comment]
Created an enhancement request for this in our internal ticketing system. Feel free to reopen if there's something that needs to be added to this thread.
