### ISSUE TITLE
Infinite cycle on method swizzling when using Automatic Integration

### ISSUE THREAD

**Issue by lehenealexandra** [urbanairship/ios-library#341]
# Preliminary Info

### What Airship dependencies are you using?
16.9.3/16.9.4 (the latest stable released)

### What are the versions of any relevant development tools you are using?
xcode 14.0.1, cocoapods 1.11.3

# Report

### What unexpected behavior are you seeing?
After upgrading from 'Airship', '= 16.7.0' to latest versions 16.9.3/16.9.4 method swizzling implementation will go in infinite cycle in simulator when calling ApplicationDidFailToRegisterForRemoteNotificationsWithError 

### What is the expected behavior?
didFailToRegisterForRemoteNotificationsWithError should be called only once when running on simulator 

### What are the steps to reproduce the unexpected behavior?
1. use default config of UA without any customization
2. run the app on simulator
3. request to registerForRemoteNotifications in didFinishLaunchingWithOptions method
4. infinite cycle will happen on method didFailToRegisterForRemoteNotificationsWithError from AppDelegate which was triggered by ApplicationDidFailToRegisterForRemoteNotificationsWithError airship method swizzling in UAAutoIntegration

### Do you have logging for the issue?

![Screenshot 2022-10-18 at 15 10 25](https://user-images.githubusercontent.com/114667370/196428934-ec282597-0c03-4794-b63e-9264dad1a94d.png)
![Screenshot 2022-10-18 at 15 11 30](https://user-images.githubusercontent.com/114667370/196615424-7f15e48d-18d1-45b4-8a15-d006a05b9a37.png)

**Comment by oristanovic** [comment]
@lehenealexandra Does this happen even if you leave the `didFailToRegisterForRemoteNotifications`in your `AppDelegate` empty ?

**Comment by lehenealexandra** [comment]
@oristanovic I just tested right now, I let the method _didFailToRegisterForRemoteNotificationsin_  empty and on iPhone14 pro (iOS16.0) is not getting called at all but on iPhone 8 (15.5) is getting called 3 times ... but at least is not going in infinite cycle how is happening when I have some code in those methods from app delegate

**Comment by oristanovic** [comment]
Right, so in that case it would seem that the method (`requestActivateUser`) you're calling might be triggering the registration process and creating the infinite cycle.

**Comment by lehenealexandra** [comment]
@oristanovic True ;) I just printed a log message and it will not go to infinity cycle. I thought is a problem with the library update while our code is the same and with older version 16.7.0 this infinite cycle is not happening at all. In that method `requestActivateUser` we use this block UNUserNotificationCenter.current().getNotificationSettings to get exactly the updated status to send it to our server ... so definitely we don't try to register again for remote notif but we try to get the status of push notif registration which according to me is still wrong while the method swizzling from Airship intercept it in a wrong way.

**Comment by rlepinski** [comment]
@lehenealexandra I dont think its the method swizzling, it seems like a red herring to me. Most likely it has to do with the changes we made to our APNS registration where we might be calling `registerForRemoteNotifications` more often to Airship. Does requestActivateUser make any calls to AIrship?
