### ISSUE TITLE
In-app messages & deeplink not working(16.10.6)

### ISSUE THREAD

**Issue by Tank-Coder14** [urbanairship/ios-library#343]
# Preliminary Info

### What Airship dependencies are you using?

Airship/Core, 16.10.6
AirshipExtensions/NotificationService, 16.10.6
### What are the versions of any relevant development tools you are using?

Xcode 14.1

# Report

### What unexpected behavior are you seeing?

1. My app is running in foreground, then I send a push notification(include `In-App Message`) from airship service,  but  I can't receive this notification or message.
2. My app is not running, and then I send a push notification with a deepLink from the airship background, I receive this notification, I tap it to open the app, but the deepLink does not work.
3. The above 2 items can work normally in version 16.9.4

### What is the expected behavior?

1. I can receive this message when my app in foreground
2. when I tap the notification, the deeplink need be work

**Comment by Tank-Coder14** [comment]
here is my code:


```
public func registerPushNotification(_ launchOptions: [UIApplication.LaunchOptionsKey: Any]?) {
        let config = Config.default()
        config.isAutomaticSetupEnabled = false
        config.detectProvisioningMode = true
        config.requestAuthorizationToUseNotifications = false
        config.urlAllowListScopeOpenURL = [customerSuccessLink, vimeoHttpsLink, vimeoHttpLink]
        config.productionAppKey = Target.type.airshipProAppKey
        config.productionAppSecret = Target.type.airshipProAppSecret
        config.developmentAppKey = Target.type.airshipDevAppKey
        config.developmentAppSecret = Target.type.airshipDevAppSecret

        Airship.takeOff(config, launchOptions: launchOptions)
        if Airship.isFlying {
            Airship.push.pushNotificationDelegate = pushHandler
            Airship.push.customCategories = getNotificationCategories()
            Airship.push.registrationDelegate = registrationDelegate
            Airship.shared.deepLinkDelegate = deepLinkDelegate
            DevicePrivacy.getAuthorizedNotificationSettings { setting, authorizationStatus in
                guard authorizationStatus == .authorized else { return }
                Airship.push.userPushNotificationsEnabled = true
            }
        }
    }
```

**Comment by rlepinski** [comment]
@Tank-Coder14 Did you mean to close this? Still having the issue?

**Comment by Tank-Coder14** [comment]
> @Tank-Coder14 Did you mean to close this? Still having the issue?

yes, we found out that our project's code was causing the issue, so closed it.
