### ISSUE TITLE
Receptive crashes in Coredata class UrbanAirship iOS SDK 

### ISSUE THREAD

**Issue by snomula05** [urbanairship/ios-library#353]
Hi Team, 

We are using UrbanAirship-iOS-SDK, we are getting repetitive crashes in CoreData UrbanAirship classes, please find the attached console log for your reference.

Currently we are using  'UrbanAirship-iOS-SDK', '~ 12.0.0'?, We are identified one update 12.1 available, the above issue fixed in this version or not?, kindly please let us know.

What are ways to reproduce the above issue in iOS devices?

These crashes are reported by the firebase analytics console.

[AppCrash Console file. txt](https://github.com/urbanairship/ios-library/files/10897739/AppCrash.Console.file.txt)

**Comment by rlepinski** [comment]
I dont see anything Airship or Coredata related in your stacktrace. Maybe the wrong one?

**Comment by snomula05** [comment]
> I dont see anything Airship or Coredata related in your stacktrace. Maybe the wrong one?

Please find the below-attached files.
[Airship Kit crash file. txt](https://github.com/ur
[Airship Crash file-2.txt](https://github.com/urbanairship/ios-library/files/10905963/Airship.Crash.file-2.txt)
banairship/ios-library/files/10905962/Airship.Kit.crash.file.txt)

**Comment by snomula05** [comment]
> I don't see anything Airship or Coredata related in your stack trace. Maybe the wrong one?

Please find the below-attached files:
[Airship Kit crash file-1.txt](https://github.com/urbanairship/ios-library/files/10908901/Airship.Kit.crash.file-1.txt)
[Airship Kit crash file-2.txt](https://github.com/urbanairship/ios-library/files/10908902/Airship.Kit.crash.file-2.txt)
[Airship Kit Crash file-3.txt](https://github.com/urbanairship/ios-library/files/10908903/Airship.Kit.Crash.file-3.txt)
[Airship Kit crash file-4.txt](https://github.com/urbanairship/ios-library/files/10908904/Airship.Kit.crash.file-4.txt)
[Airship Kit crash file-5.txt](https://github.com/urbanairship/ios-library/files/10908905/Airship.Kit.crash.file-5.txt)

**Comment by rlepinski** [comment]
I am not seeing the reasons for the crash in the stack traces, just the path. I am not sure what the crashes are caused from, most this code has been rewritten in swift, so its very possible it no longer exists in recent versions of the SDK (16.11). I see a few patches for 12.x that fix issues with IAA and Message Center, so I would at least update to 12.1.2 to see if they go away. Ideally you update to 16.x though
