### ISSUE TITLE
High Number of HTTP 502 Errors

### ISSUE THREAD

**Issue by rwbutler** [urbanairship/ios-library#354]
# Preliminary Info

### What Airship dependencies are you using?
Airship iOS SDK version 16.10.7 in a native Swift iOS app supporting iOS 13 and above.

### What are the versions of any relevant development tools you are using?
Xcode 14.2

# Report

### What unexpected behavior are you seeing?

Airship iOS SDK is contacting https://combine.urbanairship.com/warp9 and receiving a very high number of 502 errors in response. This frequently causes errors to be raised by our monitoring software and even causes alerts to be raised informing our team that there is a high number of errors in our app. When we investigate the cause it turns out to be the iOS Airship SDK.

Presumably either an incorrect API call is being made by the SDK or there is a server-side error.

Data suggests that the following URLs are also triggering 502 response codes.

![Screenshot 2023-03-08 at 09 27 28](https://user-images.githubusercontent.com/1029504/223674998-f6c0439a-d2c8-4bbf-9325-006edd8be416.png)

### What is the expected behavior?

There should be no 502s in a perfect world but even a reduced number of these would be preferable.

### What are the steps to reproduce the unexpected behavior?
Cause is unknown - perhaps the logs below will shed some light on this. Airship server-side logs would no doubt help with debugging this.

### Do you have logging for the issue?

![Screenshot 2023-03-08 at 09 22 03](https://user-images.githubusercontent.com/1029504/223673999-5c7ea58a-69b9-47b5-b784-37114b55c5fd.png)

(Have redacted some of the information)

**Comment by rlepinski** [comment]
I am not sure what the time period is for that many error 502s, but that is generally an indicator of the backend service not scaling quickly enough for the load. Looks like there was a small period of elevated 50x in the last few days. The SDK will automatically retry and handle 502s without losing data, so you can safely ignore them.
