### ISSUE TITLE
In-App Automation Modal doesn't get dismissed on button press

### ISSUE THREAD

**Issue by mmdumi** [urbanairship/ios-library#355]
# Preliminary Info

### What Airship dependencies are you using?
Latest version 16.11.2

### What are the versions of any relevant development tools you are using?
xcode 14.2

# Report

### What unexpected behavior are you seeing?
I've got an in app automation running that shows a modal template correctly.
The template offers a button that triggers a deeplink into the app.
Pressing the button calls the following delegate implementation:
```
func receivedDeepLink(_ url: URL, completionHandler: @escaping () -> Void) {
    onReceivedURL?(url)
    completionHandler()
  }
```
On android the same automation calls the delegate but then dismisses the modal. On iOS the modal doesn't get automatically dismissed.

### What is the expected behavior?
The modal should get dismissed on template button press.

### What are the steps to reproduce the unexpected behavior?
Create an in app automation with a simple template + button that triggers a deeplink.

**Comment by rlepinski** [comment]
@mmdumi Which path did you take when creating the message?

<img width="1146" alt="Screenshot 2023-03-09 at 7 12 17 AM" src="https://user-images.githubusercontent.com/3967591/224067570-bce6cce8-b4ff-485f-8177-8652b4f54ac9.png">

**Comment by mmdumi** [comment]
It was template and I did choose a default template with button

**Comment by rlepinski** [comment]
Thanks, trying to reproduce with your exact setup. Template & Interactive Editor produce HTML based IAA and dismiss differently vs the classic ones.

**Comment by mmdumi** [comment]
Thank you. Please try with html ones.

**Comment by rlepinski** [comment]
When you created your content, did you check this box:
<img width="406" alt="Screenshot 2023-03-09 at 16 53 13" src="https://user-images.githubusercontent.com/3967591/224081947-f7e519db-21b1-4a0d-b8b6-c16d1c2f5278.png">

**Comment by rlepinski** [comment]
🎉
