### ISSUE TITLE
Xcode 14.3 report No such module Airship

### ISSUE THREAD

**Issue by chandrapol** [urbanairship/ios-library#358]
# Preliminary Info

### What Airship dependencies are you using?

`pod 'Airship', '~> 16.11.3'`

### What are the versions of any relevant development tools you are using?
1. `pod 'Airship', '~> 16.11.3'`
2. Xcode `14.3 (14E222b)`
3. CocoaPods: `1.11.3`
4. MacBook Pro M1
5. macOS Ventura `13.3`

# Report

### What is the expected behavior?
Xcode reports `No such module Airship`. Airship has been working since years. This is happening with new Xcode update (to 14.3).

### What are the steps to reproduce the unexpected behavior?
1. Update Xcode to `14.3`
2. `pod deintegrate`
3. `pod install`
4. Build the project

### Do you have logging for the issue?
Not relevant

**Comment by jyaganeh** [comment]
Hi @chandrapol,

I checked the CocoaPods Specs repo and can confirm that the [16.11.3 release](https://github.com/CocoaPods/Specs/commit/5b66e4dc7a4c7a52429e1a07b173fcb2035725fc) exists there.

Can you try a `pod install --repo-update`, so that CocoaPods will fetch the latest specs, and see if that resolves your issue?

**Comment by chandrapol** [comment]
Hi @jyaganeh : 

Even before running `pod install --repo-update`, I see Airship was fetched.

```
Podfile.lock
PODS:
  - Airship (16.11.3):
    - Airship/Automation (= 16.11.3)
    - Airship/Basement (= 16.11.3)
    - Airship/Core (= 16.11.3)
    - Airship/ExtendedActions (= 16.11.3)
    - Airship/MessageCenter (= 16.11.3)
```

But for some reasons, our project does not recognize. It is happening only on Xcode 14.3. 

Xcode 14.2 just runs fine.

**Comment by rlepinski** [comment]
@chandrapol Ill try to reproduce today. Thanks for the update

**Comment by rlepinski** [comment]
What version are you coming from? In SDK 16 we had to rename the module import to `AirshipKit` from `Airship` to avoid a conflict with the class `Airship`.

**Comment by chandrapol** [comment]
> What version are you coming from? In SDK 16 we had to rename the module import to `AirshipKit` from `Airship` to avoid a conflict with the class `Airship`.

`pod 'Airship', '~> 16.11.3'`

**Comment by rlepinski** [comment]
What was the previous version in your pod lock file for Airship? If you replace `import Airship` with `import AirshipKit` do your issues go away?

**Comment by chandrapol** [comment]
> import AirshipKit

This worked. I will close this issue.
