### ISSUE TITLE
Airship not compiling on XCode 14.3 while using spm

### ISSUE THREAD

**Issue by AdamLinke** [urbanairship/ios-library#360]
# Preliminary Info

### What Airship dependencies are you using?

AirshipCore
### What are the versions of any relevant development tools you are using?

Xcode 13.4, swift package manager 
# Report

### What unexpected behavior are you seeing?

The library is not compiling. With the issue being lines 30 and 38 in Shapes struct(in Shapes.swift file). The error displayed being "Initializer for conditional binding must have Optional type, not 'Color'". Which is accurate because the strokeColor is not optional(as in this case it would have Color.clear value as wrote in line 25 of Shapes struct)
### What is the expected behavior?

The framework should compile.
### What are the steps to reproduce the unexpected behavior?

Try to compile the framewrok using swift package manager and XCode 13.4
### Do you have logging for the issue?

Error displayed during compilation: "Initializer for conditional binding must have Optional type, not 'Color'"

**Comment by rlepinski** [comment]
Already fixed in 16.11.2+

https://github.com/urbanairship/ios-library/issues/359
