### ISSUE TITLE
InAppAutomation animated dismiss

### ISSUE THREAD

**Issue by Skornos** [urbanairship/ios-library#366]
# Preliminary Info

### What Airship dependencies are you using?

16.11.3

# Report

### What unexpected behavior are you seeing?

Our app is using InAppAutomation from AirshipKit to display in app overlays and messages. Anyway the UX on dismiss after tapping on deeplink is not good because it's dismissed immediately without any smooth animation. Is there a way how to dismiss the message with an animation? 

### What is the expected behavior?

InAppAutomation gets dismissed with animation after tapping on deeplink.

### What are the steps to reproduce the unexpected behavior?

Receive InAppAutomation message with a deeplink. Tap on a button. Message gets dismissed immediately without any animation.

**Comment by rlepinski** [comment]
👍 

We will be working on improving our animations in the coming months.

**Comment by rlepinski** [comment]
In 18.0.0 we added window animations
