### ISSUE TITLE
Tint color not applied to MessageCenter navigation button items

### ISSUE THREAD

**Issue by garyjyochum** [urbanairship/ios-library#369]
# Preliminary Info

### What Airship dependencies are you using?
pod 'Airship' //16.11.3
pod 'AirshipExtensions/NotificationService' //v14.6.1

### What are the versions of any relevant development tools you are using?
Xcode 14.3.1
iPhone XR with iOS 16.3.1

# Report

### What unexpected behavior are you seeing?
When rendering the MessageCenter component in our iOS app, setting the MessageCenterStyle 'tintColor' property does not get applied to the navigation button items.  We are setting the tintColor to a dark blue, but when rendering the MessageCenter, we see

![IMG_991E167E0BFA-1](https://github.com/urbanairship/ios-library/assets/67169547/c2819003-d07d-4c66-8fdd-903dd09b31ee)

The buttons are there but the color for both buttons is white, thus not visible.

```
let messageCenter = MessageCenter.shared
let s = MessageCenterStyle()

        s.titleFont = UIFont(name: "HelveticaNeue", size: 20)
        s.tintColor = UIColor.blue
        s.titleColor = UIColor.blue
        s.navigationBarColor = UIColor.white
        s.navigationBarOpaque = true
        s.listColor = UIColor.white
        s.refreshTintColor = UIColor.blue
        s.iconsEnabled = false
        s.cellSeparatorColor = UIColor.lightGray
messageCenter.defaultUI.messageCenterStyle = s
messageCenter.display(false)
```

### What is the expected behavior?
When using the code above, we are expecting the navigation button items to match what we set for the tintColor.

### What are the steps to reproduce the unexpected behavior?
When the user taps a CTA in the app, we create a MessageCenter instance, set the style, and render it

### Do you have logging for the issue?
No, but we have fixed(?) the issue by doing the following in our local development environment:
1. Open the UADefaultMessageCenterSplitViewController.m class
2. navigate to the applyStyle() method
3. in the if statement checking to see if tintColor has been set, we added this line `self.listNavigationController.navigationBar.tintColor = self.messageCenterStyle.tintColor;`

```
if (self.messageCenterStyle.tintColor) {
        self.view.tintColor = self.messageCenterStyle.tintColor;
        self.listNavigationController.navigationBar.tintColor = self.messageCenterStyle.tintColor;
        self.messageNavigationController.navigationBar.tintColor = self.messageCenterStyle.tintColor;
    }
```
![IMG_55AE83436EF6-1](https://github.com/urbanairship/ios-library/assets/67169547/c584ef42-38e5-4632-96af-80605e1e29de)

Note: I checked to see if the latest 16.* version of the SDK addressed this (16.12.2) before creating this issue.

**Comment by rlepinski** [comment]
Thanks for the report, ill see if i can get this fixed for the next patch release this week

**Comment by rlepinski** [comment]
This seems to be working for me, I used your code but set the tint color to purple:

![simulator_screenshot_086BE022-DE81-4755-AE29-0F060DDD012C](https://github.com/urbanairship/ios-library/assets/3967591/3fdc5c6f-371f-4f20-868f-53a62491a734)

Trying to figure out how to reproduce it

**Comment by rlepinski** [comment]
This was on a simulator running 16.4 not 16.3.1. Could you try it on 16.4 to see if the issue still exists? If not, are you setting an message center display delegate? Also I am not sure how you are getting no buttons (maybe invisible?)

**Comment by garyjyochum** [comment]
@rlepinski Interesting, I just ran our app on a 16.4 simulator and still see the issue.  I updated the version UA to 16.12.2 as well just to make sure I have the latest 16.* version.  We do not set a message center display delegate - should we?  I thought that rendering something custom - we just want to render the default message list/details.  As you can see in the screenshot, the buttons are definitely there, just match the white background color.

If you cannot reproduce, I am working to update the project to use the new 17.* version of the SDK in a separate branch.  Hopefully that will resolve the issue.

<img width="1268" alt="image" src="https://github.com/urbanairship/ios-library/assets/67169547/5b3058d2-e48f-4f52-aeaa-5569c94272f6">

**Comment by rlepinski** [comment]
No on the display delegate, just checking to see what could be causing this. Are you setting the appearance at the top level in your app somewhere? I was able to get similar results with this:
```
UINavigationBar.appearance().tintColor = .white
```

**Comment by rlepinski** [comment]
Doing a 16.12.3 release that should fix your current issue. I am going to bet that 17.x message center is might cause some issues with you since we switched to swiftui and have less control over how the navigation bar is styled. If you run into any issues with that please let me know asap and we will get it sorted out.

**Comment by garyjyochum** [comment]
@rlepinski Thank you for looking at this so quickly!

**Comment by rlepinski** [comment]
16.12.3 should be out
