### ISSUE TITLE
Failed navigating to Message Center after push notification action

### ISSUE THREAD

**Issue by bm185178** [urbanairship/ios-library#383]
# Preliminary Info

### What Airship dependencies are you using?
Airship: 16.12.3+ and 17.6.0

### What are the versions of any relevant development tools you are using?
Xcode 15.0.1 and iPhone 15 Pro Max (iOS 17)

# Report

### What unexpected behavior are you seeing?
Push notification action does not navigate to Message Center after fresh launching the app

### What is the expected behavior?
Push notification action should navigate to Message Center after fresh launching the app

### What are the steps to reproduce the unexpected behavior?
1. Send push notification with action - that is configured to display message center
2. Receive above push in your phone
3. Press the push 

### Do you have logging for the issue?
There is no error or warning on console since it is not crash. No logs but this case woks with android airship sdk and iOS works partially. If app was already launched before, push action will take user to Message Center as expected.

**Comment by rlepinski** [comment]
Do you have a message center delegate set? if so could you provide that? Does this happen only on a cold launch or also when the app is in the background?
