### ISSUE TITLE
Don't exclude arm64 architecture in the SDK

### ISSUE THREAD

**Issue by cristianeydev** [urbanairship/ios-library#384]
# Preliminary Info

### What Airship dependencies are you using?
pod 'AirshipServiceExtension', '~> 17.1.3'

# Report

### What unexpected behavior are you seeing?
Unsupport for arm64 architecture

### What is the expected behavior?
Support for arm64 architecture

We need a version of the SDK supporting this:

Apple is marking this like an important point from a long time ago
https://developer.apple.com/documentation/technotes/tn3117-resolving-build-errors-for-apple-silicon/
"Important Always contact the library vendor to request an updated library supporting the simulator on Apple silicon. Modifications to the EXCLUDED_ARCHS build setting for a simulator SDK are not a replacement for getting an updated library, and should only be used while waiting for the vendor to make an updated library available"

**Comment by rlepinski** [comment]
I don not believe we are excluding any architectures in the pod spec - https://github.com/urbanairship/ios-library/blob/17.1.3/AirshipServiceExtension.podspec

**Comment by cristianeydev** [comment]
Now it's not failing, I'm closing until I can get a trace of the error.
