### ISSUE TITLE
Fix LICENSE file

### ISSUE THREAD

**Issue by stherold** [urbanairship/ios-library#389]
# Report

### What unexpected behavior are you seeing?
We now have to verify our licenses against a central file and we use [License Plist](https://github.com/mono0926/LicensePlist) to find the licenses for all of our dependencies. For Airship it cannot detect the proper license type though. 

I recognized that your LICENSE file differs quite a bit from e.g. the one [Google Maps](https://github.com/googlemaps/google-maps-ios-utils/blob/main/LICENSE) is using, which is recognized by the tool. 

### What is the expected behavior?
Can you fix your license file so it matches an official version of the Apache 2.0 license? 

Here you can find the official license text:
https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by rlepinski** [comment]
We can probably update it but its something that I will have to run by our legal team

**Comment by stherold** [comment]
That would be nice :)

**Comment by rlepinski** [comment]
@stherold I did submit this to legal when you first posted it, ill ping them again on it

**Comment by Blackjacx** [comment]
Thanks for being so fast 🙏

**Comment by rlepinski** [comment]
@Blackjacx @stherold I got approval to update the license. Sorry for the delay. Is it possible for you to update to 18.x?

**Comment by Blackjacx** [comment]
Hey there 👋 thank you very much! Yes 18.x is totallly fine 👍
