### ISSUE TITLE
Core Data warnings on Xcode 15.2

### ISSUE THREAD

**Issue by ppluskota** [urbanairship/ios-library#391]
# Preliminary Info

### What Airship dependencies are you using?
Airship Core, MessageCenter, Automation, PreferenceCenter - Version 17.7.3

### What are the versions of any relevant development tools you are using?
Xcode 15.2, iOS 17, macOS Ventura 13.6.4, CocoaPods 1.15.0

# Report

### What unexpected behavior are you seeing?
I'm seeing a couple of warnings from Airship on Xcode 15.2

### What is the expected behavior?
No warnings from Airship on Xcode 15.2

### What are the steps to reproduce the unexpected behavior?
Just install the latest Airship version (17.7.3) using CocoaPods 1.15.0 and build the project on Xcode 15.2

### Do you have logging for the issue?
See the attached screenshot

<img width="464" alt="2024-02-6 o 11 48 59" src="https://github.com/urbanairship/ios-library/assets/22774595/b81f0f19-2f72-450d-b44a-20a0d312970a">

**Comment by crow** [comment]
Hey thanks for submitting this. We're currently looking at ways to reduce our need for transformers in an effort to further streamline our core data implementation. We'll make sure we get these resolved in the process. Will keep you posted.

**Comment by rlepinski** [comment]
These should be resolved in 18.0.0-beta.2. We are hoping to do a final release in the next week or two.

**Comment by ppluskota** [comment]
@rlepinski any chance to update it in Airship 17 as well? We don't want to migrate to the 18 version yet

**Comment by rlepinski** [comment]
@ppluskota There are 2 coredata warnings that are difficult to remove in the automation module that we addressed in SDK 18. IMO its not worth the risk of changing it for 17 when it appears to just be  a warning in Xcode 15 that has no effect on runtime. I am still hopeful a new xcode version will fix it

**Comment by rlepinski** [comment]
18.0.0 is finally out
