### ISSUE TITLE
Thread Performance Checker Issue

### ISSUE THREAD

**Issue by nomimalik92** [urbanairship/ios-library#394]
What Airship dependencies are you using?
iOS SDK and Version 16.12.4

What are the versions of any relevant development tools you are using?
XCode 15.3

What unexpected behavior are you seeing?
I am getting this thread performance issue in logs.

What expected behavior I am looking for?
This thread performance should not be here.

Do you have logging for the issue?
Attaching screenshot of logs.

<img width="1486" alt="image" src="https://github.com/urbanairship/ios-library/assets/62884306/7acb472a-3f9e-48d1-8f67-6da71f9ade2c">

**Comment by nomimalik92** [comment]
What about those user who can't update their SDK to 17.0. Because of minimum target restriction. Our app minimum version is iOS 12 and we can't update SDK to 17.0. 
So there should be a fix for this. What you think?

**Comment by nomimalik92** [comment]
@rlepinski

**Comment by rlepinski** [comment]
I looked into the issue and it appears that we are doing everything on a utility queue, not user initiated. I also was not able to reproduce that exact issue, but I was able to get this to happen once per run:
```
Thread Performance Checker: Thread running at User-initiated quality-of-service class waiting on a lower QoS thread running at Utility quality-of-service class. Investigate ways to avoid priority inversions
14  AirshipCore                         0x0000000105316914 $s11AirshipCore10UACoreDataC18safePerformAndWaityyySb_So22NSManagedObjectContextCtcFyyXEfU_ + 632
17  CoreData                            0x0000000186369e80 developerSubmittedBlockToNSManagedObjectContextPerform + 156
20  CoreData                            0x0000000186369d8c -[NSManagedObjectContext performBlockAndWait:] + 260
21  AirshipCore                         0x0000000105316644 $s11AirshipCore10UACoreDataC18safePerformAndWaityyySb_So22NSManagedObjectContextCtcF + 396
22  AirshipCore                         0x0000000105316b2c $s11AirshipCore10UACoreDataC18safePerformAndWaityyySb_So22NSManagedObjectContextCtcFTo + 104
```

These are warnings, they are not causing enough issues to patch a now 2 major version back release. Its just not worth the risk IMO.
