### ISSUE TITLE
Banner in-app message view controller is not removed from parent view controller

### ISSUE THREAD

**Issue by neriusv** [urbanairship/ios-library#395]
# Preliminary Info

### What Airship dependencies are you using?
18.0.1

### What are the versions of any relevant development tools you are using?
Xcode 15.3

# Report

### What unexpected behavior are you seeing?
View controller of a banner in-app message is not removed from parent view controller after being dismissed.

### What is the expected behavior?
View controller should be removed after dismissing the banner message.

### What are the steps to reproduce the unexpected behavior?

1. Send a banner in-app message;
2. Dismiss the message;
3. Inspect `children` of the root view controller: `AirshipAutomation.InAppMessageBannerViewController` is still present.

I believe the problem is at line [146 of AirshipLayoutDisplayAdapter.swift](https://github.com/urbanairship/ios-library/blob/314551ee7607a7101dd2d4cf69a8637fd3ed20af/Airship/AirshipAutomation/Source/InAppMessage/Display%20Adapter/AirshipLayoutDisplayAdapter.swift#L146) where `viewController?.removeFromParent()` is not called.
The correct order should be

```swift
viewController?.willMove(toParent: nil)
viewController?.view.removeFromSuperview()
viewController?.removeFromParent()
viewController = nil
```

See Apple Developer documentation: [Remove a child view controller from your content](viewController?.removeFromParent())

### Do you have logging for the issue?
n/a

**Comment by crow** [comment]
Thanks for the report - will get this fixed and released in the next patch.
