### ISSUE TITLE
Which documentation is correct?

### ISSUE THREAD

**Issue by paulsUsername** [urbanairship/ios-library#401]
The documentation on airship:

<img width="936" alt="Screenshot 2024-04-11 at 21 52 30" src="https://github.com/urbanairship/ios-library/assets/32492218/7839e651-43c7-4fa2-a973-e8f2384fc9f1">

The actual SDK in Airship.push:

    /// Called when APNS registration completes.
    ///
    /// - Parameters:
    ///   - authorizedSettings: The settings that were authorized at the time of registration.
    ///   - status: The authorization status.
    @objc
    optional func notificationRegistrationFinished(
        withAuthorizedSettings authorizedSettings:
            UAAuthorizedNotificationSettings,
        status: UAAuthorizationStatus
    )

    /// Called when notification authentication changes with the new authorized settings.
    ///
    /// - Parameter authorizedSettings: UAAuthorizedNotificationSettings The newly changed authorized settings.
    @objc optional func notificationAuthorizedSettingsDidChange(
        _ authorizedSettings: UAAuthorizedNotificationSettings
    )

    /// Called when the UIApplicationDelegate's application:didRegisterForRemoteNotificationsWithDeviceToken:
    /// delegate method is called.
    ///
    /// - Parameter deviceToken: The APNS device token.
    @objc optional func apnsRegistrationSucceeded(
        withDeviceToken deviceToken: Data
    )
    

   Which is correct and which should be called when?
   
   Even the docuemtation on your trouble shooting is wrong!
   
   <img width="939" alt="Screenshot 2024-04-11 at 21 53 38" src="https://github.com/urbanairship/ios-library/assets/32492218/ac67ed01-48d7-4b94-90f6-f5665729bddf">
   
   This method is actually called:
   
   config.isAutomaticSetupEnabled = false
   
   This is my first 5-6 hours of using airship. How out of line is the documentation?

**Comment by rlepinski** [comment]
It should be `isAutomaticSetupEnabled` not `automaticSetupEnabled`. That changed during the swift migration but you can use either key in the airshipconfig.plist. 

You are not calling through to AirshipPush, instead you are calling through to AppIntegration class. The documentation looks correct to me other than `isAutomaticSetupEnabled` key
