### ISSUE TITLE
Banner is not appearing correctly

### ISSUE THREAD

**Issue by paulsUsername** [urbanairship/ios-library#402]
No matter what configuration I set, I am getting the same. Modal works fine but just banner is always in top left corner.

SDK version 18.1.1

![IMG_3540](https://github.com/urbanairship/ios-library/assets/32492218/b3b11f23-1760-474f-86ac-73b482a943a8)

**Comment by paulsUsername** [comment]
Modals and Fullscreen work perfectly, its just banner type.

**Comment by crow** [comment]
@paulsUsername looking into it, thanks for reporting

**Comment by rlepinski** [comment]
@paulsUsername We are unable to reproduce but you are not the only user that is seeing this. We are going to continue to try but if you could provide a sample or maybe some hints on your UI stack that would be awesome

**Comment by rlepinski** [comment]
We were able to reproduce it, looking for a fix

**Comment by paulsUsername** [comment]
Hey @rlepinski 
Sorry for not getting back. That's good, thanks for the update!

If you need anything else from me please let me know 🙌🏻

**Comment by crow** [comment]
@paulsUsername [Release 18.2.0](https://github.com/urbanairship/ios-library/releases/tag/18.2.0) is out with the fix

**Comment by paulsUsername** [comment]
Working for me now, thanks!
