### ISSUE TITLE
Airship 18 prebuilt with Carthage

### ISSUE THREAD

**Issue by hassan-ioki** [urbanairship/ios-library#403]
# Report

### What unexpected behavior are you seeing?
We use Airship prebuilt with Carthage. Normally we get the json [here](https://github.com/urbanairship/ios-library-prebuilt/blob/main/Carthage/Airship.json). But for Airship 18 I don't see this. Is there an expected update for this?

### What is the expected behavior?
Can you suggest what we could be missing or a suggestion on how to proceed?

**Comment by rlepinski** [comment]
It should be there, we will take a look at the build process to see whats going on. Hopefully we can have this addressed tomorrow.

**Comment by rlepinski** [comment]
It looks to be addressed. Please reach out if you still have issues.

**Comment by hassan-ioki** [comment]
@rlepinski The newest version is not visible in the raw json [here](https://raw.githubusercontent.com/urbanairship/ios-library-prebuilt/main/Carthage/Airship.json) or in the file [here](https://github.com/urbanairship/ios-library-prebuilt/blob/main/Carthage/Airship.json). Can you please add it there too?

**Comment by rlepinski** [comment]
Added. Sorry this must of fell off my todo list to fix it on deploy. Ill get another ticket on our board for this.
