### ISSUE TITLE
[Enhancement] Make in app message dismiss button size configurable

### ISSUE THREAD

**Issue by FabianBartels** [urbanairship/ios-library#407]
### What Airship dependencies are you using?
Exact-Version: 18.3.1

### What are the versions of any relevant development tools you are using?
Xcode: 16.0.0

# Report
This can be seen as enhancement rather than an issue.

### What unexpected behavior are you seeing?
The [dismiss button](https://github.com/urbanairship/ios-library/blob/9b75747e2942baaa7e10e09838c27bb24092f1c5/Airship/AirshipAutomation/Source/InAppMessage/View/CloseButton.swift#L40) which are applied to the In App Messages (Banner, Fullscreen, Modal) is not resizable and will be always at 12 pixel in both directions, width and height.

### What is the expected behavior?
The expected behavior is that the dismiss button should not only be configured with a different resource/image but also the width and height should be configurable. 
This would help us in making full use of changing the resource to the need of our application.
So far we cannot use our custom resources because 12x12 pixel is just to small for our need.

### What are the steps to reproduce the unexpected behavior?
Create any in app message

### Do you have logging for the issue?
Its UI.

**Comment by rlepinski** [comment]
👍

**Comment by rlepinski** [comment]
I forgot to close this issue. This was added in 18.5.0
