### ISSUE TITLE
No push notifications after migration to iPhone 16

### ISSUE THREAD

**Issue by r3econ** [urbanairship/ios-library#414]
# Preliminary Info

### What Airship dependencies are you using?

iOS SDK 18.9.1, 18.7.2

# Report

### What unexpected behavior are you seeing?

We are facing a strange issue in our iOS app. Users that bought a new iPhone (e.g. 16/15) and restored their new device from iCloud are not receiving push notifications. 

Can it be that AirShip SDK somehow stays bound to the old device ID or the SDK performs a fresh registration with APNS, etc?
Does anyone know why the users do not receive push notifications after the device restore? Any hints are highly welcomed!

### What is the expected behavior?

Users receive push notifications

**Comment by rlepinski** [comment]
The SDK detects this scenario by storing a value in the keychain for `this device only` and our user defaults. When the device is restored, we compare the two values to detect if its a restore. When its restored, we clear the channel and device token that we have locally cached, then recreate the channel with the token from the device. This should result in a fresh channel that has the proper token.

Are you bypassing Airship's notification permission prompt or does Airship manage that for you? How are you targeting pushes?
