### ISSUE TITLE
add support for macOS

### ISSUE THREAD

**Issue by drmarkpowell** [urbanairship/ios-library#415]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

latest iOS-library

### What are the versions of any relevant development tools you are using?

Xcode 16.0

# Report

As of the latest version of iOS-library, only UIKit-friendly platforms are supported. Please add macOS platform support as well.

**Comment by crow** [comment]
Thanks for the report. We're not currently looking to support macOS but we've shared the feedback with our product team. We do currently support mac catalyst. Going to close this for now, but feel free to add any specific use cases you're trying to enable and I can add them to our internal product feedback. Thanks again!
