### ISSUE TITLE
Inject hot reloading - conflict

### ISSUE THREAD

**Issue by stvalentin** [urbanairship/ios-library#417]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

I'm trying to test a new library in my project called "Inject" that should handle hot reloading via spm

After I enable the project and try to compile it I'm getting errors from your library 

<img width="2223" alt="image" src="https://github.com/user-attachments/assets/72986132-a376-4ea4-bf56-beccc81aa1a6">

Do you have a workaround ?

# Preliminary Info

### What are the versions of any relevant development tools you are using?

# Report

**Comment by rlepinski** [comment]
Those missing attributes/members `Observeinjection` and `enableInjection` are symbols from the inject library that you are trying to use. You should open the issue with them, not us, as we are just providing standard swifui in a framework.
