### ISSUE TITLE
APNSRegistration skipped on restored new devices

### ISSUE THREAD

**Issue by danielbowden** [urbanairship/ios-library#72]
I have come across an issue with the iOS SDK that is still present in 5.0.0 and have confirmed it has happened on three separate devices.

When the new iPhone 6 came out I restored it as a backup of my iPhone 5S (via iTunes) so I was good to go immediately. This has restored app preferences such as UA's use of NSUserDefaults.

When I call `setUserPushNotificationsEnabled:YES` the SDK checks the previous value from NSUserDefaults which returns YES as I previously had push notifications enabled on my 5S.

It then compares the previous value with the new value and skips registration if they are the same.

```objc
UAPush.m
if (enabled != previousValue) {
   self.shouldUpdateAPNSRegistration = YES;
   [self updateRegistration];
}
```

The problem is this is a new device and therefore a new push device token. It has kept my previous push enabled preference when the user defaults have been restored onto the new device and will never prompt or register this new device. So even though the SDK now thinks I have push enabled it was never registered.

Future calls to `[[UAPush shared] updateRegistration];` will not rectify this issue as `self.shouldUpdateAPNSRegistration` is never triggered as being out of date so `[self updateAPNSRegistration];` is never called.

This has happened on both AdHoc builds and Production AppStore releases. I understand the previous value check is in place to avoid registration every time however is there a way to avoid this with new devices?

**Comment by jx2** [comment]
Hi Jeff,

Do you have any updates on this issue, either from UA or Apple? I didn't notice anything in the UA SDK changelogs from 5.0.0 through 5.1.1 that appear to address the problem. If we're going to call this an Apple bug, do you have any workarounds in addition to the ones you mentioned earlier: importing the UAPush+Internal.h header and calling updateAPNSRegistration directly, or enabling the remote-notification background mode? Just weighing the options...

Thanks,
John

**Comment by waltermvp** [comment]
+1

**Comment by jtowle** [comment]
Hi all - 

We believe there are still a few outstanding iOS issues, but we've taken some steps to mitigate them as of 5.0.0. The only one we have not been able to address is one where some applications are not able to receive notifications until they're started once (or sometimes twice) following a restore/upgrade.

If you're seeing these issues, or other upgrade/restore related issues, please send them over to support@urbanairship.com and we can add them to our Radar tickets.

Thanks!
jeff

**Comment by waltermvp** [comment]
@jtowie if the issue still occurs, why is this ticket being closed?

**Comment by jtowle** [comment]
@waltermvp We're not able to do anything about it in our code. We'll need specific reports sent to our support team so that we can attach them to our open radar tickets.

**Comment by waltermvp** [comment]
@jtowle fair enough.
