### ISSUE TITLE
Does not compile without a precompiled header

### ISSUE THREAD

**Issue by younata** [urbanairship/ios-library#85]
UAActionResult.h should not import <Foundation/Foundation.h>, especially when it depends upon UIKit.

I was going to submit a pull request, but don't have time to fill out the contributor agreement.

https://github.com/urbanairship/ios-library/blob/master/Airship/Common/UAActionResult.h#L26
Replace `#import <Foundation/Foundation.h>` with `#import <UIKit/UIKit.h>`

**Comment by rlepinski** [comment]
I believe we fixed this. Please reopen if you have any other issues.
