### ISSUE TITLE
iOS 9 compatability/readiness?

### ISSUE THREAD

**Issue by khappucino-nordstrom** [urbanairship/ios-library#90]
Are there any known issues with iOS9?

**Comment by marc-scig** [comment]
The most current release (6.1.4) is minimally comaptible with iOS 9 in the sense that we've made sure that it runs without crashing, or other unexpected behaviors. However we'll be releasing a more complete update to the SDK once Xcode 7 is out of beta, with support for new features such as bitcode.

**Comment by Blahartinger** [comment]
6.1.4 doesn't appear to be in cocoapods yet.
