### ISSUE TITLE
Please audit nullability

### ISSUE THREAD

**Issue by jshier** [urbanairship/ios-library#91]
Just updated to 6.2.0. Thanks for adopting the nullability modifiers and generics. However, I don't think the nullability annotations have been properly audited. For instance, does it really make sense for `UAirship.push()` to be nullable? If that doesn't exist, isn't something really really broken? I'd really appreciate a proper audit of the nullability annotations so the SDK can be used from Swift without such extreme pain.

**Comment by marc-scig** [comment]
Hi @jshier,

UAirship.push is a lazily initialized object, which will not exist at runtime before takeOff has completed. The SDK is designed to avoid using resources unless they're explicitly needed, and has been for some time. The difference now, with Swift, is that you're using a language that will not allow you to access such a resource without ensuring that it's done safely.

That's not to say that Swift integration with existing Objective-C libraries is especially pain-free in the general case, but we think this collection of nullability annotations in 6.2.0 strikes a reasonable balance without requiring more painful things like major breaking changes or unnecessarily inflated CPU/memory usage.

**Comment by jshier** [comment]
Interesting, but I don't see how that effects the nullability of `UAirship.push()` unless you're saying that its lazy initialization can fail. Is that the case? A quick look through the `UAPush` initializer doesn't show anything too fragile, nor do I see anything that handles a failure from the initializer. Is the framework really designed so that the entire push functionality can be broken?

**Comment by rlepinski** [comment]
If you call `UAirship.push()` before takeoff it will be null. Therefore, it should be marked as nullable.

**Comment by jshier** [comment]
I see. Thanks.

**Comment by rlepinski** [comment]
Its not ideal to have `?`, but its the world we live in. If we can do anything in the future to make it better we will. Thanks for the feedback.
