### ISSUE TITLE
enable bitcode with Xcode 7

### ISSUE THREAD

**Issue by zinthemoney** [urbanairship/ios-library#93]
I know you guys are probably on this one. creating an issue here so others will know when it is ready :octocat: 

http://stackoverflow.com/questions/32415627/urbanairship-ios-sdk-error-in-xcode-7-when-archiving-libuairship-6-2-0-a-uawal

**Comment by marc-scig** [comment]
Hey @zinthemoney,

We'll have a build out with bitcode support very soon, likely early next week. I'll leave a comment here when the update is ready to download.

**Comment by zinthemoney** [comment]
:+1:

**Comment by marc-scig** [comment]
Hi again,

We've updated the SDK with an additional build compiled with bitcode support:

https://bintray.com/urbanairship/iOS/urbanairship-sdk/6.2.1/view

**Comment by jshier** [comment]
ETA on an updated CocoaPod?

**Comment by hcrowell** [comment]
hi @jshier , we just released two updated CocoaPod (one for Xcode 6.4 without bitcode and one for Xcode 7 with bitcode enabled)

**Comment by jshier** [comment]
@hcrowell Thanks, I saw it. You say two CocoaPods, how can I make sure I have the right one?

**Comment by stephenwoodford** [comment]
@jshier Update your Podfile to specify the bitcode version: `pod 'UrbanAirship-iOS-SDK', '6.2.1-bitcode'`

**Comment by hcrowell** [comment]
@jshier What @stephenwoodford said above ^ is correct. :+1:
