### ISSUE TITLE
Warnings on bitcode version (6.2.1-bitcode)

### ISSUE THREAD

**Issue by stephenwoodford** [urbanairship/ios-library#95]
Not sure if this belongs here or on the Cocoapod repo, but I'm getting a lot of warnings from the UrbanAirship library with bitcode enabled (6.2.1-bitcode) that I do not get if I use the non-bitcode version (6.2.1).

Here's a gist with the log: https://gist.github.com/stephenwoodford/42c3291092aa7437163b

**Comment by hcrowell** [comment]
Thanks @stephenwoodford . Can you open the issue in our cocoapod repo please? We will take a look and respond to you in the cocoapod repo. Closing issue for this repo.

**Comment by hcrowell** [comment]
@stephenwoodford fyi the 6.2.1-bitcode version is only for Xcode 7
