### ISSUE TITLE
Deprecation in Static Library 6.3.0

### ISSUE THREAD

**Issue by stoikr** [urbanairship/ios-library#99]
Hi,

I get a deprecation warning in the static Library version 6.3.0 in the UAPushSettingsAddTagViewController class. It uses [UATagUtils createTags:] in line 49, which is actually deprecated.

Greetings

**Comment by hansemannn** [comment]
+1

**Comment by rlepinski** [comment]
UAPushSettingsAddTagViewController has been removed in 7.0.0

**Comment by JamaicanRumCream** [comment]
So what is the replacement method? Where are 'device property tags'? Can't find anything in the docs.

**Comment by Kristina777** [comment]
So what is the replacement method (for createTags:)? Where are 'device property tags'? Can't find anything in the docs.

**Comment by rlepinski** [comment]
See https://github.com/urbanairship/ios-library/issues/123
